### ISSUE TITLE
Problem z tablistą

### ISSUE THREAD

**Issue by SkenPl** [FunnyGuilds/FunnyGuilds#1014]
Mam problem z tablistą plugin działa (CHYBA) dobrze lecz w konsoli dostaje spam co sekunde o to tym logiem PS: tablista nie działa CRAFTBUKKIT-1.8.8
LOGI
[16:36:01] [pool-3-thread-589/WARN]: Exception in thread "pool-3-thread-589" 
[16:36:01] [pool-3-thread-589/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.0.1.1 Tribute-c3578f4 generated an exception while executing task 3795
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.util.runnable.Ticker.getRecentTPS(Ticker.java:30)
	at net.dzikoysk.funnyguilds.util.element.tablist.AbstractTablist.putVars(AbstractTablist.java:179)
	at net.dzikoysk.funnyguilds.util.element.tablist.impl.v1_8_R3.TablistImpl.send(TablistImpl.java:92)
	at net.dzikoysk.funnyguilds.util.runnable.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:70)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by insertt** [comment]
Zaktualizuj plugin do najnowszej wersji: https://github.com/FunnyGuilds/FunnyGuilds/releases/tag/4.4.1
