### ISSUE TITLE
Błąd przy tworzeniu gildii

### ISSUE THREAD

**Issue by oski646** [FunnyGuilds/FunnyGuilds#1024]
Witam, otóż przy tworzeniu gildii występuje taki problem:
```
[23:46:56 ERROR]: [FunnyGuilds]
[23:46:56 ERROR]: [FunnyGuilds] Could not execute update
[23:46:56 ERROR]: [FunnyGuilds]
[23:46:56 ERROR]: [FunnyGuilds] java.sql.SQLException: Field 'regions' doesn't have a default value
[23:46:56 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[23:46:56 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[23:46:56 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[23:46:56 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[23:46:56 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1347)
[23:46:56 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:845)
[23:46:56 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[23:46:56 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[23:46:56 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[23:46:56 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[23:46:56 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[23:46:56 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:72)
[23:46:56 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.DatabaseGuild.save(DatabaseGuild.java:114)
[23:46:56 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:178)
[23:46:56 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.command.ExcCreate.execute(ExcCreate.java:284)
[23:46:56 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:126)
[23:46:56 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:164)
[23:46:56 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:22)
[23:46:56 ERROR]: [FunnyGuilds]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[23:46:56 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[23:46:56 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[23:46:56 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[23:46:56 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:46:56 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:46:56 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[23:46:56 ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:46:56 ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:46:56 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[23:46:56 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[23:46:56 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[23:46:56 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[23:46:56 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[23:46:56 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[23:46:56 ERROR]: [FunnyGuilds]
[23:46:56 ERROR]: [FunnyGuilds] Server Information:
[23:46:56 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.4.2 Tribute-fc6c3db
[23:46:56 ERROR]: [FunnyGuilds]   Bukkit: 1.8.8-R0.1-SNAPSHOT
[23:46:56 ERROR]: [FunnyGuilds]   Java: 1.8.0_172
[23:46:56 ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,5,main]
[23:46:56 ERROR]: [FunnyGuilds]
```
Problem zaczął się tak nagle pojawiać jeśli na serwerze powstało ok. 20-25 gildii.

**Comment by insertt** [comment]
Najnowszy build powinien mieć naprawiony ten błąd.

**Comment by oski646** [comment]
Kiedy mogę się spodziewać najnowszego builda?

**Comment by insertt** [comment]
https://ci.insertt.pl/job/FunnyGuilds/49/

**Comment by oski646** [comment]
```
[00:30:09 ERROR]: [FunnyGuilds]
[00:30:09 ERROR]: [FunnyGuilds] Could not execute update
[00:30:09 ERROR]: [FunnyGuilds]
[00:30:09 ERROR]: [FunnyGuilds] java.sql.SQLException: Column count doesn't match value count at row 1
[00:30:09 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[00:30:09 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[00:30:09 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[00:30:09 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[00:30:09 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[00:30:09 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[00:30:09 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[00:30:09 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[00:30:09 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[00:30:09 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[00:30:09 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[00:30:09 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[00:30:09 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:72)
[00:30:09 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.DatabaseGuild.save(DatabaseGuild.java:114)
[00:30:09 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:178)
[00:30:09 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24)
[00:30:09 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[00:30:09 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[00:30:09 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:30:09 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:30:09 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[00:30:09 ERROR]: [FunnyGuilds]
[00:30:09 ERROR]: [FunnyGuilds] Server Information:
[00:30:09 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.4.2 Tribute-f420941
[00:30:09 ERROR]: [FunnyGuilds]   Bukkit: 1.8.8-R0.1-SNAPSHOT
[00:30:09 ERROR]: [FunnyGuilds]   Java: 1.8.0_172
[00:30:09 ERROR]: [FunnyGuilds]   Thread: Thread[Craft Scheduler Thread - 33,5,main]
[00:30:09 ERROR]: [FunnyGuilds]
```
Czy to ja mam błąd ze swoją bazą danych czy teraz kolejny błąd się pojawił (dalej przy tworzeniu gildii) 😄

**Comment by insertt** [comment]
https://ci.insertt.pl/job/FunnyGuilds/50/

**Comment by oski646** [comment]
Już nie pojawia się żaden błąd ale podczas tworzenia jest odstęp czasu krótki, potem wywala wszystkich z serwera, ale go nie wyłącza, i po chwili można wejść znowu na serwer i gildia się tworzy.
```
[00:50:12 INFO]: oski646 issued server command: /zaloz TEST Testowa
[00:50:33 INFO]: oski646 lost connection: Disconnected
[00:50:34 INFO]: UUID of player _d__d_ is 67bf1c14-9833-3b68-96d4-a97835a931d4
[00:50:37 INFO]: Disconnecting com.mojang.authlib.GameProfile@68a5ce65[id=c1ea5411-1bed-322d-b24e-aa0aa96ca524,name=oski646,properties={textures=[com.mojang.authlib.properties.Property@506cb69]},legacy=false] (/*): §cTen gracz jest juz na serwerze!
[00:50:45 INFO]:  » oski646 zalozyl gildie: TEST (Testowa).
```

**Comment by insertt** [comment]
Ten błąd nie dotyczy zgłoszonego wyżej, stwórz nowy issue wraz z dokładniejszym opisem tego problemu.
