### ISSUE TITLE
NPE podczas inicjalizacji Dummy

### ISSUE THREAD

**Issue by MateoxPL** [FunnyGuilds/FunnyGuilds#1044]
Witam
Problem wygląda następująco 
Posiadam plugin na antylogout - gdy jesteśmy w walce i gracz który jest ofiarą wyjdzie z serwera
wyskakuje taki błąd w konsoli ze strony pluginu FG (natomiast wszystko się odbywa sprawnie mianowicie punkty zostają przydzielone atakującemu i zostaje wyświetlona informacja z pluginu tylko właśnie ten błąd wyskakuje natomiast z kolei gdy wyloguje się atakujący tego problemu nie ma) oto logi z konsoli:

Wersja Serwera: PaperSpigot 1.8.8

> [09:36:05 ERROR]: [FunnyGuilds]
> [09:36:05 ERROR]: [FunnyGuilds]
> [09:36:05 ERROR]: [FunnyGuilds] An error occurred while handling concurrent request
> [09:36:05 ERROR]: [FunnyGuilds]
> [09:36:05 ERROR]: [FunnyGuilds] java.lang.NullPointerException
> [09:36:05 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.element.Dummy.initialize(Dummy.java:40)
> [09:36:05 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.element.Dummy.<init>(Dummy.java:18)
> [09:36:05 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.basic.user.UserCache.getDummy(UserCache.java:160)
> [09:36:05 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.element.DummyManager.updateScore(DummyManager.java:17)
> [09:36:05 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.requests.dummy.DummyGlobalUpdateUserRequest.execute(DummyGlobalUpdateUserRequest.java:17)
> [09:36:05 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)
> [09:36:05 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)
> [09:36:05 ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> [09:36:05 ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(Unknown Source)
> [09:36:05 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> [09:36:05 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> [09:36:05 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Unknown Source)
> [09:36:05 ERROR]: [FunnyGuilds]
> [09:36:05 ERROR]: [FunnyGuilds] Server Information:
> [09:36:05 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.4.2 Tribute-8d4f43e
> [09:36:05 ERROR]: [FunnyGuilds]   Bukkit: 1.8.8-R0.2-SNAPSHOT
> [09:36:05 ERROR]: [FunnyGuilds]   Java: 1.8.0_211
> [09:36:05 ERROR]: [FunnyGuilds]   Thread: Thread[pool-6-thread-1,5,main]
> [09:36:05 ERROR]: [FunnyGuilds]   Loaded plugins: Schowek 1.0, FastAsyncWorldEdit 18.04.29-81a76df-1092-19.5.26, Skript 2.2-dev36, TerrainControl 2.7.2, ZAnvil 1.0, NoClocks 1.21, koxCobbleX 0.1, skript-db 0.1.1, Skungee 1.0.6b, SkQuery 3.6.0-Lime, ViaVersion 1.3.0, Vault 1.5.6-b49, UltraPermissions 4.0.6, ProtocolLib 4.4.0, Skellett 1.9.6b, WorldEdit 6.1.7;dd00bb1, TradePlus 3.16, HolographicDisplays 2.3.2, WorldGuard 6.1.3-SNAPSHOT;c904242, FunnySkAddon-Extended 1.8.8, skRayFall 1.9.12, CombatLogPro 1.5.8
> [09:36:05 ERROR]: [FunnyGuilds]

**Comment by MateoxPL** [comment]
Niestety nadal ten błąd występuje

**Comment by insertt** [comment]
Czy mógłbyś podesłać stacktrace z wersji po poprawkach?

**Comment by MateoxPL** [comment]
Proszę:

> [16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds] 
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds] An error occurred while handling concurrent request
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds] 
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds] java.lang.NullPointerException
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.element.Dummy.updateScore(Dummy.java:26)
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.element.DummyManager.updateScore(DummyManager.java:17)
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.requests.dummy.DummyGlobalUpdateUserRequest.execute(DummyGlobalUpdateUserRequest.java:17)
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Unknown Source)
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds] 
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds] Server Information:
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]   FunnyGuilds: 4.4.2 Tribute-68ba924
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]   Bukkit: 1.8.8-R0.2-SNAPSHOT
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]   Java: 1.8.0_211
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]   Thread: Thread[pool-6-thread-1,5,main]
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]   Loaded plugins: Schowek 1.0, Skript 2.2-dev36, TerrainControl 2.7.2, ZAnvil 1.0, NoClocks 1.21, skript-db 0.1.1, SkQuery 3.6.0-Lime, xDisco 1.0, xOtchlan 1.0, xHolo 1.0, Skellett 1.9.6b, FastAsyncWorldEdit 18.04.29-81a76df-1092-19.5.26, ViaVersion 1.3.0, KraftPandors 1.0, Vault 1.5.6-b49, UltraPermissions 4.0.6, WorldEdit 6.1.7;dd00bb1, ProtocolLib 4.4.0, TradePlus 3.16, HolographicDisplays 2.3.2, WorldGuard 6.1.3-SNAPSHOT;c904242, FunnySkAddon-Extended 1.8.8, skRayFall 1.9.12, CombatLogPro 1.5.8
[16:16:02] [pool-6-thread-1/ERROR]: [FunnyGuilds]

**Comment by insertt** [comment]
Czy błąd dalej występuje?
