### ISSUE TITLE
Błąd w zapytaniu do bazy danych

### ISSUE THREAD

**Issue by h4p1x** [FunnyGuilds/FunnyGuilds#1045]
[14:02:47 ERROR]: [FunnyGuilds]
[14:02:47 ERROR]: [FunnyGuilds] Could not execute update
[14:02:47 ERROR]: [FunnyGuilds]
[14:02:47 ERROR]: [FunnyGuilds] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1000','0','0','0','null') ON DUPLICATE KEY UPDATE `name`='Cysop\',`points`='1000' at line 1
[14:02:47 ERROR]: [FunnyGuilds]        at sun.reflect.GeneratedConstructorAccessor210.newInstance(Unknown Source)
[14:02:47 ERROR]: [FunnyGuilds]        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:02:47 ERROR]: [FunnyGuilds]        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[14:02:47 ERROR]: [FunnyGuilds]        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[14:02:47 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[14:02:47 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[14:02:47 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:72)
[14:02:47 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55)
[14:02:47 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:154)
[14:02:47 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24)
[14:02:47 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[14:02:47 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:02:47 ERROR]: [FunnyGuilds]        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[14:02:47 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:02:47 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:02:47 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[14:02:47 ERROR]: [FunnyGuilds]
[14:02:47 ERROR]: [FunnyGuilds] Server Information:
[14:02:47 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.4.2 Tribute-8d4f43e
[14:02:47 ERROR]: [FunnyGuilds]   Bukkit: 1.8.8-R0.1-SNAPSHOT
[14:02:47 ERROR]: [FunnyGuilds]   Java: 1.8.0_141
[14:02:47 ERROR]: [FunnyGuilds]   Thread: Thread[Craft Scheduler Thread - 799,5,main]
[14:02:47 ERROR]: [FunnyGuilds]   Loaded plugins: **********
[14:02:47 ERROR]: [FunnyGuilds]

**Comment by Kamilkime** [comment]
Najnowszy build powinien już nie mieć tego problemu
https://ci.insertt.pl/job/FunnyGuilds/77/
