### ISSUE TITLE
Blad przy update mysql

### ISSUE THREAD

**Issue by h4p1x** [FunnyGuilds/FunnyGuilds#1049]
[08:57:52 ERROR]: [FunnyGuilds]
[08:57:52 ERROR]: [FunnyGuilds] Could not execute update
[08:57:52 ERROR]: [FunnyGuilds]
[08:57:52 ERROR]: [FunnyGuilds] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[08:57:52 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
[08:57:52 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[08:57:52 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
[08:57:52 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
[08:57:52 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:65)
[08:57:52 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55)
[08:57:52 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:146)
[08:57:52 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24)
[08:57:52 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[08:57:52 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[08:57:52 ERROR]: [FunnyGuilds]        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[08:57:52 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08:57:52 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08:57:52 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[08:57:52 ERROR]: [FunnyGuilds]
[08:57:52 ERROR]: [FunnyGuilds] Server Information:
[08:57:52 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.4.2 Tribute-4c503c8
[08:57:52 ERROR]: [FunnyGuilds]   Bukkit: 1.8.8-R0.1-SNAPSHOT
[08:57:52 ERROR]: [FunnyGuilds]   Java: 1.8.0_141
[08:57:52 ERROR]: [FunnyGuilds]   Thread: Thread[Craft Scheduler Thread - 452,5,main]
[08:57:52 ERROR]: [FunnyGuilds]   Loaded plugins: PermissionsEx 1.23.4, NoCheatPlus 3.16.0-RC-sMD5NET-b1134, CoreMax-Enchant 1.0, WorldEdit 6.1.8-SNAPSHOT;cd4729f, CoreMax-Core 3.8.1, ViaVersion 1.6.0, Shopkeepers 1.68, TerrainControl 2.7.2, CoreMax-Schowek 1.1, CoreMax-Drop 1.5, WorldGuard 6.1.3-SNAPSHOT;c904242
[08:57:52 ERROR]: [FunnyGuilds]
[08:57:53 ERROR]: [FunnyGuilds]
[08:57:53 ERROR]: [FunnyGuilds] Could not execute update
[08:57:53 ERROR]: [FunnyGuilds]
[08:57:53 ERROR]: [FunnyGuilds] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[08:57:53 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
[08:57:53 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[08:57:53 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
[08:57:53 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
[08:57:53 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:65)
[08:57:53 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55)
[08:57:53 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:146)
[08:57:53 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24)
[08:57:53 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[08:57:53 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[08:57:53 ERROR]: [FunnyGuilds]        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[08:57:53 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08:57:53 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08:57:53 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[08:57:53 ERROR]: [FunnyGuilds]
[08:57:53 ERROR]: [FunnyGuilds] Server Information:
[08:57:53 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.4.2 Tribute-4c503c8
[08:57:53 ERROR]: [FunnyGuilds]   Bukkit: 1.8.8-R0.1-SNAPSHOT
[08:57:53 ERROR]: [FunnyGuilds]   Java: 1.8.0_141
[08:57:53 ERROR]: [FunnyGuilds]   Thread: Thread[Craft Scheduler Thread - 1583,5,main]
[08:57:53 ERROR]: [FunnyGuilds]   Loaded plugins: PermissionsEx 1.23.4, NoCheatPlus 3.16.0-RC-sMD5NET-b1134, CoreMax-Enchant 1.0, WorldEdit 6.1.8-SNAPSHOT;cd4729f, CoreMax-Core 3.8.1, ViaVersion 1.6.0, Shopkeepers 1.68, TerrainControl 2.7.2, CoreMax-Schowek 1.1, CoreMax-Drop 1.5, WorldGuard 6.1.3-SNAPSHOT;c904242
[08:57:53 ERROR]: [FunnyGuilds]

co sekunde mam taki blad

**Comment by h4p1x** [comment]
w innych pluginach jest normalnie

**Comment by h4p1x** [comment]
https://pastebin.com/8m4aZrcK kolejny blad przy lagowaniu

**Comment by insertt** [comment]
Czy błąd występuje z samym FunnyGuilds na serwerze?

**Comment by Pak3rP** [comment]
Usun reszte pluginow z serwera,  bo w tym linku co podałes widać że masz sporo pluginów.

Ps. Pluginy z CoreMaxa prawdopodobnie mają backdoory

**Comment by h4p1x** [comment]
@Pak3rP CoreMax to mój serwer i to nie są pluginy z wycieku

@insertt inne pluginy używające MySQL nie wywalają żadnych błędów

**Comment by h4p1x** [comment]
@Pak3rP dużo pluginow? Mam 13 pluginow większość serwerów ma +30 xD

**Comment by insertt** [comment]
Co nie oznacza, że te pluginy nie gubią połączeń, dlatego prosiłem o reprodukcje błędu z samym FunnyGuilds na serwerze.

**Comment by h4p1x** [comment]
@insertt nie mogę usunąć innych pluginow, ten błąd pojawia się po około 6 godzinach i muszę restartować serwer żeby zniknął

**Comment by insertt** [comment]
Prawdopodobnie któryś z pluginów na serwerze gubi połączenia, przez co FunnyGuilds nie może nawiązać połączenia w celu wykonania operacji. Bez reprodukcji błędu używając wyłącznie FunnyGuilds na serwerze nie jesteśmy w stanie pomóc.
