### ISSUE TITLE
[Problem] FunnyGuilds nie reaguje na zabicie Gracza

### ISSUE THREAD

**Issue by Rollczi** [FunnyGuilds/FunnyGuilds#1051]
Mam Problem z dodawaniem punktów do rankingu graczy.
Sytuacja jest taka
1. AntyLogOut otaguje gracza (Jest podczas walki)
2. Gracz wylogowuje się z Gry
3. Plugin zabija Gracza wypadają itemy itd.
4. FunnyGuilds nie reaguje na zabicie. (nie zmienia punktacji) 

Plugin AntyLogOut: CombatLogX
https://www.spigotmc.org/resources/combatlogx.31689/

Dodatkowo kiedy jeden gracz zalogował się na serwer i po chwili FunnyGuilds wysyła błąd:
```
[21:07:08 ERROR]: [FunnyGuilds]

[21:07:08 ERROR]: [FunnyGuilds] An error occurred while handling concurrent request

[21:07:08 ERROR]: [FunnyGuilds]

[21:07:08 ERROR]: [FunnyGuilds] java.lang.NullPointerException

[21:07:08 ERROR]: [FunnyGuilds] at net.dzikoysk.funnyguilds.element.Dummy.initialize(Dummy.java:40)

[21:07:08 ERROR]: [FunnyGuilds] at net.dzikoysk.funnyguilds.element.Dummy.<init>(Dummy.java:18)

[21:07:08 ERROR]: [FunnyGuilds] at net.dzikoysk.funnyguilds.basic.user.UserCache.getDummy(UserCache.java:160)

[21:07:08 ERROR]: [FunnyGuilds] at net.dzikoysk.funnyguilds.element.DummyManager.updateScore(DummyManager.java:17)

[21:07:08 ERROR]: [FunnyGuilds] at net.dzikoysk.funnyguilds.concurrency.requests.dummy.DummyGlobalUpdateUserRequest.execute(DummyGlobalUpdateUserRequest.java:17)

[21:07:08 ERROR]: [FunnyGuilds] at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)

[21:07:08 ERROR]: [FunnyGuilds] at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)

[21:07:08 ERROR]: [FunnyGuilds] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[21:07:08 ERROR]: [FunnyGuilds] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[21:07:08 ERROR]: [FunnyGuilds] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

[21:07:08 ERROR]: [FunnyGuilds] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

[21:07:08 ERROR]: [FunnyGuilds] at java.lang.Thread.run(Thread.java:748)

[21:07:08 ERROR]: [FunnyGuilds]

[21:07:08 ERROR]: [FunnyGuilds] Server Information:

[21:07:08 ERROR]: [FunnyGuilds] FunnyGuilds: 4.4.2 Tribute-8d4f43e

[21:07:08 ERROR]: [FunnyGuilds] Bukkit: 1.8.8-R0.1-SNAPSHOT

[21:07:08 ERROR]: [FunnyGuilds] Java: 1.8.0_141

[21:07:08 ERROR]: [FunnyGuilds] Thread: Thread[pool-6-thread-1,5,main]
```
(ten błąd pokazał się tylko raz nie powtarzał się i chyba nie ma powiązania z moim problemem)

Wersje:
/ver
 This server is running CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing 
API version 1.8.8-R0.1-SNAPSHOT)
 Error obtaining version information

/ver FunnyGuilds
 FunnyGuilds version 4.4.2 Tribute-8d4f43e
 Website: https://github.com/FunnyGuilds
 Author: FunnyGuilds Team

/ver CombatLogX
 CombatLogX version 9.7.1.3
 An expandable combat-tagging plugin with actual logging options
 Author: SirBlobman

**Comment by Rollczi** [comment]
;-; help?

**Comment by insertt** [comment]
Zaktualizuj FunnyGuilds do najnowszej wersji: https://ci.insertt.dev/job/FunnyGuilds/

**Comment by Rollczi** [comment]
okej
