### ISSUE TITLE
MySQL błąd

### ISSUE THREAD

**Issue by zSpookyPL** [FunnyGuilds/FunnyGuilds#1076]
W config.yml zmieniłem tylko że data-model: MYSQL i dane do mysql i nie działa ani na 1.8.8 ani na 1.9.4 działa tylko na 1.14.2 a potrzebuje na 1.8.8. WERSJA FunnyGuilds 4.5.0.

```
[17:52:14] [Server thread/INFO]: [FunnyGuilds] Enabling FunnyGuilds v4.5.0 Tribute-2f6a538
[17:52:14] [Server thread/ERROR]: Error occurred while enabling FunnyGuilds v4.5.0 Tribute-2f6a538 (Is it up to date?)
java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/spi/ExtendedLogger;
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:37) ~[?:?]
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:29) ~[?:?]
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:52) ~[?:?]
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383) ~[?:?]
	at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.Database.<init>(Database.java:21) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.Database.getInstance(Database.java:46) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.SQLDataModel.load(SQLDataModel.java:36) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:143) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]


[17:54:14] [Server thread/INFO]: [FunnyGuilds] Disabling FunnyGuilds v4.5.0 Tribute-2f6a538
[17:54:14] [Server thread/ERROR]: Error occurred while disabling FunnyGuilds v4.5.0 Tribute-2f6a538 (Is it up to date?)
java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.FunnyGuilds.onDisable(FunnyGuilds.java:202) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:593) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by zSpookyPL** [comment]
Pomoże ktos?

**Comment by insertt** [comment]
W najnowszym nightly błąd powinien być naprawiony.
