### ISSUE TITLE
Problem z TabListą

### ISSUE THREAD

**Issue by majkrafter** [FunnyGuilds/FunnyGuilds#1078]
Oto błąd z konsoli:
```
[FunnyGuilds] 
[FunnyGuilds]: An error occurred while handling concurrent request
[FunnyGuilds] 
[FunnyGuilds]: java.lang.NullPointerException
[FunnyGuilds]: at net.dzikoysk.funnyguilds.concurrency.requests.ReloadRequest.execute(ReloadRequest.java:27)
[FunnyGuilds]: at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)
[FunnyGuilds]: at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)
[FunnyGuilds]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[FunnyGuilds]: at java.util.concurrent.FutureTask.run(Unknown Source)
[FunnyGuilds]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[FunnyGuilds]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[FunnyGuilds]: at java.lang.Thread.run(Unknown Source)
[FunnyGuilds] 
[FunnyGuilds]: Server Information:
[FunnyGuilds]: FunnyGuilds: 4.5.0 Tribute-2f6a538
[FunnyGuilds]: Bukkit: 1.8.8-R0.1-SNAPSHOT
[FunnyGuilds]: Java: 1.8.0_211
[FunnyGuilds]: Thread: Thread[pool-8-thread-1,5,main]
[FunnyGuilds]: Loaded plugins: _matatjahuShop-dragonix 0.1, Schowek 1.0, WorldEdit 6.1;no_git_id, TimTheEnchanter 3.0, Skript 2.1.2, Essentials TeamCity, PacketListenerApi 3.4.4, eastStone 4.0, UProtector 2.7, thBans 1.0, Z-BlockedCmd 1.0, SkQuery 3.21.4, WorldBorder 1.8.7, NametagEdit 4.1.7, pcRandomTp-1.8.8 1.0, Wiadomosci 1.0, ProtocolLib 4.3.0, NoCheatPlus 3.16.0-RC-sMD5NET-b1134, GodMotd 1.0, SkinsRestorer 13.7.1, yetrrBorder 1.0.3, rhDrop 0.9.93, Z-BlokadaKomend 1.0, pcCheck-1.3 1.3, Shopkeepers 1.68, TimeTNT 1.0, WildSkript 1.8, EssentialsChat TeamCity, Stoniarki 1.0, youcoreEnchant 1.0, PermissionsEx 1.23.4, F-Alert 1.0 PreBeta, xnDisco 1.0, pcCombat-1.8.8 1.6, KeepTheWeather 1.0, ageUnknown 1.0, Vault 1.4.1-b436, EssentialsSpawn TeamCity, HolographicDisplays 2.2.2, TreasureChest 8.4.4, ChestCommands 3.2.0, BugowanieBP 1.0, WorldGuard 6.1.3-SNAPSHOT;c904242
[FunnyGuilds]
```

**Comment by insertt** [comment]
Wrzuć cały log serwera na https://pastebin.com/

**Comment by majkrafter** [comment]
https://pastebin.com/2acjAQjW

**Comment by insertt** [comment]
Czy w najnowszym nightly problem zniknął?

**Comment by insertt** [comment]
Z powodu braku aktywności zamykam issue.
