### ISSUE TITLE
Błąd po założeniu gildii

### ISSUE THREAD

**Issue by yetrr** [FunnyGuilds/FunnyGuilds#1079]
Config nie ruszany, defaultowy, rzuca błąd od razu po założeniu gildii.

```java [12:29:09 ERROR]: [FunnyGuilds]
[12:29:09 ERROR]: [FunnyGuilds] Could not update guild
[12:29:09 ERROR]: [FunnyGuilds]
[12:29:09 ERROR]: [FunnyGuilds] java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/spi/ExtendedLogger;
[12:29:09 ERROR]: [FunnyGuilds]        at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:37)
[12:29:09 ERROR]: [FunnyGuilds]        at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:29)
[12:29:09 ERROR]: [FunnyGuilds]        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:52)
[12:29:09 ERROR]: [FunnyGuilds]        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
[12:29:09 ERROR]: [FunnyGuilds]        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
[12:29:09 ERROR]: [FunnyGuilds]        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
[12:29:09 ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
[12:29:09 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.Database.<init>(Database.java:21)
[12:29:09 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.Database.getInstance(Database.java:46)
[12:29:09 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.requests.database.DatabaseUpdateGuildRequest.execute(DatabaseUpdateGuildRequest.java:24)
[12:29:09 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)
[12:29:09 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)
[12:29:09 ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:29:09 ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(Unknown Source)
[12:29:09 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:29:09 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:29:09 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Unknown Source)
[12:29:09 ERROR]: [FunnyGuilds]
[12:29:09 ERROR]: [FunnyGuilds] Server Information:
[12:29:09 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.5.0 Tribute-2f6a538
[12:29:09 ERROR]: [FunnyGuilds]   Bukkit: 1.8.8-R0.1-SNAPSHOT
[12:29:09 ERROR]: [FunnyGuilds]   Java: 1.8.0_181
[12:29:09 ERROR]: [FunnyGuilds]   Thread: Thread[pool-4-thread-1,5,main]
[12:29:09 ERROR]: [FunnyGuilds]   Loaded plugins: PermissionsEx 1.23.3, WorldEdit 6.1;no_git_id
[12:29:09 ERROR]: [FunnyGuilds]

**Comment by Kamilkime** [comment]
Najnowsze nightly powinno mieć to już poprawione
https://ci.insertt.dev/job/FunnyGuilds/job/master/
