### ISSUE TITLE
Błąd przy najnowszej wersji przy założeniu gildii 

### ISSUE THREAD

**Issue by GGBVSKY** [FunnyGuilds/FunnyGuilds#1082]
Wersja serwera 1.8.8 PaperSpigot, błąd przy założeniu gildii, dane MYSQL podane poprawie, w configu tylko zmienione regions-enabled: false

```
[19:55:55 ERROR]: [FunnyGuilds]
[19:55:55 INFO]: ggbvsky zalozyl gildie o nazwie TESTOWAGILDIA i tagu TEST!
[19:55:59 ERROR]: [FunnyGuilds]
[19:55:59 ERROR]: [FunnyGuilds] Could not execute update
[19:55:59 ERROR]: [FunnyGuilds]
[19:55:59 ERROR]: [FunnyGuilds] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'points' in 'field list'
[19:55:59 ERROR]: [FunnyGuilds]at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:55:59 ERROR]: [FunnyGuilds]at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:55:59 ERROR]: [FunnyGuilds]at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:55:59 ERROR]: [FunnyGuilds]at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.Util.getInstance(Util.java:382)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[19:55:59 ERROR]: [FunnyGuilds]at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[19:55:59 ERROR]: [FunnyGuilds]at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[19:55:59 ERROR]: [FunnyGuilds]at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:72)
[19:55:59 ERROR]: [FunnyGuilds]at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55)
[19:55:59 ERROR]: [FunnyGuilds]at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:146)
[19:55:59 ERROR]: [FunnyGuilds]at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24)
[19:55:59 ERROR]: [FunnyGuilds]at net.dzikoysk.funnyguilds.data.DataPersistenceHandler$$Lambda$136/903435488.run(Unknown Source)
[19:55:59 ERROR]: [FunnyGuilds]at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[19:55:59 ERROR]: [FunnyGuilds]at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:55:59 ERROR]: [FunnyGuilds]at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[19:55:59 ERROR]: [FunnyGuilds]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[19:55:59 ERROR]: [FunnyGuilds]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[19:55:59 ERROR]: [FunnyGuilds]at java.lang.Thread.run(Thread.java:745)
[19:55:59 ERROR]: [FunnyGuilds]
[19:55:59 ERROR]: [FunnyGuilds] Server Information:
[19:55:59 ERROR]: [FunnyGuilds]FunnyGuilds: 4.5.0 Tribute-13d333a
[19:55:59 ERROR]: [FunnyGuilds]Bukkit: 1.8.8-R0.1-SNAPSHOT
[19:55:59 ERROR]: [FunnyGuilds]Java: 1.8.0_40
[19:55:59 ERROR]: [FunnyGuilds]Thread: Thread[Craft Scheduler Thread - 6,5,main]
[19:55:59 ERROR]: [FunnyGuilds]Loaded plugins: WorldEdit 5.6.1, Skript 2.1.2, Essentials TeamCity, killStats 3.0, xD-Bans 1.4, PlaceholderAPI 2.10.3, Z-BlockedCmd 1.0, ZavMessage 1.1.1, SkQuery 3.21.4, iAuth 1.2-DEV, iAntyLogout 1.4.3, NametagEdit 4.1.7, KUnkownCMD 1.0, Multiverse-Core 2.5.0-b727, ProtocolLib 4.2.1, skRayFall 1.9.10, zTopList 0.3, WildSkript 1.8, EssentialsChat TeamCity, PermissionsEx 1.20.4, pc_Disco-1.8.8 1.0, kodiSchowek 1.0-SNAPSHOT, MOTD 2.3.6, Vault 1.7.2-b107, ChatManager 1.0, EssentialsSpawn TeamCity, TitleManager 2.1.5, ProtocolTab 1.1.2, WorldGuard 6.1
[19:55:59 ERROR]: [FunnyGuilds]
[19:55:59 ERROR]: [FunnyGuilds]
[19:55:59 ERROR]: [FunnyGuilds] Could not execute update
[19:55:59 ERROR]: [FunnyGuilds]
[19:55:59 ERROR]: [FunnyGuilds] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'guild' in 'field list'
[19:55:59 ERROR]: [FunnyGuilds]at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:55:59 ERROR]: [FunnyGuilds]at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:55:59 ERROR]: [FunnyGuilds]at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:55:59 ERROR]: [FunnyGuilds]at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.Util.getInstance(Util.java:382)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[19:55:59 ERROR]: [FunnyGuilds]at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[19:55:59 ERROR]: [FunnyGuilds]at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[19:55:59 ERROR]: [FunnyGuilds]at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[19:55:59 ERROR]: [FunnyGuilds]at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:72)
[19:55:59 ERROR]: [FunnyGuilds]at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55)
[19:55:59 ERROR]: [FunnyGuilds]at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:146)
[19:55:59 ERROR]: [FunnyGuilds]at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24)
[19:55:59 ERROR]: [FunnyGuilds]at net.dzikoysk.funnyguilds.data.DataPersistenceHandler$$Lambda$136/903435488.run(Unknown Source)
[19:55:59 ERROR]: [FunnyGuilds]at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[19:55:59 ERROR]: [FunnyGuilds]at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:55:59 ERROR]: [FunnyGuilds]at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[19:55:59 ERROR]: [FunnyGuilds]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[19:55:59 ERROR]: [FunnyGuilds]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[19:55:59 ERROR]: [FunnyGuilds]at java.lang.Thread.run(Thread.java:745)
[19:55:59 ERROR]: [FunnyGuilds]
[19:55:59 ERROR]: [FunnyGuilds] Server Information:
[19:55:59 ERROR]: [FunnyGuilds]FunnyGuilds: 4.5.0 Tribute-13d333a
[19:55:59 ERROR]: [FunnyGuilds]Bukkit: 1.8.8-R0.1-SNAPSHOT
[19:55:59 ERROR]: [FunnyGuilds]Java: 1.8.0_40
[19:55:59 ERROR]: [FunnyGuilds]Thread: Thread[Craft Scheduler Thread - 6,5,main]
[19:55:59 ERROR]: [FunnyGuilds]Loaded plugins: WorldEdit 5.6.1, Skript 2.1.2, Essentials TeamCity, killStats 3.0, xD-Bans 1.4, PlaceholderAPI 2.10.3, Z-BlockedCmd 1.0, ZavMessage 1.1.1, SkQuery 3.21.4, iAuth 1.2-DEV, iAntyLogout 1.4.3, NametagEdit 4.1.7, KUnkownCMD 1.0, Multiverse-Core 2.5.0-b727, ProtocolLib 4.2.1, skRayFall 1.9.10, zTopList 0.3, WildSkript 1.8, EssentialsChat TeamCity, PermissionsEx 1.20.4, pc_Disco-1.8.8 1.0, kodiSchowek 1.0-SNAPSHOT, MOTD 2.3.6, Vault 1.7.2-b107, ChatManager 1.0, EssentialsSpawn TeamCity, TitleManager 2.1.5, ProtocolTab 1.1.2, WorldGuard 6.1
```

**Comment by GGBVSKY** [comment]
Można wiedzieć kiedy powyższy ERROR będzie poprawiony?

**Comment by insertt** [comment]
Usuń strukturę bazy dla pluginu FunnyGuilds, włącz ponownie serwer i daj znać czy błąd dalej występuje.
