### ISSUE TITLE
Problem z wiadomością o zabójstwie

### ISSUE THREAD

**Issue by majkrafter** [FunnyGuilds/FunnyGuilds#1085]
Po zabójstwie nie pokazuje się wiadomość z pluginu, tylko customowa z minecrafta. Wyskakuje taki błąd w konsoli:
```
25.07.2019 21:44:55
21:44:55Could not pass event PlayerDeathEvent to FunnyGuilds v4.5.0 Tribute-2f6a538
Console 25.07.2019 21:44:55
21:44:55org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:425) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:822) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1382) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@377889b4
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
at net.dzikoysk.funnyguilds.util.nms.PacketSender.sendPacket(PacketSender.java:67) ~[?:?]
at net.dzikoysk.funnyguilds.util.nms.PacketSender.lambda$sendPacket$1(PacketSender.java:54) ~[?:?]
at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_221]
at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:1.8.0_221]
at net.dzikoysk.funnyguilds.util.nms.PacketSender.sendPacket(PacketSender.java:54) ~[?:?]
at net.dzikoysk.funnyguilds.util.nms.PacketSender.sendPacket(PacketSender.java:46) ~[?:?]
at net.dzikoysk.funnyguilds.listener.PlayerDeath.onDeath(PlayerDeath.java:273) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
... 23 more
```

**Comment by insertt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/issues/1073, w najnowszym [nightly](https://ci.insertt.dev/job/FunnyGuilds/job/master/lastSuccessfulBuild/artifact/target/FunnyGuilds%204.5.0%20(MC%201.8-1.14).jar) problem został naprawiony.
