### ISSUE TITLE
Błąd w konsoli.

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1134]
Używam najnowszej wersji Funnyguilds nightly, który mam połączony z bazą danych, bez wersji nightly tych błędów było wiele mniej, ale miałem spróbować tej wersji. Wina pluginu czy mojej konfiguracji? Wersja Spigot: 1.12.2

> [08:43:20] [Craft Scheduler Thread - 19/WARN]: HikariPool-1 - Connection com.mysql.jdbc.JDBC4Connection@5915bad1 marked as broken because of SQLSTATE(08003), ErrorCode(0)
> com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1187) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1182) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.ConnectionImpl.clientPrepareStatement(ConnectionImpl.java:1388) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4110) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4040) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:318) ~[?:?]
> 	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:66) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:146) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-d21162c-61e0c69]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
> [08:43:20] [Craft Scheduler Thread - 18/WARN]: HikariPool-1 - Connection com.mysql.jdbc.JDBC4Connection@46ca3d14 marked as broken because of SQLSTATE(08003), ErrorCode(0)
> com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1187) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1182) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.ConnectionImpl.clientPrepareStatement(ConnectionImpl.java:1388) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4110) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4040) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:318) ~[?:?]
> 	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:66) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:146) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-d21162c-61e0c69]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
> [08:43:20] [Craft Scheduler Thread - 19/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.5.1 Tribute-5eb9ecc generated an exception while executing task 36
> java.lang.IllegalArgumentException: Plugin already initialized!
> 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at net.dzikoysk.funnyguilds.FunnyGuilds.<init>(FunnyGuilds.java:79) ~[?:?]
> 	at net.dzikoysk.funnyguilds.FunnyGuilds.getInstance(FunnyGuilds.java:307) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:149) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-d21162c-61e0c69]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
> Caused by: java.lang.IllegalStateException: Initial initialization
> 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at net.dzikoysk.funnyguilds.FunnyGuilds.<init>(FunnyGuilds.java:79) ~[?:?]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:308) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	... 1 more
> [08:43:20] [Craft Scheduler Thread - 18/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.5.1 Tribute-5eb9ecc generated an exception while executing task 36
> java.lang.IllegalArgumentException: Plugin already initialized!
> 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at net.dzikoysk.funnyguilds.FunnyGuilds.<init>(FunnyGuilds.java:79) ~[?:?]
> 	at net.dzikoysk.funnyguilds.FunnyGuilds.getInstance(FunnyGuilds.java:307) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:149) ~[?:?]
> 	at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-d21162c-61e0c69]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
> Caused by: java.lang.IllegalStateException: Initial initialization
> 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at net.dzikoysk.funnyguilds.FunnyGuilds.<init>(FunnyGuilds.java:79) ~[?:?]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
> 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:308) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) ~[server.jar:git-Spigot-d21162c-61e0c69]
> 	... 1 more

**Comment by insertt** [comment]
Najnowsze nightly dostępne [tutaj](https://ci.insertt.dev/job/FunnyGuilds/job/master/) powinno rozwiązać ten problem.

**Comment by radek203** [comment]
@insertt Dalej coś nie tak chyba
[13:24:47] [Server thread/INFO]: [FunnyGuilds] Disabling FunnyGuilds v4.5.1 Tribute-e639992
[13:24:47] [Server thread/WARN]: HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@984d589 (No operations allowed after connection closed.)
[13:24:47] [Server thread/WARN]: HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@218f2d94 (No operations allowed after connection closed.)
[13:24:47] [Server thread/WARN]: HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@e088cb1 (No operations allowed after connection closed.)
[13:24:49] [Server thread/INFO]: HikariPool-1 - Shutdown initiated...
[13:24:49] [Server thread/INFO]: HikariPool-1 - Shutdown completed.
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds] 
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds] 
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds] Could not execute update
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds] Could not execute update
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds] 
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds] 
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds] java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds] java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:91)
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:91)
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:65)
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:65)
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55)
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55)
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:146)
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:146)
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24)
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24)
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Unknown Source)
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Unknown Source)
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds] 
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds] 
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds] Server Information:
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds] Server Information:
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]   FunnyGuilds: 4.5.1 Tribute-e639992
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]   FunnyGuilds: 4.5.1 Tribute-e639992
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]   Bukkit: 1.12.2-R0.1-SNAPSHOT
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]   Bukkit: 1.12.2-R0.1-SNAPSHOT
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]   Java: 1.8.0_221
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]   Java: 1.8.0_221
[13:24:49] [Craft Scheduler Thread - 4/ERROR]: [FunnyGuilds]   Thread: Thread[Craft Scheduler Thread - 4,5,main]
[13:24:49] [Craft Scheduler Thread - 3/ERROR]: [FunnyGuilds]   Thread: Thread[Craft Scheduler Thread - 3,5,main]
[13:24:49] [Craft Scheduler Thread - 3/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.5.1 Tribute-e639992 generated an exception while executing task 32
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:149) ~[?:?]
	at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-dcd1643-e60fc34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[13:24:49] [Craft Scheduler Thread - 4/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.5.1 Tribute-e639992 generated an exception while executing task 32
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:149) ~[?:?]
	at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-dcd1643-e60fc34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by insertt** [comment]
Podeślij cały log serwera

**Comment by radek203** [comment]
Mogę jakoś na priv? Nie chce udostępniać listy pluginów które posiadam.

**Comment by insertt** [comment]
Możesz skorzystać z naszego discorda
