### ISSUE TITLE
Problem z usuwaniem gildii po walce

### ISSUE THREAD

**Issue by misiekhardcore** [FunnyGuilds/FunnyGuilds#1145]
Cześć,

Mam problem, którego rozwiązania nie mogę znaleźć od kilku dni, dlatego też zakładam nowy wątek.

Co sekundę w konsoli pojawia się taki błąd:

`[12:20:13] [Craft Scheduler Thread - 4/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.5.1 Tribute-e61b796 generated an exception while executing task 19
java.lang.IllegalStateException: GuildDeleteEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
	at net.dzikoysk.funnyguilds.event.SimpleEventHandler.handle(SimpleEventHandler.java:8) ~[?:?]
	at net.dzikoysk.funnyguilds.system.GuildValidationHandler.validateGuildLifetime(GuildValidationHandler.java:29) ~[?:?]
	at net.dzikoysk.funnyguilds.system.GuildValidationHandler.run(GuildValidationHandler.java:18) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`

Jednocześnie gracze skarżą się, że po pokonaniu gildii przeciwnika ta nadal istnieje, a w plikach sprawdzilem ze gildia ma nadal tyle samo żyć.

**Comment by insertt** [comment]
Zaktualizuj FunnyGuilds do najnowszej wersji.
