### ISSUE TITLE
Błąd

### ISSUE THREAD

**Issue by Blox61** [FunnyGuilds/FunnyGuilds#1155]
Witam napotkał mnie taki oto problem:

```
[12:02:02] [Craft Scheduler Thread - 4/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 74
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 3/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 80
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 5/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 77
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 3/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 89
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 5/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 83
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 4/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 86
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 8/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 92
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 3/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 102
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 5/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 98
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 4/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 95
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 5/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 111
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 8/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 108
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:02:02] [Craft Scheduler Thread - 9/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 105
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-56f8471-3e3818b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by Blox61** [comment]
Po za tym, wciąż wysyła mi wiadomość że jest dostępna nowa wersja pluginu

**Comment by insertt** [comment]
Podeślij pełny log serwera gdy ten błąd wystąpił.

**Comment by Blox61** [comment]
http://www.mediafire.com/file/6uljhlo51zc5s3h/Logi_24.12.209_-_Blox61.log/file

**Comment by insertt** [comment]
Zaktualizuj FunnyGuilds do najnowszej wersji nightly dostępnej [tutaj](https://ci.insertt.dev/job/FunnyGuilds/job/master/).
