### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 2

### ISSUE THREAD

**Issue by Weediati** [FunnyGuilds/FunnyGuilds#1160]
logi z konsoli

```
[21:28:02 ERROR]: [FunnyGuilds]
[21:28:02 ERROR]: [FunnyGuilds] Could not load plugin configuration
[21:28:02 ERROR]: [FunnyGuilds]
[21:28:02 ERROR]: [FunnyGuilds] java.lang.ArrayIndexOutOfBoundsException: 2
[21:28:02 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.util.commons.bukkit.ItemUtils.parseItem(ItemUtils.java:97)
[21:28:02 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.loadItemStackList(PluginConfiguration.java:1199)
[21:28:02 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.load(PluginConfiguration.java:1278)
[21:28:02 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:107)
[21:28:02 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:313)
[21:28:02 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:753)
[21:28:02 ERROR]: [FunnyGuilds]        at org.bukkit.Bukkit.reload(Bukkit.java:525)
[21:28:02 ERROR]: [FunnyGuilds]        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[21:28:02 ERROR]: [FunnyGuilds]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:28:02 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
[21:28:02 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[21:28:02 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[21:28:02 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:28:02 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:28:02 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:28:02 ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:28:02 ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:28:02 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:28:02 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[21:28:02 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:28:02 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:28:02 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:28:02 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[21:28:02 ERROR]: [FunnyGuilds]
[21:28:02 ERROR]: [FunnyGuilds] Server Information:
[21:28:02 ERROR]: [FunnyGuilds]   FunnyGuilds: null
[21:28:02 ERROR]: [FunnyGuilds]   Bukkit: 1.12.2-R0.1-SNAPSHOT
[21:28:02 ERROR]: [FunnyGuilds]   Java: 1.8.0_141
[21:28:02 ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,5,main]`
```

konfig

```yml
# ~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~ #
#                                 #
#           FunnyGuilds           #
#      4.6.0-SNAPSHOT Tribute     #
#                                 #
# ~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~ #
# FunnyGuilds wspiera PlaceholderAPI, lista dodawanych placeholderow znajduje sie tutaj:
# https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-2/#funnyguilds
#  
# FunnyGuilds wspiera takze placeholdery w BungeeTabListPlus i MVdWPlaceholderAPI
# Placeholdery sa dokladnie takie same jak w przypadku PlaceholderAPI (bez znaku % oczywiscie)
#  
# Jezeli chcesz, aby dana wiadomosc byla pusta, zamiast wiadomosci umiesc: ''
#  
# Wyswietlana nazwa pluginu
plugin-name: "FunnyGuilds"
# Czy plugin ma dzialac w trybie debug (wysylanie dodatkowych wiadomosci w celu zdiagnozowania bledow itp.)
debug-mode: false
# Czy informacje o aktualizacji maja byc widoczne podczas wejscia na serwer
update-info: false
# Mozliwosc zakladania gildii (mozna zmienic takze za pomoca komendy /ga enabled)
guilds-enabled: true
# Czy tworzenie regionow gildii (i inne zwiazane z nimi rzeczy) maja byc wlaczone
# UWAGA - dobrze przemysl decyzje o wylaczeniu regionow!
# Gildie nie beda mialy w sobie zadnych informacji o regionach, a jesli regiony sa wlaczone - te informacje musza byc obecne
# Jesli regiony mialyby byc znowu wlaczone - bedzie trzeba wykasowac WSZYSTKIE dane pluginu
# Wylaczenie tej opcji nie powinno spowodowac zadnych bledow, jesli juz sa utworzone regiony gildii
regions-enabled: true
# Czy gracz po smierci ma sie pojawiac w bazie swojej gildii
# Dziala tylko jesli regiony sa wlaczone
respawn-in-base: true
# Maksymalna dlugosc nazwy gildii
name-length: 22
# Minimalna dlugosc nazwy gildii
name-min-length: 4
# Maksymalna dlugosc tagu gildii
tag-length: 5
# Minimalna dlugosc tagu gildii
tag-min-length: 2
# Zasada sprawdzania nazwy gildii przy jej tworzeniu
# Dostepne zasady:
# LOWERCASE - umozliwia uzycie tylko malych liter
# UPPERCASE - umozliwia uzycie tylko duzych liter
# DIGITS - umozliwia uzycie tylko cyfr
# LOWERCASE_DIGITS - umozliwia uzycie malych liter i cyfr
# UPPERCASE_DIGITS - umozliwia uzycie duzych liter i cyfr
# LETTERS - umozliwia uzycie malych i duzych liter
# LETTERS_DIGITS - umozliwia uzycie malych i duzych liter oraz cyrf
# LETTERS_DIGITS_UNDERSCORE - umozliwia uzycie malych i duzych liter, cyrf oraz podkreslnika
name-regex: "LETTERS"
# Zasada sprawdzania tagu gildii przy jej tworzeniu
# Mozliwe zasady sa takie same jak w przypadku name-regex
tag-regex: "LETTERS"
# Minimalna liczba graczy w gildii, aby zaliczala sie ona do rankingu
guild-min-members: 1
# Czy wiadomosci o braku potrzebnych przedmiotow maja zawierac elementy, na ktore mozna najechac
# Takie elementy pokazuja informacje o przedmiocie, np. jego typ, nazwe czy opis
# Funkcja jest obecnie troche niedopracowana i moze powodowac problemy na niektorych wersjach MC, np. 1.8.8
enable-item-component: false
# Przedmioty wymagane do zalozenia gildii
# Tylko wartosci ujete w <> sa wymagane, reszta (ujeta w []) jest opcjonalna
# Wzor: <ilosc> <przedmiot>:[metadata] [name:lore:enchant:eggtype:skullowner:armorcolor]
# Przyklad: "5 stone name:&bFunnyGuilds lore:&eJestem_najlepszym#&6pluginem!"
# Zamiast spacji wstawiaj podkreslnik: _
# Aby zrobic nowa linie lore wstaw hash: #
# Aby w lore uzyc znaku # wstaw {HASH}
# eggtype to typ jajka do spawnu moba, uzywane tylko gdy typem przedmiotu jest MONSTER_EGG
# skullowner to nick gracza, ktorego glowa jest tworzona, uzywane tylko gdy typem przedmiotu jest SKULL_ITEM
# armorcolor to kolor, w ktorym bedzie przedmiot, uzywane tylko gdy przedmiot jest czescia zbroi skorzanej
# Kolor musi byc podany w postaci: "R_G_B"
# UWAGA: Nazwy przedmiotow musza pasowac do nazw podanych tutaj: https://spigotdocs.okaeri.eu/select/org/bukkit/Material.html
# UWAGA: Typ jajka musi pasowac do typow entity podanych tutaj: https://spigotdocs.okaeri.eu/select/org/bukkit/entity/EntityType.html
items: 
- "64 MONSTER_EGG name:&5Weedowegg lore:&aJajko_uzywane_do#&aTworzenia_gildii enchant:unbreaking 10"
- "64 TNT"
- "64 DIAMOND"
- "64 CAKE"
- "64 BOOK"
- "64 GOLD_INGOT"
- "64 SAND"
- "64 ANVIL"
# Wymagana ilosc doswiadczenia do zalozenia gildii
required-experience: 0
# Wymagana ilosc pieniedzy do zalozenia gildii
# UWAGA: Aby ta opcja mogla dzialac, na serwerze musi byc plugin Vault oraz plugin dodajacy ekonomie
required-money: 0.0
# Przedmioty wymagane do zalozenia gildii dla osoby z uprawnieniem funnyguilds.vip.items
items-vip: 
- "32 MONSTER_EGG &5Weedowegg:&aJajko_uzywane_do#&aTworzenia_gildii:unbreaking10:1"
- "32 TNT"
- "32 DIAMOND"
- "32 CAKE"
- "64 BOOK"
- "32 GOLD_INGOT"
- "32 SAND"
- "32 ANVIL"
# Wymagana ilosc doswiadczenia do zalozenia gildii dla osoby z uprawnieniem funnyguilds.vip.items
required-experience-vip: 0
# Wymagana ilosc pieniedzy do zalozenia gildii dla osoby z uprawnieniem funnyguilds.vip.items
# UWAGA: Aby ta opcja mogla dzialac, na serwerze musi byc plugin Vault oraz plugin dodajacy ekonomie
required-money-vip: 0.0
# Czy opcja wymaganego rankingu do zalozenia gildi ma byc wlaczona?
rank-create-enable: true
# Minimalny ranking wymagany do zalozenia gildi
rank-create: 1300
# Minimalny ranking wymagany do zalozenia gildi dla osoby z uprawnieniem funnyguilds.vip.rank
rank-create-vip: 800
# Czy GUI z przedmiotami na gildie ma byc wspolne dla wszystkich?
# Jesli wlaczone - wszyscy gracze beda widzieli GUI stworzone w sekcji gui-items, a GUI z sekcji gui-items-vip bedzie ignorowane
use-common-gui: false
# GUI z przedmiotami na gildie dla osob bez uprawnienia funnyguilds.vip.items
# Jesli wlaczone jest use-common-gui - ponizsze GUI jest uzywane takze dla osob z uprawnieniem funnyguilds.vip.items
# Kazda linijka listy oznacza jeden slot, liczba slotow powinna byc wielokrotnoscia liczby 9 i nie powinna byc wieksza niz 54
# Aby uzyc przedmiotu stworzonego w jednym slocie w innym mozna uzyc {GUI-nr}, np. {GUI-1} wstawi ten sam przedmiot, ktory jest w pierwszym slocie
# Aby wstawic przedmiot na gildie nalezy uzyc {ITEM-nr}, np. {ITEM-1} wstawi pierwszy przedmiot na gildie
# Aby wstawic przedmiot na gildie z listy vip nalezy uzyc {VIPITEM-nr}
gui-items: 
- "1 stained_glass_pane name:&r"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "1 paper name:&b&lItemy_na_gildie"
- "{ITEM-1}"
- "{ITEM-2}"
- "{ITEM-3}"
- "{ITEM-4}"
- "{ITEM-5}"
- "{ITEM-6}"
- "{ITEM-7}"
- "{GUI-10}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{ITEM-8}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
# Nazwa GUI z przedmiotami na gildie dla osob bez uprawnienia funnyguilds.vip.items
# Nazwa moze zawierac max. 32 znaki (wliczajac w to kody kolorow)
gui-items-title: "&5&lPrzedmioty na gildie"
# GUI z przedmiotami na gildie dla osob z uprawnieniem funnyguilds.vip.items
# Zasada tworzenia GUI jest taka sama jak w przypadku sekcji gui-items
# Ponizsze GUI bedzie ignorowane jesli wlaczone jest use-common-gui
gui-items-vip: 
- "1 stained_glass_pane name:&r"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "1 paper name:&b&lItemy_na_gildie"
- "{VIPITEM-1}"
- "{VIPITEM-2}"
- "{VIPITEM-3}"
- "{VIPITEM-4}"
- "{VIPITEM-5}"
- "{VIPITEM-6}"
- "{VIPITEM-7}"
- "{GUI-10}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{VIPITEM-8}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
- "{GUI-1}"
```

Od dobrych 2 godzin proboje to naprwic i nie umiem pomocy;x

**EDIT** dałem logi i config w code ~Molka

**Comment by rrye** [comment]
Wrzuć konfiguracje na np. pastebin i daj tutaj link zamiast tego w issue.

**Comment by Weediati** [comment]
1sec

**Comment by Weediati** [comment]
https://pastebin.com/pZhGXtK5

**Comment by rrye** [comment]
`- "64 MONSTER_EGG name:&5Weedowegg lore:&aJajko_uzywane_do#&aTworzenia_gildii enchant:unbreaking 10"`
Patrząc na to, co jest napisane w komentarzach nad polem to nie jest to prawidłowy zapis.

**Comment by Weediati** [comment]
tzn ? co zle wpisalem ? moge prosic o objasnienie ?

**Comment by Weediati** [comment]
probowalem to roznie robic

- "64 MONSTER_EGG name:&5Weedowegg lore:&aJajko_uzywane_do#&aTworzenia_gildii enchant:unbreaking 10 eggtype:minecraft_spawnegg_spawn"

tez nie działało ;/

- "64 MONSTER_EGG name:&5Weedowegg lore:&aJajko_uzywane_do#&aTworzenia_gildii enchant:unbreaking_10"
Tak samo ;/ malo pomyslow ;/

**Comment by Weediati** [comment]
> `- "64 MONSTER_EGG name:&5Weedowegg lore:&aJajko_uzywane_do#&aTworzenia_gildii enchant:unbreaking 10"`
> Patrząc na to, co jest napisane w komentarzach nad polem to nie jest to prawidłowy zapis.

probowalem to roznie robic

"64 MONSTER_EGG name:&5Weedowegg lore:&aJajko_uzywane_do#&aTworzenia_gildii enchant:unbreaking 10 eggtype:minecraft_spawnegg_spawn"
tez nie działało ;/

"64 MONSTER_EGG name:&5Weedowegg lore:&aJajko_uzywane_do#&aTworzenia_gildii enchant:unbreaking_10"
Tak samo ;/ malo pomyslow ;/

**Comment by insertt** [comment]
`- "64 MONSTER_EGG name:&5Weedowegg lore:&aJajko_uzywane_do#&aTworzenia_gildii enchant:unbreaking:10"
`
