### ISSUE TITLE
Problem z FG

### ISSUE THREAD

**Issue by HeavyStoner** [FunnyGuilds/FunnyGuilds#1162]
```
[01:35:48] [Craft Scheduler Thread - 0/WARN]: Exception in thread "Craft Scheduler Thread - 0"
[01:35:48] [Craft Scheduler Thread - 0/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 89
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 4 more
```

**EDIT** dodałem code ~Molka

**Comment by TheMolkaPL** [comment]
Wygląda na duplikat #1155

**Comment by insertt** [comment]
Zaktualizuj FunnyGuilds do najnowszej wersji nightly dostępnej [tutaj](https://ci.insertt.dev/job/FunnyGuilds/job/master/).
