### ISSUE TITLE
[FunnyGuilds] [Parser] > Unknown enchant: unbreaking

### ISSUE THREAD

**Issue by Weediati** [FunnyGuilds/FunnyGuilds#1165]
Logi z konsoli nr1:
`[17:37:36 WARN]: [FunnyGuilds] [Parser] > Unknown enchant: unbreaking
[17:37:36 ERROR]: [FunnyGuilds]
[17:37:36 ERROR]: [FunnyGuilds] Could not load plugin configuration
[17:37:36 ERROR]: [FunnyGuilds]
[17:37:36 ERROR]: [FunnyGuilds] java.lang.IllegalArgumentException: Enchantment cannot be null
[17:37:36 ERROR]: [FunnyGuilds]        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[17:37:36 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaItem.addEnchant(CraftMetaItem.java:710)
[17:37:36 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaSpawnEgg.addEnchant(CraftMetaSpawnEgg.java:1)
[17:37:36 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.util.commons.bukkit.ItemBuilder.addEnchant(ItemBuilder.java:67)
[17:37:36 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.util.commons.bukkit.ItemUtils.parseItem(ItemUtils.java:108)
[17:37:36 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.loadItemStackList(PluginConfiguration.java:1199)
[17:37:36 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.load(PluginConfiguration.java:1278)
[17:37:36 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:107)
[17:37:36 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:313)
[17:37:36 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:753)
[17:37:36 ERROR]: [FunnyGuilds]        at org.bukkit.Bukkit.reload(Bukkit.java:525)
[17:37:36 ERROR]: [FunnyGuilds]        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[17:37:36 ERROR]: [FunnyGuilds]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:37:36 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
[17:37:36 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[17:37:36 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[17:37:36 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:37:36 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:37:36 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:37:36 ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:37:36 ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:37:36 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[17:37:36 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[17:37:36 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[17:37:36 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[17:37:36 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[17:37:36 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[17:37:36 ERROR]: [FunnyGuilds]
[17:37:36 ERROR]: [FunnyGuilds] Server Information:
[17:37:36 ERROR]: [FunnyGuilds]   FunnyGuilds: null
[17:37:36 ERROR]: [FunnyGuilds]   Bukkit: 1.12.2-R0.1-SNAPSHOT
[17:37:36 ERROR]: [FunnyGuilds]   Java: 1.8.0_141
[17:37:36 ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,5,main]`

 Logi z konsoli nr2:
`[17:40:07 ERROR]: [FunnyGuilds]
[17:40:07 ERROR]: [FunnyGuilds] Could not load plugin configuration
[17:40:07 ERROR]: [FunnyGuilds]
[17:40:07 ERROR]: [FunnyGuilds] java.lang.ArrayIndexOutOfBoundsException: 1
[17:40:07 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.util.commons.bukkit.ItemUtils.parseItem(ItemUtils.java:93)
[17:40:07 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.loadItemStackList(PluginConfiguration.java:1199)
[17:40:07 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.load(PluginConfiguration.java:1278)
[17:40:07 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:107)
[17:40:07 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:313)
[17:40:07 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:753)
[17:40:07 ERROR]: [FunnyGuilds]        at org.bukkit.Bukkit.reload(Bukkit.java:525)
[17:40:07 ERROR]: [FunnyGuilds]        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[17:40:07 ERROR]: [FunnyGuilds]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:40:07 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
[17:40:07 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[17:40:07 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[17:40:07 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:40:07 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:40:07 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:40:07 ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:40:07 ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:40:07 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[17:40:07 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[17:40:07 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[17:40:07 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[17:40:07 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[17:40:07 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[17:40:07 ERROR]: [FunnyGuilds]
[17:40:07 ERROR]: [FunnyGuilds] Server Information:
[17:40:07 ERROR]: [FunnyGuilds]   FunnyGuilds: null
[17:40:07 ERROR]: [FunnyGuilds]   Bukkit: 1.12.2-R0.1-SNAPSHOT
[17:40:07 ERROR]: [FunnyGuilds]   Java: 1.8.0_141
[17:40:07 ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,5,main]`

pastebin config nr1: https://pastebin.com/7AypPiKM
pastebin config nr2: https://pastebin.com/RdGKisyw

**Comment by rrye** [comment]
`enchant:unbreaking: 5"`
Usuń spację i sprawdź.

**Comment by Weediati** [comment]
bez spacnij tez nie dziala ;/

**Comment by Weediati** [comment]
[17:58:14 WARN]: [FunnyGuilds] [Parser] > Unknown enchant: unbreaking
[17:58:14 ERROR]: [FunnyGuilds]
[17:58:14 ERROR]: [FunnyGuilds] Could not load plugin configuration
[17:58:14 ERROR]: [FunnyGuilds]
[17:58:14 ERROR]: [FunnyGuilds] java.lang.IllegalArgumentException: Enchantment cannot be null
[17:58:14 ERROR]: [FunnyGuilds]        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[17:58:14 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaItem.addEnchant(CraftMetaItem.java:710)
[17:58:14 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaSpawnEgg.addEnchant(CraftMetaSpawnEgg.java:1)
[17:58:14 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.util.commons.bukkit.ItemBuilder.addEnchant(ItemBuilder.java:67)
[17:58:14 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.util.commons.bukkit.ItemUtils.parseItem(ItemUtils.java:108)
[17:58:14 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.loadItemStackList(PluginConfiguration.java:1199)
[17:58:14 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.load(PluginConfiguration.java:1278)
[17:58:14 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:107)
[17:58:14 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:313)
[17:58:14 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:753)
[17:58:14 ERROR]: [FunnyGuilds]        at org.bukkit.Bukkit.reload(Bukkit.java:525)
[17:58:14 ERROR]: [FunnyGuilds]        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[17:58:14 ERROR]: [FunnyGuilds]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:58:14 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
[17:58:14 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[17:58:14 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[17:58:14 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:58:14 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:58:14 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:58:14 ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:58:14 ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:58:14 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[17:58:14 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[17:58:14 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[17:58:14 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[17:58:14 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[17:58:14 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[17:58:14 ERROR]: [FunnyGuilds]
[17:58:14 ERROR]: [FunnyGuilds] Server Information:
[17:58:14 ERROR]: [FunnyGuilds]   FunnyGuilds: null
[17:58:14 ERROR]: [FunnyGuilds]   Bukkit: 1.12.2-R0.1-SNAPSHOT
[17:58:14 ERROR]: [FunnyGuilds]   Java: 1.8.0_141
[17:58:14 ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,5,main]

paste bin config: https://pastebin.com/v3AVZ40R

**Comment by Weediati** [comment]
> `enchant:unbreaking: 5`
> Usuń spację i sprawdź.

z spacja bez spacji trez nie dziala ;/

**Comment by Weediati** [comment]
Logi z konsoli: [FunnyGuilds]
[18:00:39 ERROR]: [FunnyGuilds] Could not load plugin configuration
[18:00:39 ERROR]: [FunnyGuilds]
[18:00:39 ERROR]: [FunnyGuilds] java.lang.ArrayIndexOutOfBoundsException: 2
[18:00:39 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.util.commons.bukkit.ItemUtils.parseItem(ItemUtils.java:97)
[18:00:39 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.loadItemStackList(PluginConfiguration.java:1199)
[18:00:39 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.load(PluginConfiguration.java:1278)
[18:00:39 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:107)
[18:00:39 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:313)
[18:00:39 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:753)
[18:00:39 ERROR]: [FunnyGuilds]        at org.bukkit.Bukkit.reload(Bukkit.java:525)
[18:00:39 ERROR]: [FunnyGuilds]        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[18:00:39 ERROR]: [FunnyGuilds]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:00:39 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
[18:00:39 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[18:00:39 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[18:00:39 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:00:39 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:00:39 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[18:00:39 ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:00:39 ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:00:39 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[18:00:39 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[18:00:39 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[18:00:39 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[18:00:39 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[18:00:39 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[18:00:39 ERROR]: [FunnyGuilds]
[18:00:39 ERROR]: [FunnyGuilds] Server Information:
[18:00:39 ERROR]: [FunnyGuilds]   FunnyGuilds: null
[18:00:39 ERROR]: [FunnyGuilds]   Bukkit: 1.12.2-R0.1-SNAPSHOT
[18:00:39 ERROR]: [FunnyGuilds]   Java: 1.8.0_141
[18:00:39 ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,5,main]

config: https://pastebin.com/vgPBVZ2r

**Comment by Weediati** [comment]
[18:09:45 WARN]: [FunnyGuilds] [Parser] > Unknown enchant: unbreaking
[18:09:45 ERROR]: [FunnyGuilds]
[18:09:45 ERROR]: [FunnyGuilds] Could not load plugin configuration
[18:09:45 ERROR]: [FunnyGuilds]
[18:09:45 ERROR]: [FunnyGuilds] java.lang.IllegalArgumentException: Enchantment cannot be null
[18:09:45 ERROR]: [FunnyGuilds]        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[18:09:45 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaItem.addEnchant(CraftMetaItem.java:710)
[18:09:45 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaSpawnEgg.addEnchant(CraftMetaSpawnEgg.java:1)
[18:09:45 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.util.commons.bukkit.ItemBuilder.addEnchant(ItemBuilder.java:67)
[18:09:45 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.util.commons.bukkit.ItemUtils.parseItem(ItemUtils.java:108)
[18:09:45 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.loadItemStackList(PluginConfiguration.java:1199)
[18:09:45 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.load(PluginConfiguration.java:1278)
[18:09:45 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:107)
[18:09:45 ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:313)
[18:09:45 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205)
[18:09:45 ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[18:09:45 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[18:09:45 ERROR]: [FunnyGuilds]
[18:09:45 ERROR]: [FunnyGuilds] Server Information:
[18:09:45 ERROR]: [FunnyGuilds]   FunnyGuilds: null
[18:09:45 ERROR]: [FunnyGuilds]   Bukkit: 1.12.2-R0.1-SNAPSHOT
[18:09:45 ERROR]: [FunnyGuilds]   Java: 1.8.0_141
[18:09:45 ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,5,main]



teraz takie bledy dostaje a nic nie zmienilem ;/

**Comment by rrye** [comment]
Zapomniałem, enchant `unbreaking` nie nazywa się tak samo w silniku.
Użyj nazwy `durability` i powinno zadziałać.

**Comment by Weediati** [comment]
juz patrze

**Comment by Weediati** [comment]
Dziala dzęki za pomoc rrye!
