### ISSUE TITLE
Błąd czy tam ostrzeżenie - Gildia, ranking, podbijanie

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1198]
Pomijając to że mimo że mam permisje żeby nie liczyć się do rankingu to dalej się liczę to:
Gdy usunąłem gildię przez console zostało dalej serce gildii które można uderzyć i wtedy pokazuje się błąd ale serce ciągle nie znika. W między czasie wpisałem komendę żeby upewnić się że używam nowej wersji fg.
```
[20:54:37 INFO]: Pomyslnie usunieto gildie!
[20:54:37 INFO]: CONSOLE rozwiazal gildie KRSS!
```
```
[20:55:21 WARN]: java.lang.NullPointerException
[20:55:21 WARN]:        at net.dzikoysk.funnyguilds.system.security.SecuritySystem.checkPlayer(SecuritySystem.java:70)
[20:55:21 WARN]:        at net.dzikoysk.funnyguilds.system.security.SecuritySystem.checkPlayer(SecuritySystem.java:33)
[20:55:21 WARN]:        at net.dzikoysk.funnyguilds.system.war.WarListener.call(WarListener.java:72)
[20:55:21 WARN]:        at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:58)
[20:55:21 WARN]:        at net.dzikoysk.funnyguilds.concurrency.requests.WarUseRequest.execute(WarUseRequest.java:19)
[20:55:21 WARN]:        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)
[20:55:21 WARN]:        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)
[20:55:21 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:55:21 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[20:55:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:55:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:55:21 WARN]:        at java.lang.Thread.run(Unknown Source)
>fg version
[20:56:11 INFO]: FunnyGuilds 4.6.0-SNAPSHOT Tribute-951d8e0 by FunnyGuilds Team
[21:00:17 WARN]: java.lang.NullPointerException
[21:00:17 WARN]:        at net.dzikoysk.funnyguilds.system.security.SecuritySystem.checkPlayer(SecuritySystem.java:70)
[21:00:17 WARN]:        at net.dzikoysk.funnyguilds.system.security.SecuritySystem.checkPlayer(SecuritySystem.java:33)
[21:00:17 WARN]:        at net.dzikoysk.funnyguilds.system.war.WarListener.call(WarListener.java:72)
[21:00:17 WARN]:        at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:58)
[21:00:17 WARN]:        at net.dzikoysk.funnyguilds.concurrency.requests.WarUseRequest.execute(WarUseRequest.java:19)
[21:00:17 WARN]:        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)
[21:00:17 WARN]:        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)
[21:00:17 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:00:17 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[21:00:17 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:00:17 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:00:17 WARN]:        at java.lang.Thread.run(Unknown Source)
```
Błąd wyskakuje zawsze kiedy chce uderzyć serce usuniętej już gildii.

**Comment by radek203** [comment]
@dzikoysk Wracając do tego, dziś chciałem założyć gildię. Przy zwykłych ustawianiach bez schematu czy innego serca gildii i wyskoczyło:
[11:37:11 INFO]: radek203 issued server command: /zaloz KRSS KoxyRefySameStrefy
```
[11:37:11 WARN]: java.lang.IllegalArgumentException: argument type mismatch
[11:37:11 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:37:11 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[11:37:11 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[11:37:11 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[11:37:11 WARN]:        at net.dzikoysk.funnyguilds.util.nms.GuildEntityHelper.createSpawnGuildHeartPacket(GuildEntityHelper.java:87)
[11:37:11 WARN]:        at net.dzikoysk.funnyguilds.util.nms.GuildEntityHelper.spawnGuildHeart(GuildEntityHelper.java:123)
[11:37:11 WARN]:        at net.dzikoysk.funnyguilds.util.nms.GuildEntityHelper.spawnGuildHeart(GuildEntityHelper.java:103)
[11:37:11 WARN]:        at net.dzikoysk.funnyguilds.basic.guild.GuildUtils.spawnHeart(GuildUtils.java:95)
[11:37:11 WARN]:        at net.dzikoysk.funnyguilds.command.ExcCreate.execute(ExcCreate.java:269)
[11:37:11 WARN]:        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:126)
[11:37:11 WARN]:        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:164)
[11:37:11 WARN]:        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:22)
[11:37:11 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:37:11 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[11:37:11 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399)
[11:37:11 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234)
[11:37:11 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:37:11 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:37:11 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[11:37:11 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:37:11 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[11:37:11 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[11:37:11 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[11:37:11 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[11:37:11 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[11:37:11 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[11:37:11 WARN]:        at java.lang.Thread.run(Unknown Source)
[11:37:11 INFO]: radek203 zalozyl gildie o nazwie KoxyRefySameStrefy i tagu KRSS!
[11:37:13 WARN]: java.lang.IllegalArgumentException: argument type mismatch
[11:37:13 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:37:13 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[11:37:13 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[11:37:13 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[11:37:13 WARN]:        at net.dzikoysk.funnyguilds.util.nms.GuildEntityHelper.createSpawnGuildHeartPacket(GuildEntityHelper.java:87)
[11:37:13 WARN]:        at net.dzikoysk.funnyguilds.util.nms.GuildEntityHelper.spawnGuildHeart(GuildEntityHelper.java:123)
[11:37:13 WARN]:        at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$null$1(PlayerMove.java:124)
[11:37:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[11:37:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:37:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[11:37:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[11:37:13 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by insertt** [comment]
Te błędy wyglądają na przełączanie opcji `regions-enabled` po utworzeniu jakiejś gildii, a następnie testowanie na niej tychże rzeczy. Czy konfiguracja przed i po utworzeniu gildii różniła się gdy te błędy wystąpiły?

**Comment by radek203** [comment]
Tej opcji nie ruszałem, ale testowałem wklejanie schematu, ale tak jak mówię jeden błąd wystąpił bez zmiany tego - te usunięcie gildii przez konsole

**Comment by dzikoysk** [comment]
Czy błąd występuje w najnowszym nightly?
