### ISSUE TITLE
Błąd przy zakładaniu gildii - nie da się założyć

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1219]
```
[11:56:15] [Server thread/INFO]: radek203 issued server command: /zaloz KRSS KoxyRefySameStrefy
[11:56:15] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'zaloz KRSS KoxyRefySameStrefy' in net.dzikoysk.funnyguilds.command.util.Performer(zaloz)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[server.jar:git-Spigot-8faa8b4-7f61a25]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:713) ~[server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[?:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[?:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [server.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [server.jar:git-Spigot-8faa8b4-7f61a25]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at net.dzikoysk.funnyguilds.element.schematic.SchematicHelper.pasteSchematic(SchematicHelper.java:26) ~[?:?]
        at net.dzikoysk.funnyguilds.command.ExcCreate.execute(ExcCreate.java:248) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:126) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:164) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:22) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-Spigot-8faa8b4-7f61a25]
        ... 16 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[server.jar:git-Spigot-8faa8b4-7f61a25]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[server.jar:git-Spigot-8faa8b4-7f61a25]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at net.dzikoysk.funnyguilds.element.schematic.SchematicHelper.pasteSchematic(SchematicHelper.java:26) ~[?:?]
        at net.dzikoysk.funnyguilds.command.ExcCreate.execute(ExcCreate.java:248) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:126) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:164) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:22) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-Spigot-8faa8b4-7f61a25]
        ... 16 more
```
Z tego co widzę jest to błąd przy wklejaniu schematu - w sensie te serce gildii jak ktoś ustawił
Spigot: 1.15.2
WorldEdit: worldedit-bukkit-7.2.0-SNAPSHOT-dist
FG: FunnyGuilds 4.6.0 Tribute-242c3e9 by FunnyGuilds Team

**Comment by Szymusek07** [comment]
Pokaz schemat serca gildii jaki to blok.

**Comment by radek203** [comment]
> Pokaz schemat serca gildii jaki to blok.

Nic do tego blok samego serca nie ma, to jest zupełnie co innego. Z tego co sie domyslam to tutaj brakuje wsparcie dla WorldEdit 7+ i tyle.

**Comment by dzikoysk** [comment]
#1218
