### ISSUE TITLE
Błąd lagujący gre

### ISSUE THREAD

**Issue by 0VERR** [FunnyGuilds/FunnyGuilds#1223]
Co jakiś czas w konsoli występuje taki błąd, po czym ścina gre na około 10 sekund, wersja: 1.15.2

```[11:54:44] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.EntityDamage.onDamage(EntityDamage.java:48) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor262.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-87]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:561) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:232) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:994) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:881) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:837) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1026) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1691) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity0(EntityHuman.java:878) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1049) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:801) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:746) ~[patched_1.15.2.jar:git-Paper-87]
	at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:143) ~[?:?]
	at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1113) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1698) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2049) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-87]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by 0VERR** [comment]
Co jakiś czas w konsoli występuje taki błąd, po czym ścina gre na około 10 sekund, wersja: 1.15.2


11:54:44] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.listener.EntityDamage.onDamage(EntityDamage.java:48) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor262.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-87]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:561) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:232) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:994) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:881) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:837) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1026) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1691) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity0(EntityHuman.java:878) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1049) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:801) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:746) ~[patched_1.15.2.jar:git-Paper-87]
	at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:143) ~[?:?]
	at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1113) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1698) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2049) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-87]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by insertt** [comment]
Na jakiej wersji FunnyGuilds występuje ten problem?
