### ISSUE TITLE
Problem z TAB'em, błędy przy wczytywaniu 

### ISSUE THREAD

**Issue by maxiebeast** [FunnyGuilds/FunnyGuilds#1238]
```
[13:30:12 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -89201000 and range PING found!
at net.dzikoysk.funnyguilds.util.IntegerRange.inRange(IntegerRange.java:38) ~[?:?]
at net.dzikoysk.funnyguilds.element.tablist.variable.DefaultTablistVariables.lambda$createFunnyVariables$16(DefaultTablistVariables.java:108) ~[?:?]
at net.dzikoysk.funnyguilds.element.tablist.variable.DefaultTablistVariables$$Lambda$206/1079844106.apply(Unknown Source) ~[?:?]
at net.dzikoysk.funnyguilds.element.tablist.variable.impl.SimpleTablistVariable.get(SimpleTablistVariable.java:29) ~[?:?]
at net.dzikoysk.funnyguilds.element.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:29) ~[?:?]
at net.dzikoysk.funnyguilds.element.tablist.AbstractTablist.putVars(AbstractTablist.java:174) ~[?:?]
at net.dzikoysk.funnyguilds.element.tablist.AbstractTablist.putVarsPrepareCells(AbstractTablist.java:156) ~[?:?]
at net.dzikoysk.funnyguilds.element.tablist.impl.v1_10_R1.TablistImpl.send(TablistImpl.java:94) ~[?:?]
at net.dzikoysk.funnyguilds.element.tablist.TablistBroadcastHandler.run(TablistBroadcastHandler.java:24) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
[13:30:13 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:14 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:15 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:16 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:17 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:18 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:18 INFO]: [AuthMe] matiks12300 logged in!
[13:30:18 WARN]: [AuthMe] Could not download GeoLiteAPI database [UnknownHostException]: geolite.maxmind.com
[13:30:19 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -66900681 and range PING found!
[13:30:20 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:21 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:22 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:23 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:24 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:25 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:26 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:27 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -50175506 and range PING found!
[13:30:28 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:29 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -37631625 and range PING found!
[13:30:30 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:31 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -28223715 and range PING found!
[13:30:32 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:33 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -21167779 and range PING found!
[13:30:34 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:35 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:36 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -15875757 and range PING found!
[13:30:37 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -11906814 and range PING found!
[13:30:38 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:39 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:40 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -8930106 and range PING found!
[13:30:41 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:42 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -6697575 and range PING found!
[13:30:43 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:44 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -5023177 and range PING found!
[13:30:45 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:46 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -3767379 and range PING found!
[13:30:47 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:48 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -2825530 and range PING found!
[13:30:49 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:50 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -2119143 and range PING found!
[13:30:51 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:52 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -1589353 and range PING found!
[13:30:53 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:54 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -1192010 and range PING found!
[13:30:55 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:56 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -894003 and range PING found!
[13:30:56 INFO]: [Bocik] Administracja nie odpowiada za to kogo dodajesz do gildii!
[13:30:57 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:30:58 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -670498 and range PING found!
[13:30:59 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:00 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -502851 and range PING found!
[13:31:01 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:02 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -377134 and range PING found!
[13:31:03 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:04 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -282846 and range PING found!
[13:31:05 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:06 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -212130 and range PING found!
[13:31:07 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:08 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -159093 and range PING found!
[13:31:09 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:10 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -119315 and range PING found!
[13:31:11 INFO]: zendira585 issued server command: /tpa Janek657
[13:31:11 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:12 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -89482 and range PING found!
[13:31:13 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:14 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -67107 and range PING found!
[13:31:15 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:16 INFO]: Janek6574 issued server command: /tpaccept
[13:31:16 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -50326 and range PING found!
[13:31:17 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:18 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -37740 and range PING found!
[13:31:19 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:20 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:21 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -28301 and range PING found!
[13:31:22 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:23 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -21221 and range PING found!
[13:31:24 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:25 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -15911 and range PING found!
[13:31:26 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:27 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -11929 and range PING found!
[13:31:28 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:29 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -8943 and range PING found!
[13:31:30 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:31 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -6700 and range PING found!
[13:31:32 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:33 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -5021 and range PING found!
[13:31:34 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:35 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -3761 and range PING found!
[13:31:36 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:37 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -2816 and range PING found!
[13:31:38 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:39 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -2047 and range PING found!
[13:31:40 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:41 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -1530 and range PING found!
[13:31:42 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:43 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -1143 and range PING found!
[13:31:44 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:45 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -852 and range PING found!
[13:31:46 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:47 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -635 and range PING found!
[13:31:48 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:49 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -472 and range PING found!
[13:31:50 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:51 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -348 and range PING found!
[13:31:52 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:53 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -257 and range PING found!
[13:31:54 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:55 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -189 and range PING found!
[13:31:56 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:56 INFO]: [Bocik] Wszystkie informacje o serwerze znajdziesz pod: /informacje!
[13:31:57 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -137 and range PING found!
[13:31:58 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:31:59 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -94 and range PING found!
[13:32:00 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:32:01 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:32:02 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -66 and range PING found!
[13:32:03 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:32:04 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -45 and range PING found!
[13:32:05 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:32:06 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -29 and range PING found!
[13:32:07 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:32:08 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -18 and range PING found!
[13:32:09 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:32:10 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -9 and range PING found!
[13:32:11 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
[13:32:12 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -3 and range PING found!
[13:32:13 WARN]: [FunnyGuilds] Plugin Gildie v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 28
```

**Comment by rrye** [comment]
Podałeś złą wartość w polu odnośnie pingu na tab-liście. Pokaż konfigurację.

**Comment by insertt** [comment]
GH-1177
