### ISSUE TITLE
Błąd w konsoli

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1243]
```
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds] 
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds] An error occurred while handling concurrent request
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds] 
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds] java.lang.NullPointerException
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.element.Dummy.initialize(Dummy.java:68)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.element.Dummy.<init>(Dummy.java:18)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.basic.user.UserCache.getDummy(UserCache.java:158)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.element.DummyManager.updateScore(DummyManager.java:17)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.requests.dummy.DummyGlobalUpdateUserRequest.execute(DummyGlobalUpdateUserRequest.java:17)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds] 
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds] Server Information:
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]   FunnyGuilds: 4.6.0 Tribute-3b25983
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]   Bukkit: 1.12.2-R0.1-SNAPSHOT
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]   Java: 1.8.0_141
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]   Thread: Thread[pool-8-thread-1,5,main]
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds]   Loaded plugins: KMSprawdz 1.0, KMCraftingi 1.0, WorldEdit 6.1.9;caf0ad9, KMBorder 1.0, KMMotd 1.0, KMEfekty 1.0, KMPvP 1.0, KMNoSwear 1.0, KMTrade 1.0, KMKomendy 1.0, KMBans 1.0, KMEnder 1.0, ProtocolLib 4.5.1-SNAPSHOT-b447, KMSklep 1.0, AAC 4.3.9, SkinsRestorer 13.7.6-SNAPSHOT, KMAntyLogout 1.0, KMDrop 1.0, KMRTP 1.0, KMBlockClocks 1.0, PermissionsEx 1.23.4, KMCX 1.0, KMAdminWeryfikacja 1.0, KMPremiumCase 1.0, KMCore 1.0, KMEnchant 1.0, KMStoniarki 1.0, AuthMe 5.6.0-SNAPSHOT-b2385, WorldGuard 6.2.2-SNAPSHOT;8eeab68
[19:53:07] [pool-8-thread-1/ERROR]: [FunnyGuilds] 
```
Dostałem taki błąd, ale nie wiem przez co jest powodowany.

**Comment by radek203** [comment]
Podczas wyłączania serwera jeszcze takie 2 dostałem:
```
[11:11:31 WARN]: [com.zaxxer.hikari.pool.ProxyConnection] HikariPool-1 - Connection com.mysql.jdbc.JDBC4Connection@50a977b9 marked as broken because of SQLSTATE(08S01), ErrorCode(0)
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet successfully received from the server was 4 milliseconds ago.  The last packet sent successfully to the server was 4 milliseconds ago.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_141]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_141]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_141]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_141]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3559) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1283) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:783) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998) ~[patched_1.12.2.jar:git-Paper-1618]
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]
at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:72) ~[?:?]
at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55) ~[?:?]
at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:153) ~[?:?]
at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.net.SocketException: Socket closed
at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_141]
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_141]
at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_141]
at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_141]
at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469) ~[patched_1.12.2.jar:git-Paper-1618]
... 21 more
```
```
[11:11:31 WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0 Tribute-3b25983 generated an exception while executing task 26
java.lang.NullPointerException: null
at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:156) ~[?:?]
at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```
