### ISSUE TITLE
Przy założeniu gildii dostaje błąd

### ISSUE THREAD

**Issue by dj1sklero** [FunnyGuilds/FunnyGuilds#1247]
Witam!
Przy próbie założenie gildii dostaje błąd na chacie gry "An internal error occurred while attempting to perform this command" oraz błąd java:
```[16:46:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'zaloz sad asdasd' in net.dzikoysk.funnyguilds.command.util.Performer(zaloz)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[server.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[server.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [server.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [server.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-"8b18730"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [server.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
        at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at net.dzikoysk.funnyguilds.util.commons.spigot.ItemComponentUtils.getItemComponent(ItemComponentUtils.java:107) ~[?:?]
        at net.dzikoysk.funnyguilds.util.commons.spigot.ItemComponentUtils.translateComponentPlaceholder(ItemComponentUtils.java:76) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Executor.playerHasEnoughItems(Executor.java:38) ~[?:?]
        at net.dzikoysk.funnyguilds.command.ExcCreate.execute(ExcCreate.java:189) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:126) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:164) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:22) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[server.jar:git-PaperSpigot-"8b18730"]
        ... 14 more
```
Wersja serwera 1.8.8
Wersja FG to nightly #115 we wcześniejszej z 29 lutego ten sam błąd.

**Comment by dj1sklero** [comment]
Witam!

Czy coś już wiadomo w temacie?

**Comment by dzikoysk** [comment]
@dj1sklero Podaj listę itemów na gildię z configu (również te dla vipa)

**Comment by dj1sklero** [comment]
items: 
- "64 diamond"
- "64 emerald"
- "64 obsidian"
- "64 tnt"
- "64 bookshelf"
- "64 slimeball"
- "64 gold_block"
- "64 cactus"
- "64 anvil"

items-vip: 
- "32 diamond"
- "32 emerald"
- "32 obsidian"
- "32 tnt"
- "32 bookshelf"
- "32 slimeball"
- "32 gold_block"
- "32 cactus"
- "32 anvil"

**Comment by insertt** [comment]
Zaktualizuj Paperspigota do najnowszego release wersji 1.8.8

**Comment by dzikoysk** [comment]
Z tego co widzę, to nie ma materiału `slimeball` tylko `slime_ball`

**Comment by dj1sklero** [comment]
dzięki wielkie slime_ball był problemem
