### ISSUE TITLE
Error - Citizens?

### ISSUE THREAD

**Issue by xCraftRayX** [FunnyGuilds/FunnyGuilds#1257]
Po uruchomieniu serwera robi się spam co parę sekund takim błędem, chyba chodzi o citizens entity type Player:

```
[00:24:08 WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.6.0-SNAPSHOT Tribute-f68875e generated an exception while executing task 1745
java.lang.NullPointerException: null
        at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-236]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-236]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-236]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by dzikoysk** [comment]
Wgraj najnowszą wersję FG z nightly
