### ISSUE TITLE
"Błędy" podczas wyłączania serwera.

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1270]
```
[10:21:12 WARN]: HikariPool-1 - Connection com.mysql.jdbc.JDBC4Connection@7ab01338 marked as broken because of SQLSTATE(08003), ErrorCode(0)
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_141]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_141]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_141]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_141]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1213) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1200) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.mysql.jdbc.ConnectionImpl.clientPrepareStatement(ConnectionImpl.java:1447) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4242) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4169) ~[server.jar:git-PaperSpigot-"8b18730"]
at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:318) ~[?:?]
at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[?:?]
at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:66) ~[?:?]
at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:55) ~[?:?]
at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:153) ~[?:?]
at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [server.jar:git-PaperSpigot-"8b18730"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[10:21:12 WARN]: Exception in thread "Craft Scheduler Thread - 83"
[10:21:12 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.7.0 Tribute-98147ce generated an exception while executing task 26
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
at net.dzikoysk.funnyguilds.data.database.SQLDataModel.save(SQLDataModel.java:156)
at net.dzikoysk.funnyguilds.data.DataPersistenceHandler.lambda$startHandler$0(DataPersistenceHandler.java:24)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more
```
Przez to mój serwer wyłącza się bardzo długo.
PaperSpigot: 1.8.8
FunnyGuilds 4.7.0 Tribute-98147ce by FunnyGuilds Team

**Comment by radek203** [comment]
@insertt Zostanie to może naprawione? Wiem że błąd stary, ale dalej występuje.
Według mnie to tu nie jest zakończone zadanie zapisywania do MySQL i takie coś potem wywala.

**Comment by radek203** [comment]
Chyba zostało naprawione
