### ISSUE TITLE
Błąd z nieusuwaniem się gildii kiedy gildia wygasa.

### ISSUE THREAD

**Issue by radek203** [FunnyGuilds/FunnyGuilds#1282]
Zauważyłem że gdy gildia wygasa (Mam zapis MySQL) Gracz traci gildię. ale w gildii wskakuje do region: null, tak samo przy regionach center: null. Przez po podczas uruchamiania się serwera i wyłączania serwer wywala błędy i długo się wyłącza.
Przez co potem da się wpisać komendę do sprawdzenia statystyk gildii, która wywala błędy bo w teorii tej gildii już nie ma.
Może być to wina tego że mam niestandardowe serce gildii bądź schemat, ale mimo wszystko jak jest to w pluginie to powinno to działać.

Przez co chyba łączy się to z #1270

PaperSpigot: 1.8.8
FunnyGuilds version 4.7.0 Tribute-98147ce
```
[21:36:11] [Server thread/INFO]: FRiPciuch issued server command: /info smog
[21:36:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'info smog' in net.dzikoysk.funnyguilds.command.util.Performer(info)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[server.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [?:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [?:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-"8b18730"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.command.ExcInfo.execute(ExcInfo.java:72) ~[?:?]
	at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:126) ~[?:?]
	at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:164) ~[?:?]
	at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:22) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[server.jar:git-PaperSpigot-"8b18730"]
	... 14 more
```
Podczas uruchamiania:
```
[04:01:02] [Server thread/ERROR]: [FunnyGuilds] 
[04:01:02] [Server thread/ERROR]: [FunnyGuilds] Could not deserialize guild
[04:01:02] [Server thread/ERROR]: [FunnyGuilds] 
[04:01:02] [Server thread/ERROR]: [FunnyGuilds] java.lang.NullPointerException
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.basic.guild.Guild.setRegion(Guild.java:184)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.util.DeserializationUtils.deserializeGuild(DeserializationUtils.java:28)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.DatabaseGuild.deserialize(DatabaseGuild.java:101)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.lambda$load$2(SQLDataModel.java:91)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.Database.executeQuery(Database.java:57)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.load(SQLDataModel.java:88)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:152)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[04:01:02] [Server thread/ERROR]: [FunnyGuilds] 
```

**Comment by insertt** [comment]
Po przeanalizowaniu co dokładnie się dzieje przy wygasaniu gildii nie bardzo widzę w jaki sposób region gildyjny mógłby stać się nieprawidłowy poza nieudanym zapisem do bazy danych (lub niekompletnym), dlatego też wydaje mi się, że ta gildia to pozostałość gdy proces usuwania gildii z bazy danych się nie powiódł?

**Comment by radek203** [comment]
Normalnie wszystko pokazuje się jakby się usunęło. Według mnie tutaj próba zapisu podczas wyłączania serwera jest po zamknięciu połączenia z 1 błędu można było wyczytać. ("Przez co chyba łączy się to z #1270")

**Comment by radek203** [comment]
U siebie naprawiłem to przez zmienienie serca gildii znowu na kryształ (zamiast bedrocka) + w pluginie co nie wiem czy może to tego nie naprawiło
https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/data/database/DatabaseRegion.java
Linijka 70
        update.append("';");
na
        update.append("'");
