### ISSUE TITLE
FunnyGuilds nie chce sie przładować i występują takie błędy.

### ISSUE THREAD

**Issue by Industrial1107** [FunnyGuilds/FunnyGuilds#1296]
```[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.libs.org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:410)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.cfg.system.BaseTemplate.load(BaseTemplate.java:240)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.cfg.system.Template.load(Template.java:146)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.cfg.system.Template.load(Template.java:159)
[14:18:36 ERROR]: [FunnyGuilds]        at org.diorite.cfg.system.Template.load(Template.java:171)
[14:18:36 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.util.commons.ConfigHelper.loadConfig(ConfigHelper.java:38)
[14:18:36 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.FunnyGuilds.reloadPluginConfiguration(FunnyGuilds.java:314)
[14:18:36 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.requests.ReloadRequest.execute(ReloadRequest.java:25)
[14:18:36 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)
[14:18:36 ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)
[14:18:36 ERROR]: [FunnyGuilds]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:18:36 ERROR]: [FunnyGuilds]        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:18:36 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:18:36 ERROR]: [FunnyGuilds]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:18:36 ERROR]: [FunnyGuilds]        at java.lang.Thread.run(Thread.java:748)
[14:18:36 ERROR]: [FunnyGuilds] 
[14:18:36 ERROR]: [FunnyGuilds] Server Information:
[14:18:36 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.7.0 Tribute-8627f6a
[14:18:36 ERROR]: [FunnyGuilds]   Bukkit: 1.8.8-R0.1-SNAPSHOT
[14:18:36 ERROR]: [FunnyGuilds]   Java: 1.8.0_191
[14:18:36 ERROR]: [FunnyGuilds]   Thread: Thread[pool-4-thread-1,5,main]
[14:18:36 ERROR]: [FunnyGuilds]   Loaded plugins: WorldEdit 6.1;no_git_id, Schowek 1.0, BarAPI 3.5, PlaceholderAPI 2.10.6, ClearLag 3.1.6, Rzucane_tnt 1.0, StoneGenerator 1.5, WorldBorder 1.8.6, HolographicDisplays 2.1.10, SprawdzanieGraczy 1.0, RandomTeleport 2.5.1, ViaVersion 2.2.3, MH-API 1.0-SNAPSHOT, Vault 1.7.2-b107, Actionbar 1.2.4.8, Essentials 2.17.2.0, CrateReloaded 2.0.22, 1vs1 1.6.3 #213, TreasureChestReloaded 8.5.1, EssentialsProtect 2.17.2.0, CustomShop 2.0.2, EssentialsChat 2.17.2.0, TimeIsMoney 1.9.6.12, MH-Drop 1.0-SNAPSHOT, EssentialsSpawn 2.17.2.0, AuthMe 5.4.0-b1877, WorldGuard 6.1, Shopkeepers 2.2.1, CombatLogX 9.9.3.4
[14:18:36 ERROR]: [FunnyGuilds]
```

**Comment by insertt** [comment]
To nie jest pełny log błędu, podeślij także zawartość, która znajduje się ponad tym, co wysłałeś.
