### ISSUE TITLE
mysql lub coś takiego

### ISSUE THREAD

**Issue by mdkjd** [FunnyGuilds/FunnyGuilds#1334]
Silnik: 1.16.2 
Wymagania serwer spełnia.
Błąd: 
`[23:35:49] [Craft Scheduler Thread - 18/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.7.0 Tribute-b309560 generated an exception while executing task 3993
java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.deser.std.JdkDeserializers
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDefaultDeserializer(BasicDeserializerFactory.java:1852) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.findStdDeserializer(BeanDeserializerFactory.java:167) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:131) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[?:?]
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:2094) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:681) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:701) ~[?:?]
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:96) ~[?:?]
	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:74) ~[?:?]
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:461) ~[?:?]
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:412) ~[?:?]
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:363) ~[?:?]
	at org.kohsuke.github.Requester.fetch(Requester.java:74) ~[?:?]
	at org.kohsuke.github.GitHub.getOrganization(GitHub.java:505) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuildsVersion.lambda$isNewAvailable$0(FunnyGuildsVersion.java:43) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`

**Comment by mdkjd** [comment]
`[23:14:53] [Craft Scheduler Thread - 6/WARN]: Unable to load JDK7 types (java.nio.file.Path): no Java7 type support added
[23:14:53] [Craft Scheduler Thread - 6/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.7.0 Tribute-b309560 generated an exception while executing task 92
java.lang.VerifyError: Stack map does not match the one at exception handler 77
Exception Details:
 Location:
 com/fasterxml/jackson/databind/deser/std/StdDeserializer._parseDate(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/util/Date; @77: astore
 Reason:
 Type 'com/fasterxml/jackson/core/JsonParseException' (current frame, stack[0]) is not assignable to 'com/fasterxml/jackson/core/exc/StreamReadException' (stack map, stack[0])
 Current Frame:
 bci: @69
 flags: { }
 locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
 stack: { 'com/fasterxml/jackson/core/JsonParseException' }
 Stackmap Frame:
 bci: @77
 flags: { }
 locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
 stack: { 'com/fasterxml/jackson/core/exc/StreamReadException' }
 Bytecode:
 0x0000000: 2bb6 010e aa00 0000 0000 0082 0000 0003
 0x0000010: 0000 000b 0000 007b 0000 0082 0000 0082
 0x0000020: 0000 0034 0000 0041 0000 0082 0000 0082
 0x0000030: 0000 0082 0000 0072 2a2b b600 8cb6 0091
 0x0000040: 2cb6 01a7 b02b b601 4942 a700 233a 052c
 0x0000050: 2ab4 0024 2bb6 01ad 1301 af03 bd00 2db6
 0x0000060: 01b3 c000 ed3a 0619 06b6 0156 42bb 01b5
 0x0000070: 5921 b701 b8b0 2a2c b601 bcc0 01b5 b02a
 0x0000080: 2b2c b601 bfb0 2c2a b400 242b b600 cbc0
 0x0000090: 01b5 b0 
 Exception Handler Table:
 bci [69, 74] => handler: 77
 bci [69, 74] => handler: 77
 Stackmap Table:
 same_frame(@56)
 same_frame(@69)
 same_locals_1_stack_item_frame(@77,Object[#425])
 append_frame(@109,Long)
 chop_frame(@118,1)
 same_frame(@127)
 same_frame(@134)
	at com.fasterxml.jackson.databind.deser.std.JdkDeserializers.<clinit>(JdkDeserializers.java:26) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDefaultDeserializer(BasicDeserializerFactory.java:1852) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.findStdDeserializer(BeanDeserializerFactory.java:167) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:131) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[?:?]
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:2094) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:681) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:701) ~[?:?]
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:96) ~[?:?]
	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:74) ~[?:?]
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:461) ~[?:?]
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:412) ~[?:?]
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:363) ~[?:?]
	at org.kohsuke.github.Requester.fetch(Requester.java:74) ~[?:?]
	at org.kohsuke.github.GitHub.getOrganization(GitHub.java:505) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuildsVersion.lambda$isNewAvailable$0(FunnyGuildsVersion.java:43) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`
