### ISSUE TITLE
Blad podczas uruchamiania pluginu z włączoną opcją zapisu do MySQL.

### ISSUE THREAD

**Issue by Tejnox** [FunnyGuilds/FunnyGuilds#1337]
```
[17:36:51] [Server thread/ERROR]: Error occurred while enabling FunnyGuilds v4.7.0 Tribute (Is it up to date?)
java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/spi/ExtendedLogger;
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:39) ~[?:?]
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:30) ~[?:?]
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:54) ~[?:?]
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383) ~[?:?]
	at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.Database.<init>(Database.java:21) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.Database.getInstance(Database.java:46) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.SQLDataModel.load(SQLDataModel.java:36) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:147) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[mc.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [mc.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [mc.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [mc.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [mc.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [mc.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [mc.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [mc.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [mc.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [mc.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
[17:36:51] [Server thread/INFO]: [FunnyGuilds] Disabling FunnyGuilds v4.7.0 Tribute
[17:36:51] [Server thread/ERROR]: Error occurred while disabling FunnyGuilds v4.7.0 Tribute (Is it up to date?)
java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.FunnyGuilds.onDisable(FunnyGuilds.java:209) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[mc.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [mc.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [mc.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [mc.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [mc.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [mc.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [mc.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [mc.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [mc.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [mc.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [mc.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

**Comment by insertt** [comment]
Czy w najnowszej wersji nightly ([dostępnej tutaj](https://ci.insertt.dev/job/FunnyGuilds/job/master/)) również występuje ten błąd?

**Comment by Tejnox** [comment]
Problem dotyczy gdy samemu kompiluje kod. A gdy pobieram gotową wersję działa normalnie.

**Comment by insertt** [comment]
Czy kompilujesz projekt za pomocą Mavena?

**Comment by Tejnox** [comment]
Tak.

**Comment by Tejnox** [comment]
W takim razie w Czym może tkwić problem?

**Comment by insertt** [comment]
Wejdź na naszego discorda i opisz dokładnie jak kompilujesz plugin.
