### ISSUE TITLE
Problem - Updater

### ISSUE THREAD

**Issue by arki77** [FunnyGuilds/FunnyGuilds#1363]
Gdy gracz wejdzie/wyjdzie z serwera w konsoli wyskakuje ten blad:
```
[09:29:59 INFO]: [FunnyGuilds] [Updater] > Connection to the update server (https://funnyguilds.dzikoysk.net/latest.info) failed!
[09:29:59 INFO]: [FunnyGuilds] [Updater] > Reason: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
at net.dzikoysk.funnyguilds.util.commons.IOUtils.getContent(IOUtils.java:43)
at net.dzikoysk.funnyguilds.FunnyGuildsVersion.lambda$isNewAvailable$0(FunnyGuildsVersion.java:29)
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by dzikoysk** [comment]
Jakiej wersji Javy używasz?

**Comment by arki77** [comment]
11

**Comment by dzikoysk** [comment]
Dziwne, bo 11 z tego co pamiętam była już stable pod tym względem. Generalnie problem wynika bezpośrednio z ustawień JVM, na którym odpalasz serwer i ustawień protokołu TLS, a problem nie dotyczy FunnyGuilds. Sam uruchamiasz serwer czy korzystasz z jakiegoś hostingu?

**Comment by arki77** [comment]
Hosting, co ciekawe po zmianie na 8 problem ustał

**Comment by dzikoysk** [comment]
Tak jak mówiłem, to kwestia ustawień samej Javy, która jest na hostingu, dlatego zamykam.
