### ISSUE TITLE
Problem z zakładaniem gildii

### ISSUE THREAD

**Issue by MichixYT** [FunnyGuilds/FunnyGuilds#1502]
Witam, mam jeden problem z pluginem. Gdy chcę założyć gildię, wywala mi błędy w konsoli :/
```
[12:49:54 INFO]: MichixYT issued server command: /zaloz test test
[12:49:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'zaloz test test' in net.dzikoysk.funnycommands.commands.DynamicCommand(zaloz)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-PaperSpigot-4c7641d1]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[server.jar:git-PaperSpigot-4c7641d1]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1159) [server.jar:git-PaperSpigot-4c7641d1]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:974) [server.jar:git-PaperSpigot-4c7641d1]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:44) [server.jar:git-PaperSpigot-4c7641d1]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-PaperSpigot-4c7641d1]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-4c7641d1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-4c7641d1]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:769) [server.jar:git-PaperSpigot-4c7641d1]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:376) [server.jar:git-PaperSpigot-4c7641d1]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:708) [server.jar:git-PaperSpigot-4c7641d1]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:610) [server.jar:git-PaperSpigot-4c7641d1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: net.dzikoysk.funnycommands.FunnyCommandsException: Cannot invoke command
        at net.dzikoysk.funnycommands.commands.DynamicCommand.lambda$execute$2(DynamicCommand.java:118) ~[?:?]
        at org.panda_lang.utilities.commons.function.Option.orThrow(Option.java:131) ~[?:?]
        at net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:118) ~[?:?]
        at net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:84) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[server.jar:git-PaperSpigot-4c7641d1]
        ... 14 more
Caused by: java.lang.NoClassDefFoundError: org/bukkit/util/BoundingBox
        at net.dzikoysk.funnyguilds.command.user.CreateCommand.execute(CreateCommand.java:163) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.panda_lang.utilities.inject.MethodInjector.invoke(MethodInjector.java:45) ~[?:?]
        at net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:228) ~[?:?]
        at net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:112) ~[?:?]
        at net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:84) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[server.jar:git-PaperSpigot-4c7641d1]
        ... 14 more
```
Mój silnik to paperspigot 1.8.8 (najnowszy build)
Wersja FunnyGuilds 4.9.4 Tribute-149f7e8

**Comment by P3ridot** [comment]
Problem znany, wynika z tego że do najnowszego releasa dostał się kod który działa od 1.13 (czyli te BoundingBoxy który są w errorze). Musisz użyć  niższej wersji fg (np. 4.9.3) i poczekać aż wyjdzie nowa wersja fg która implementuje własna BoundingBoxy i naprawia ten błąd.
