### ISSUE TITLE
[Nightly] Błąd krytyczny przy starcie serwera - NoClassDefFoundError net/dzikoysk/funnyguilds/libs/com/google/gson/Gson

### ISSUE THREAD

**Issue by Rollczi** [FunnyGuilds/FunnyGuilds#1504]
Po użyciu nowej kompilacji Nightly.
Powiązane https://github.com/FunnyGuilds/FunnyGuilds/issues/1430
```
java.lang.NoClassDefFoundError: net/dzikoysk/funnyguilds/libs/com/google/gson/Gson
	at net.dzikoysk.funnyguilds.FunnyGuildsVersion.<clinit>(FunnyGuildsVersion.java:14) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:72) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323) ~[server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[server.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.dzikoysk.funnyguilds.libs.com.google.gson.Gson
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[server.jar:git-Paper-1618]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[server.jar:git-Paper-1618]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 6 more
	```

**Comment by insertt** [comment]
https://github.com/FunnyGuilds/FunnyGuilds/commit/758f2a30dd431d4a14df22433f685f8e9ccddf0b

**Comment by dzikoysk** [comment]
😳👉👈
