### ISSUE TITLE
/ga nazwa - NullPointerException po restarcie serwera

### ISSUE THREAD

**Issue by barpec12** [FunnyGuilds/FunnyGuilds#1513]
Używam FunnyGuilds 4.9.4 i bazy danych MySQL do przechowywania danych.
Po zmianie nazwy z wykorzystaniem komendy "/ga nazwa" region gildii zostaje usunięty z bazy danych. Skutkuje to niemożliwością załadowania gildii po restarcie serwera. Oprócz tego, z tego co zauważyłem, to nazwa gildii w rekordach graczy również nie jest aktualizowana.

**Comment by insertt** [comment]
Wrzuć log serwera z wyżej wymienionym błędem.

**Comment by dzikoysk** [comment]
Nazwa gildii w rekordach graczy została porzucona w najnowszym nightly, więc nie będzie aktualizowana.

**Comment by barpec12** [comment]
> 
> 
> Wrzuć log serwera z wyżej wymienionym błędem.

`[03:31:41] [Server thread/ERROR]: [FunnyGuilds] Could not deserialize guild (id: 038803df-49a0-49a8-a655-daa27197c07b, name: NazwaGildii)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds] 
[03:31:41] [Server thread/ERROR]: [FunnyGuilds] java.lang.NullPointerException
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.basic.guild.Guild.setRegion(Guild.java:200)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.util.DeserializationUtils.deserializeGuild(DeserializationUtils.java:28)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.DatabaseGuild.deserialize(DatabaseGuild.java:101)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.loadGuilds(SQLDataModel.java:140)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.data.database.SQLDataModel.load(SQLDataModel.java:89)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:126)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]        at java.base/java.lang.Thread.run(Thread.java:834)
[03:31:41] [Server thread/ERROR]: [FunnyGuilds] 
[03:31:41] [Server thread/ERROR]: [FunnyGuilds] Server Information:
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]   FunnyGuilds: 4.9.4 Tribute-149f7e8
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]   Bukkit: 1.16.5-R0.1-SNAPSHOT
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]   Java: 11.0.9.1
[03:31:41] [Server thread/ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,7,main]`

Po dodaniu rekordu do tablicy regions i modyfikacji rekordu gildii w clans, żeby wskazywał na dany region, gildia załadowała się po restarcie.

**Comment by dzikoysk** [comment]
Nie używasz najnowszego nightly, tam był mały błąd poprawiany z regionami i prawdopodobnie to wina tego:

* https://ci.insertt.dev/job/FunnyGuilds/job/master/lastSuccessfulBuild/artifact/target/FunnyGuilds%204.9.4%20(MC%201.8-1.16.5).jar

Tylko musisz pozbyć się tej gildii `NazwaGildii`, bo ona niestety już jest uszkodzona. Daj mi znać czy wszystko śmigens na niej i jak tak, to wydam oficjalnie 4.9.5.

**Comment by barpec12** [comment]
> 
> 
> Nie używasz najnowszego nightly, tam był mały błąd poprawiany z regionami i prawdopodobnie to wina tego:
> 
>     * https://ci.insertt.dev/job/FunnyGuilds/job/master/lastSuccessfulBuild/artifact/target/FunnyGuilds%204.9.4%20(MC%201.8-1.16.5).jar
> 
> 
> Tylko musisz pozbyć się tej gildii `NazwaGildii`, bo ona niestety już jest uszkodzona. Daj mi znać czy wszystko śmigens na niej i jak tak, to wydam oficjalnie 4.9.5.

Nie pozbywałem się tej gildii, dodałem tylko ręcznie brakujący rekord w bazie danych. Wrzucę tą aktualizację w nocy i przetestuję.

**Comment by dzikoysk** [comment]
W 4.9.5 problem powinien zostać rozwiązany, przecwinym wypadku daj znać.
