### ISSUE TITLE
NoClassDefFoundError przy użyciu niektórych komend

### ISSUE THREAD

**Issue by barpec12** [FunnyGuilds/FunnyGuilds#1516]
Przeglądając logi serwera postawionego na najnowszym nightly, znalazłem taki błąd
```
[16:15:13] [Server thread/ERROR]: Exception when JohnPlayer attempted to tab complete sojusz ABC
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'sojusz ABC' in net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand(sojusz)
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:250) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabCompleteCommand(CraftServer.java:1968) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabComplete(CraftServer.java:1940) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.craftbukkit.v1_16_R3.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.16.5.jar:git-Paper-576]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.5.jar:git-Paper-576]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.16.5.jar:git-Paper-576]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$7(PlayerConnection.java:785) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-576]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/dzikoysk/funnyguilds/libs/org/apache/commons/lang/StringUtils
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.CommandUtils.collectCompletions(CommandUtils.java:49) ~[?:?]
	at net.dzikoysk.funnyguilds.command.GuildsCompleter.apply(GuildsCompleter.java:18) ~[?:?]
	at net.dzikoysk.funnyguilds.command.GuildsCompleter.apply(GuildsCompleter.java:13) ~[?:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.CommandsLoader.lambda$mapCompletes$4(CommandsLoader.java:168) ~[?:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.tabComplete(DynamicCommand.java:202) ~[?:?]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.16.5.jar:git-Paper-576]
	... 18 more
```
Kod szuka ścieżki net/dzikoysk/funnyguilds/libs/org/apache/commons/lang/ , a w jar jest net\dzikoysk\funnyguilds\libs\org\apache\commons\lang3\

**Comment by barpec12** [comment]
No nie zostało to dobrze naprawione. Widzę, że nawet nie testowałeś jakkolwiek xd
```
[01:00:31] [Server thread/INFO]: [FunnyGuilds] Enabling Klany v4.9.5 Tribute-ca2ec38
[01:00:31] [Server thread/ERROR]: Error occurred while enabling Klany v4.9.5 Tribute-ca2ec38 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Class org.apache.logging.slf4j.Log4jLoggerFactory does not implement the requested interface net.dzikoysk.funnyguilds.libs.org.slf4j.ILoggerFactory
	at net.dzikoysk.funnyguilds.libs.org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363) ~[?:?]
	at net.dzikoysk.funnyguilds.libs.org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388) ~[?:?]
	at net.dzikoysk.funnyguilds.libs.com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.Database.<init>(Database.java:19) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.Database.getInstance(Database.java:44) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.Database.getConnection(Database.java:55) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.element.SQLNamedStatement.executeUpdate(SQLNamedStatement.java:35) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.SQLDataModel.createTableIfNotExists(SQLDataModel.java:212) ~[?:?]
	at net.dzikoysk.funnyguilds.data.database.SQLDataModel.load(SQLDataModel.java:84) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:142) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-576]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[01:00:31] [Server thread/INFO]: [FunnyGuilds] Disabling Klany v4.9.5 Tribute-ca2ec38
[01:00:31] [Server thread/ERROR]: Error occurred while disabling Klany v4.9.5 Tribute-ca2ec38 (Is it up to date?)
java.lang.NullPointerException: null
	at net.dzikoysk.funnyguilds.FunnyGuilds.onDisable(FunnyGuilds.java:228) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-576]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-576]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-576]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by dzikoysk** [comment]
To już de facto inny błąd. Sprawdź teraz nightly, zobaczymy czy czegoś jeszcze brakuje.

**Comment by barpec12** [comment]
Na pierwszy rzut oka działa. Dzięki wielkie za poprawienie o takiej porze. Dobrej nocy!
