### ISSUE TITLE
Problem z zakładaniem

### ISSUE THREAD

**Issue by TaczkaAww** [FunnyGuilds/FunnyGuilds#1521]
Najnowsza wersja pluginu
PaperSpigot 1.8.8

Caused by: java.lang.NoClassDefFoundError: org/bukkit/util/BoundingBox
        at net.dzikoysk.funnyguilds.command.user.CreateCommand.execute(CreateCommand.java:163) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.panda_lang.utilities.inject.MethodInjector.invoke(MethodInjector.java:45) ~[?:?]
        at net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:228) ~[?:?]
        at net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:112) ~[?:?]
        at net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:84) ~[?:?]

**Comment by P3ridot** [comment]
Zainstaluj najnowsze FunnyGuilds 4.9.6

**Comment by CDFN** [comment]
Nie używasz najnowszej wersji, na przyszłe reporty wrzucaj lepiej wersje, bo "najnowsza" nie jest zawsze najnowsza

**Comment by TaczkaAww** [comment]
dobra, nie zauwazyłem ze był update 11h temu.
