### ISSUE TITLE
InventoryMerchant#getOwner doesn't have protection against invalid owners

### ISSUE THREAD

**Issue by northpl93** [FunnyGuilds/FunnyGuilds#1582]
```
[14:14:14] [Server thread/ERROR]: Could not pass event InventoryClickEvent to FunnyGuilds v4.9.7 Tribute-1730267
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [?:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.ClassCastException: uniquecode.core.utils.VillagerUtil$1 cannot be cast to net.minecraft.server.v1_8_R3.EntityVillager
    at net.minecraft.server.v1_8_R3.InventoryMerchant.getOwner(InventoryMerchant.java:43) ~[sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.getHolder(CraftInventory.java:462) ~[sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    at net.dzikoysk.funnyguilds.element.gui.GuiActionHandler.onClick(GuiActionHandler.java:13) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[sv-gildie.jar:git-PaperSpigot-"4c7641d"]
    ... 16 more
```
It isn't a bug in FunnyGuilds, but we can add an additional check in GuiActionHandler#onClick to prevent this.

**Comment by northpl93** [comment]
Suggested implementation:
```java
    @EventHandler
    public void onClick(final InventoryClickEvent event) {
        Inventory inventory = event.getInventory();
        if (inventory.getType() != InventoryType.CHEST) {
            return;
        }

        InventoryHolder inventoryHolder = inventory.getHolder();
        if (!(inventoryHolder instanceof FunnyHolder)) {
            return;
        }

        FunnyHolder funnyHolder = (FunnyHolder) inventoryHolder;

        event.setCancelled(true);
        funnyHolder.handleClick(event);
    }
```
to be discussed later on discord.
