### ISSUE TITLE
Błąd FunnyGuilds

### ISSUE THREAD

**Issue by Jadov1ty** [FunnyGuilds/FunnyGuilds#1597]
Po odpaleniu serwera wyskakuje mi taki błąd:
```
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] Could not load plugin configuration
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] net.dzikoysk.funnyguilds.libs.eu.okaeri.configs.exception.OkaeriException: failed to initialize net.dzikoysk.funnyguilds.data.configs.PluginConfiguration [class net.dzikoysk.funnyguilds.libs.eu.okaeri.configs.validator.okaeri.OkaeriValidator]
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.libs.eu.okaeri.configs.ConfigManager.create(ConfigManager.java:53)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:102)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at java.lang.Thread.run(Thread.java:748)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] Caused by: java.time.format.DateTimeParseException: Text '1080' could not be parsed at index 2
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at java.time.LocalTime.parse(LocalTime.java:441)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.load(PluginConfiguration.java:1359)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.libs.eu.okaeri.configs.OkaeriConfig.load(OkaeriConfig.java:204)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.FunnyGuilds.lambda$onLoad$2(FunnyGuilds.java:106)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.libs.eu.okaeri.configs.ConfigManager.create(ConfigManager.java:50)
[10:39:54] [Server thread/ERROR]: [FunnyGuilds] 	... 6 more

[10:39:54] [Server thread/WARN]: [FunnyGuilds] The FunnyGuilds is going to shut down! Critical error has been encountered!
```

**Comment by insertt** [comment]
Wrzuć konfigurację FunnyGuilds.

**Comment by dzikoysk** [comment]
Brak odpowiedzi, zamykam.
