### ISSUE TITLE
Bug systemu konfiguracji. Niepoprawne pobieranie Stringa.

### ISSUE THREAD

**Issue by Rollczi** [FunnyGuilds/FunnyGuilds#1603]
Powiązane: https://github.com/FunnyGuilds/FunnyGuilds/issues/1602

Startowa konfiguracja:
> guild-tnt-protection-start-time: '22:00'
> guild-tnt-protection-end-time: 06:00

Po wpisaniu godziny powyżej 09:59
np. 10:00 bez ' system konfiguracji podaje złego Stringa do parsowania.

Błąd dla przykładu z 10:00
```
[17:19:05 ERROR]: [FunnyGuilds]
[17:19:05 ERROR]: [FunnyGuilds] Could not load plugin configuration
[17:19:05 ERROR]: [FunnyGuilds]
[17:19:05 ERROR]: [FunnyGuilds] net.dzikoysk.funnyguilds.libs.eu.okaeri.configs.exception.OkaeriException: failed to initialize net.dzikoysk.funnyguilds.data.configs.PluginConfiguration [class net.dzikoysk.funnyguilds.libs.eu.okaeri.configs.validator.okaeri.OkaeriValidator]
[17:19:05 ERROR]: [FunnyGuilds]         at net.dzikoysk.funnyguilds.libs.eu.okaeri.configs.ConfigManager.create(ConfigManager.java:53)
[17:19:05 ERROR]: [FunnyGuilds]         at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:104)
[17:19:05 ERROR]: [FunnyGuilds]         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393)
[17:19:05 ERROR]: [FunnyGuilds]         at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206)
[17:19:05 ERROR]: [FunnyGuilds]         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936)
[17:19:05 ERROR]: [FunnyGuilds]         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[17:19:05 ERROR]: [FunnyGuilds]         at java.lang.Thread.run(Thread.java:748)
[17:19:05 ERROR]: [FunnyGuilds] Caused by: java.time.format.DateTimeParseException: Text '600' could not be parsed at index 2
[17:19:05 ERROR]: [FunnyGuilds]         at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
[17:19:05 ERROR]: [FunnyGuilds]         at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
[17:19:05 ERROR]: [FunnyGuilds]         at java.time.LocalTime.parse(LocalTime.java:441)
[17:19:05 ERROR]: [FunnyGuilds]         at net.dzikoysk.funnyguilds.data.configs.PluginConfiguration.load(PluginConfiguration.java:1359)
[17:19:05 ERROR]: [FunnyGuilds]         at net.dzikoysk.funnyguilds.libs.eu.okaeri.configs.OkaeriConfig.load(OkaeriConfig.java:204)
[17:19:05 ERROR]: [FunnyGuilds]         at net.dzikoysk.funnyguilds.FunnyGuilds.lambda$onLoad$2(FunnyGuilds.java:108)
[17:19:05 ERROR]: [FunnyGuilds]         at net.dzikoysk.funnyguilds.libs.eu.okaeri.configs.ConfigManager.create(ConfigManager.java:50)
[17:19:05 ERROR]: [FunnyGuilds]         ... 6 more
[17:19:05 ERROR]: [FunnyGuilds]

```

**Comment by dzikoysk** [comment]
@P3ridot czy to nie jest fixnięte tymi serializatorami co dodawałeś kiedyś?

**Comment by P3ridot** [comment]
Nie, to będzie trzeba sie zastanowic jak mozna wymusić cudzysłowie, ale to będzie trzeba looknąć w internalsy okaeri-configs

**Comment by dzikoysk** [comment]
Pytał ktoś Dawida czy da się coś z tym zrobić?

**Comment by P3ridot** [comment]
Ja pytałem, dał jakieś rozwiązanie ale nie do końca zrozumiałem o co mu chodzi 😳

**Comment by PinkLolicorn** [comment]
> Nie, to będzie trzeba sie zastanowic jak mozna wymusić cudzysłowie, ale to będzie trzeba looknąć w internalsy okaeri-configs

Falsaj novajxoj, wystarczy nie dodawać leading-zero do godzin, czyli użyć `H:mm` zamiast `HH:mm`, YAML wtedy będzie sam robił escape. W przypadku dodawania zer wartość staje się ciągiem znaków, a nie czasem, stąd brak escape.

Wspaniały format. 😳
