### ISSUE TITLE
Otrzymałem taki Błąd po ponownym właczeniu serwera 

### ISSUE THREAD

**Issue by grabeq123** [FunnyGuilds/FunnyGuilds#1674]
[23:06:59 ERROR]: Could not pass event PlayerJoinEvent to FunnyGuilds v4.10.0 Tribute-8742b45
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader.lambda$0(JavaPluginLoader.java:302) ~[server.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[server.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:?]
at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:322) ~[server.jar:?]
at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:178) ~[server.jar:?]
at net.minecraft.server.v1_8_R3.LoginListener.lambda$6(LoginListener.java:140) ~[server.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:15) [server.jar:?]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1015) [server.jar:?]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) [server.jar:?]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:957) [server.jar:?]
at net.minecraft.server.v1_8_R3.MinecraftServer.loop(MinecraftServer.java:788) [server.jar:?]
at net.minecraft.server.v1_8_R3.MinecraftServer$1.run(MinecraftServer.java:125) [server.jar:?]
at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_202]
at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_202]
Caused by: java.util.NoSuchElementException: packet_handler
at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907) ~[PaperLibs-1.8.jar:?]
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157) ~[PaperLibs-1.8.jar:?]
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150) ~[PaperLibs-1.8.jar:?]
at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:314) ~[?:?]
at net.dzikoysk.funnyguilds.nms.v1_8R3.packet.GenericChannelHandlerInstaller.installChannelHandlerInPipeline(GenericChannelHandlerInstaller.java:24) ~[?:?]
at net.dzikoysk.funnyguilds.nms.v1_8R3.packet.V1_8R3PacketAccessor.getOrInstallChannelHandler(V1_8R3PacketAccessor.java:23) ~[?:?]
at net.dzikoysk.funnyguilds.listener.PlayerJoin.onJoin(PlayerJoin.java:87) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
at org.bukkit.plugin.java.JavaPluginLoader.lambda$0(JavaPluginLoader.java:300) ~[server.jar:?]
... 17 more

**Comment by Rollczi** [comment]
Nigdzie chyba nie był fixowany taki błąd.

**Comment by Rollczi** [comment]
Ogólnie to później zostało to rozwiązane u mnie na pv. (3 razy wułącz włącz ( ͡° ͜ʖ ͡°))
