### ISSUE TITLE
Problem z Tabem

### ISSUE THREAD

**Issue by Herobrine-Minecraft-YouT** [FunnyGuilds/FunnyGuilds#1683]
Witam, mam taki problem z tablistą ,w konsoli spami warnem który jest poniżej, a tablista w miecrafcie nie działa.

[15:48:36 WARN]: java.lang.NoSuchFieldException: ping
[15:48:36 WARN]:        at java.lang.Class.getField(Class.java:1703)
[15:48:36 WARN]:        at net.dzikoysk.funnyguilds.basic.User.getPing(User.java:305)
[15:48:36 WARN]:        at net.dzikoysk.funnyguilds.util.element.PlayerList.update(PlayerList.java:129)
[15:48:36 WARN]:        at net.dzikoysk.funnyguilds.util.element.PlayerList.send(PlayerList.java:158)
[15:48:36 WARN]:        at net.dzikoysk.funnyguilds.util.element.PlayerListManager.updatePlayers(PlayerListManager.java:24)
[15:48:36 WARN]:        at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:38)
[15:48:36 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:49)
[15:48:36 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:29)

Wersja: 1.7.10
Wersja pluginu: #3.9.9.15
Java: 8
Silnik: Thermos (pluginy + mody)

**Comment by CDFN** [comment]
1.7.10 nie ma wsparcia aktualnie i raczej jest mała szansa, że kiedykolwiek będzie miało.

**Comment by Herobrine-Minecraft-YouT** [comment]
> 1.7.10 nie ma wsparcia aktualnie i raczej jest mała szansa, że kiedykolwiek będzie miało.

A można sie dowiedzieć przynajmniej w czym jest dokładnie problem?

**Comment by Rollczi** [comment]
Inna impl Playera.
