### ISSUE TITLE
WorldEditPlugin - hooks.worldguard [TablistVariablesParser]

### ISSUE THREAD

**Issue by Incluuu** [FunnyGuilds/FunnyGuilds#1708]
Silnik: Purpur-1.17.1
WorldEdit v7.2.7
WorldGuard v7.0.6
FunnyGuilds v4.10.0 Tribute-39e9c91

```
[Craft Scheduler Thread - 4 - FunnyGuilds/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.10.0 Tribute-39e9c91 generated an exception while executing task 52
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877) ~[patched_1.17.1.jar:git-Purpur-1410]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.getInstance(WorldEditPlugin.java:501) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.<init>(BukkitWorld.java:117) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:123) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionSet(WorldGuard7Hook.java:77) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionNames(WorldGuard7Hook.java:88) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.DefaultTablistVariables.getWorldGuardRegionNames(DefaultTablistVariables.java:208) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.DefaultTablistVariables.lambda$install$11(DefaultTablistVariables.java:97) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.impl.SimpleTablistVariable.get(SimpleTablistVariable.java:29) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:28) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.putVars(IndividualPlayerList.java:147) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.putVarsPrepareCells(IndividualPlayerList.java:127) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.send(IndividualPlayerList.java:112) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at panda.std.stream.PandaStream.forEach(PandaStream.java:47) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at net.dzikoysk.funnyguilds.feature.tablist.TablistBroadcastHandler.run(TablistBroadcastHandler.java:29) ~[FunnyGuilds 4.10.0 (MC 1.8-1.17) - 438.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1410]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1410]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1410]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by P3ridot** [comment]
W jakiej sytuacji występuje dokładnie błąd?

**Comment by P3ridot** [comment]
Po zreprodukowaniu problemu i debugowaniu wyszło, że problem występuje jedynie przy WE w wersji 7.2.7 - wersja 7.2.6 działa normalnie. Po zajrzeniu w kod wygląda to też trochę jak problem wewnątrz WE.

**Comment by P3ridot** [comment]
Na WE 7.2.8 problem dalej występuje gdyby ktoś się zastanawiał... Albo WE jest faktycznie mocno chory psychicznie albo FG coś ma popsute... Ewentualnie oba ( ͡° ͜ʖ ͡°)

**Comment by P3ridot** [comment]
Jakby ktoś mógł sprawdzić czy błąd występuje na najnowszym Nightly

**Comment by P3ridot** [comment]
Dobra to powiedzmy, że działa najwyżej się otworzy jeszcze raz ( ͡° ͜ʖ ͡°)

**Comment by P3ridot** [comment]
Pls test now ( ͡° ͜ʖ ͡°)

**Comment by P3ridot** [comment]
Imo działa można znowu zamknąć najwyżej kolejny raz sie otworzy
