### ISSUE TITLE
Error tnt-protection (end-time)

### ISSUE THREAD

**Issue by wojtek99019pl90** [FunnyGuilds/FunnyGuilds#1714]
Przy zmienianiu czasu działania ochrony przed TNT w gildiach (chodzi o end-time) wywala w konsoli błąd:

```
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] An error occurred while handling concurrent request
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] java.time.format.DateTimeParseException: Text '600' could not be parsed at index 2
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at java.base/java.time.LocalTime.parse(LocalTime.java:465)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.0 (MC 1.8-1.17).jar//net.dzikoysk.funnyguilds.config.PluginConfiguration.loadProcessedProperties(PluginConfiguration.java:1214)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.0 (MC 1.8-1.17).jar//net.dzikoysk.funnyguilds.config.PluginConfiguration.load(PluginConfiguration.java:1122)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.0 (MC 1.8-1.17).jar//net.dzikoysk.funnyguilds.FunnyGuilds.reloadConfiguration(FunnyGuilds.java:452)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.0 (MC 1.8-1.17).jar//net.dzikoysk.funnyguilds.concurrency.requests.ReloadRequest.execute(ReloadRequest.java:30)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.0 (MC 1.8-1.17).jar//net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:32)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.0 (MC 1.8-1.17).jar//net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:21)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 	at java.base/java.lang.Thread.run(Thread.java:831)
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] Server Information:
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds]   FunnyGuilds: 4.10.0 Tribute-e8cffb8
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds]   Bukkit: 1.17.1-R0.1-SNAPSHOT
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds]   Java: 16.0.2
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds]   Thread: Thread[pool-12-thread-1,5,main]
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds]   Loaded plu
[latest.log](https://github.com/FunnyGuilds/FunnyGuilds/files/7611668/latest.log)
gins: FastAsyncWorldEdit 1.17-403;5604000, CustomHeads 3.0.3, Essentials 2.19.1-dev+33-680d323, EssentialsSpawn 2.19.1-dev+33-680d323, EssentialsChat 2.19.1-dev+33-680d323, WorldGuard 7.0.6+1cff55f
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds]   Reload count: 0
[12:59:30] [pool-12-thread-1/ERROR]: [FunnyGuilds] 
```
logi serwera [latest.log](https://github.com/FunnyGuilds/FunnyGuilds/files/7611672/latest.log)
Silnik - purpur-1.17.1-1427
Na serwerze są takie pluginy:
![image](https://user-images.githubusercontent.com/83579930/143680611-4997f065-a7db-4c9e-8caf-e5f62dd6bc22.png)

**Comment by Aides123** [comment]
Pokaż konfiguracje tego czasu

**Comment by wojtek99019pl90** [comment]
> Pokaż konfiguracje tego czasu

![image](https://user-images.githubusercontent.com/83579930/143718536-5c674f59-2694-470e-97db-c5b1809b238a.png)
Tak jest defaultowo. Gdy zmienię na 12
![image](https://user-images.githubusercontent.com/83579930/143718556-9279ed24-5cfb-4d29-8415-6f8915d1eceb.png)
po przeładowaniu wywala już błąd
![image](https://user-images.githubusercontent.com/83579930/143718571-eb01ca5e-e9af-4164-822f-67112dfb702b.png)

**Comment by Rollczi** [comment]
Zamykaj to 12:00 w '

**Comment by Rollczi** [comment]
duplicate #1603
