### ISSUE TITLE
Błąd z komendą /zaloz - 4.10.0 Tribute-e8cffb8

### ISSUE THREAD

**Issue by liskowatyy** [FunnyGuilds/FunnyGuilds#1720]
Po zainstalowaniu FunnyGuilds w wersji 4.10.0 Tribute-e8cffb8 zaczęły pojawiać się u mnie błędy, przede wszystkim brak możliwości założenia gildii. Komenda /zaloz generowała niezależnie od położenia informację, że chcę postawić gildię za blisko worldbordera. Centrowanie i zmienianie wielkości nic nie dało. Bezpośrednio po tym w konsoli natomiast pojawił się spam czymś takim:

```
[14:04:54] [Craft Scheduler Thread - 8/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.10.0 Tribute-e8cffb8 generated an exception while executing task 84
java.lang.NullPointerException: Cannot invoke "net.dzikoysk.funnyguilds.guild.Region.getSize()" because the return value of "net.dzikoysk.funnyguilds.guild.Guild.getRegion()" is null
    at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.lambda$static$8(Placeholders.java:60) ~[?:?]
    at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.lambda$raw$23(Placeholders.java:93) ~[?:?]
    at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.lambda$toFormatter$25(Placeholders.java:119) ~[?:?]
    at java.util.HashMap.forEach(HashMap.java:1425) ~[?:?]
    at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.toFormatter(Placeholders.java:119) ~[?:?]
    at net.dzikoysk.funnyguilds.feature.hooks.holographicdisplays.HologramUpdateHandler.run(HologramUpdateHandler.java:40) ~[?:?]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
    at java.lang.Thread.run(Thread.java:831) [?:?]
```
Posiadałem następujące wersje pluginów:
WorldEdit: 7.2.6
WorldGuard: 7.0.4
Holographic Displays: 2.4.8

Po zaktualizowaniu do najnowszych wersji w konsoli pojawił się spam outputem poniżej:

```
[14:29:25] [Craft Scheduler Thread - 19/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.10.0 Tribute-e8cffb8 generated an exception while executing task 4716
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.getInstance(WorldEditPlugin.java:501) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.<init>(BukkitWorld.java:117) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:123) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionSet(WorldGuard7Hook.java:77) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionNames(WorldGuard7Hook.java:88) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.DefaultTablistVariables.getWorldGuardRegionNames(DefaultTablistVariables.java:208) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.DefaultTablistVariables.lambda$install$11(DefaultTablistVariables.java:97) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.impl.SimpleTablistVariable.get(SimpleTablistVariable.java:29) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.putVars(IndividualPlayerList.java:147) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.putVarsPrepareCells(IndividualPlayerList.java:127) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.send(IndividualPlayerList.java:112) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at panda.std.stream.PandaStream.forEach(PandaStream.java:47) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.TablistBroadcastHandler.run(TablistBroadcastHandler.java:29) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[14:29:26] [Craft Scheduler Thread - 19/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.10.0 Tribute-e8cffb8 generated an exception while executing task 4716
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.getInstance(WorldEditPlugin.java:501) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.<init>(BukkitWorld.java:117) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:123) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionSet(WorldGuard7Hook.java:77) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionNames(WorldGuard7Hook.java:88) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.DefaultTablistVariables.getWorldGuardRegionNames(DefaultTablistVariables.java:208) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.DefaultTablistVariables.lambda$install$11(DefaultTablistVariables.java:97) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.impl.SimpleTablistVariable.get(SimpleTablistVariable.java:29) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.putVars(IndividualPlayerList.java:147) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.putVarsPrepareCells(IndividualPlayerList.java:127) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.send(IndividualPlayerList.java:112) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at panda.std.stream.PandaStream.forEach(PandaStream.java:47) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.TablistBroadcastHandler.run(TablistBroadcastHandler.java:29) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by dzikoysk** [comment]
Spróbuj najnowszego nightly, powinno być już git.
