### ISSUE TITLE
Niedziałająca Tablista na iSpigocie

### ISSUE THREAD

**Issue by 00fr3szuuu** [FunnyGuilds/FunnyGuilds#1896]
Przy włączaniu fg na ispigot 1.8.8 plugin nie dziala w calosci i nie dziala miedzy innymi tablista albo plugin nie wspolpracuje z innymi pluginami jak np moj core ktory pobiera z fg tag gildii gracza  wystepuje taki blad gdy gracz wchodzi na serwer:

```
[12:15:02 INFO]: UUID of player 00fr3szuu is 5c452868-5d4d-4055-b50f-99d3796046a5
[12:15:02 ERROR]: Could not pass event PlayerJoinEvent to FunnyGuilds v4.10.0 Snowdrop-2faa90b
java.lang.RuntimeException: Failed to send PlayerList for player '00fr3szuu'
        at net.dzikoysk.funnyguilds.nms.v1_8R3.playerlist.V1_8R3PlayerList.send(V1_8R3PlayerList.java:123) ~[?:?]
        at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.lambda$send$0(IndividualPlayerList.java:121) ~[?:?]
        at panda.std.Option.peek(Option.java:171) ~[?:?]
        at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.send(IndividualPlayerList.java:121) ~[?:?]
        at net.dzikoysk.funnyguilds.listener.PlayerJoin.onJoin(PlayerJoin.java:47) ~[?:?]
        at spg.lgdev.events.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[iSpigot-original.jar:git-iSpigot-PaperEdition]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[iSpigot-original.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[iSpigot-original.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:570) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin0(SourceFile:332) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerList.a(SourceFile:168) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.LoginListener.b(SourceFile:150) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.LoginListener.c(SourceFile:53) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(SourceFile:255) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(SourceFile:122) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.tickWorlds(SourceFile:899) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.tickWorlds(SourceFile:349) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.tickServer(SourceFile:766) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:645) [iSpigot-original.jar:git-iSpigot-PaperEdition]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_312]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_312]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_312]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_312]
        at net.dzikoysk.funnyguilds.nms.v1_8R3.playerlist.PlayerInfoDataHelper.createPlayerInfoData(PlayerInfoDataHelper.java:20) ~[?:?]
        at net.dzikoysk.funnyguilds.nms.v1_8R3.playerlist.V1_8R3PlayerList.send(V1_8R3PlayerList.java:74) ~[?:?]
        ... 27 more
```

**Comment by P3ridot** [comment]
Fork Spigota, który ma prawdopodobnie dziwnie skonstruowany pakiet od tablisty. Na dodatek płatny, więc trudno by było to jakkolwiek testować.
