### ISSUE TITLE
Issue while running plugin

### ISSUE THREAD

**Issue by Weberowsky** [FunnyGuilds/FunnyGuilds#1954]
```
[17:36:51 INFO]: FalaUderzeniowa issued server command: /funnyguilds:baza
[17:36:51 ERROR]: [FunnyGuilds]
[17:36:51 ERROR]: [FunnyGuilds] An exception has been caught while executing the command
[17:36:51 ERROR]: [FunnyGuilds]
[17:36:51 ERROR]: [FunnyGuilds] java.lang.NullPointerException
[17:36:51 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.feature.command.MemberValidator.isMember(MemberValidator.java:26)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.feature.command.MemberValidator.validate(MemberValidator.java:22)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.feature.command.MemberValidator.validate(MemberValidator.java:11)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.FunnyCommandsFactory.lambda$createFunnyCommands$5(FunnyCommandsFactory.java:54)
[17:36:51 ERROR]: [FunnyGuilds] 	at org.panda_lang.utilities.inject.DefaultBindHandler.process(DefaultBindHandler.java:42)
[17:36:51 ERROR]: [FunnyGuilds] 	at org.panda_lang.utilities.inject.InjectorProcessor.fetchValue(InjectorProcessor.java:70)
[17:36:51 ERROR]: [FunnyGuilds] 	at org.panda_lang.utilities.inject.InjectorProcessor.fetchValues(InjectorProcessor.java:49)
[17:36:51 ERROR]: [FunnyGuilds] 	at org.panda_lang.utilities.inject.DefaultMethodInjector.invoke(DefaultMethodInjector.java:46)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:232)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:111)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:83)
[17:36:51 ERROR]: [FunnyGuilds] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[17:36:51 ERROR]: [FunnyGuilds] 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:36:51 ERROR]: [FunnyGuilds] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:36:51 ERROR]: [FunnyGuilds] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[17:36:51 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[17:36:51 ERROR]: [FunnyGuilds] 	at java.lang.Thread.run(Thread.java:748)
[17:36:51 ERROR]: [FunnyGuilds]
[17:36:51 ERROR]: [FunnyGuilds] Server Information:
[17:36:51 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.10.1 Snowdrop-a48585e
[17:36:51 ERROR]: [FunnyGuilds]   Bukkit: 1.8.8-R0.1-SNAPSHOT
[17:36:51 ERROR]: [FunnyGuilds]   Java: 1.8.0_282
[17:36:51 ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,5,main]
[17:36:51 ERROR]: [FunnyGuilds]   Loaded plugins: WorldEdit 5.6, Essentials TeamCity, JUHC-OTCHLAN 1.0.0, YT_RzucaneTnt 1.0, PlugMan 2.1.7, YT_AdminPanel 1.0, EasyStar-Disco 1.0, WorldGuard 6.0.0-beta-03.1514-, ProtocolLib 4.2.1, EasyStar-Efekty 1.0, YT_Sprawdzanie 0.1, UniqueMOTD 1.5.1, SkinsRestorer 14.1.15, pgRandomTP 1.0, YT_Schowek 1.0, EssentialsChat TeamCity, PermissionsEx 1.19.5, FeatherBoard 1.11.2, Whitelist 1.0, Vault 1.6.6-b${env.TRAVIS_BUILD_NUMBER}, pimpeekcombatlog 2.1, EssentialsSpawn TeamCity, PluginHiderPlus 5.2, Skript 2.5, AuthMe 5.4.0-b1877, SkQuery 4.1.0, HolographicDisplays 2.4.5, EnderContainers 2.2.0, skRayFall 1.9.21, WildSkript 1.8, YT_Farmers 1.0
[17:36:51 ERROR]: null
```

**Comment by Kamilkime** [comment]
Reloady jeśli już chcesz robić - używaj tylko komendy `/funnyguilds reload`, nie rób tego Plugmanem lub Spigotowym `/reload`. Dodatkowo polecam zrobić update niektórych pluginów - np. WorldEdita raczej powinieneś mieć w wersji 6.1.9, możliwe że FunnyGuilds w ogóle nie było testowane z WE 5.

A ten pierwszy błąd... Wygląda, że w sumie mógłby być właśnie wynikiem reloada, bo taki błąd przy normalnym użytkowaniu nigdy wystąpić nie powinien.
