### ISSUE TITLE
ConcurrentModificationException przy wysłaniu tablisty

### ISSUE THREAD

**Issue by PolsatGraniePL** [FunnyGuilds/FunnyGuilds#2031]
```
[09:38:53] [Craft Scheduler Thread - 845 - FunnyGuilds/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.10.2-SNAPSHOTS Snowdrop-b8faf02 generated an exception while executing task 57
java.util.ConcurrentModificationException: null
	at java.util.AbstractList$RandomAccessSpliterator.get(AbstractList.java:737) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at panda.std.stream.PandaStream.forEach(PandaStream.java:230) ~[FunnyGuilds 4.10.2-SNAPSHOTS (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.feature.tablist.TablistBroadcastHandler.run(TablistBroadcastHandler.java:29) ~[FunnyGuilds 4.10.2-SNAPSHOTS (MC 1.8-1.19).jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
[10:03:58] [Craft Scheduler Thread - 873 - FunnyGuilds/WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.10.2-SNAPSHOTS Snowdrop-b8faf02 generated an exception while executing task 57
java.util.ConcurrentModificationException: null
	at java.util.AbstractList$RandomAccessSpliterator.get(AbstractList.java:737) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at panda.std.stream.PandaStream.forEach(PandaStream.java:230) ~[FunnyGuilds 4.10.2-SNAPSHOTS (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.feature.tablist.TablistBroadcastHandler.run(TablistBroadcastHandler.java:29) ~[FunnyGuilds 4.10.2-SNAPSHOTS (MC 1.8-1.19).jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Kamilkime** [comment]
To jest cały Exception, czy jest coś jeszcze niżej? Bo [ta linijka](https://github.com/FunnyGuilds/FunnyGuilds/blob/cee83619aed22d4a9108dc614e6ecdcb5e26104f/plugin/src/main/java/net/dzikoysk/funnyguilds/feature/tablist/TablistBroadcastHandler.java#L29) coś sypie, ale musi się coś dziać w środku IndividualPlayerList#send, a stamtąd stacktrace już nie ma. Chyba, że to wszystko, a nam to raczej nie pomaga...

**Comment by P3ridot** [comment]
Na najnowszym Nightly problem nie powinien njuż występować

**Comment by insertt** [comment]
Issue still persists with the same stacktrace as before.
