### ISSUE TITLE
Błąd przy starcie pluginu

### ISSUE THREAD

**Issue by MENQ** [FunnyGuilds/FunnyGuilds#2050]
[12:32:00] [Server thread/INFO]: [FunnyGuilds] Loading FunnyGuilds v4.10.3-SNAPSHOT Snowdrop-73349d3
[12:32:01] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[12:32:06] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] Could not find matching NmsAccessor for currently running server version: v1_18_R1 initializing FunnyGuilds v4.10.3-SNAPSHOT Snowdrop-73349d3 (Is it up to date?)
java.lang.RuntimeException: Could not find matching NmsAccessor for currently running server version: v1_18_R1
	at net.dzikoysk.funnyguilds.FunnyGuilds.prepareNmsAccessor(FunnyGuilds.java:669) ~[FunnyGuilds 4.10.3-SNAPSHOT (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:201) ~[FunnyGuilds 4.10.3-SNAPSHOT (MC 1.8-1.19).jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:426) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by MENQ** [comment]
> Update do 1.18.2? 📦

a nie można na 1.18.1?

**Comment by P3ridot** [comment]
Nie, nie wspieramy juz 1.18.1
