### ISSUE TITLE
WorldGuard-Hook error - WorldGuardPlatform is null.

### ISSUE THREAD

**Issue by Ravis96** [FunnyGuilds/FunnyGuilds#2052]
Stacktrace: (maybe something is wrong with WG?)
```
[20:40:04 ERROR]: Could not pass event PlayerJoinEvent to FunnyGuilds v4.10.2 Snowdrop-6f65021
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionSet(WorldGuard7Hook.java:93) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionNames(WorldGuard7Hook.java:103) ~[?:?]
	at net.dzikoysk.funnyguilds.user.placeholders.UserPlaceholdersService.lambda$getWorldGuardRegionNames$17(UserPlaceholdersService.java:73) ~[?:?]
	at panda.std.Option.map(Option.java:137) ~[?:?]
	at net.dzikoysk.funnyguilds.user.placeholders.UserPlaceholdersService.getWorldGuardRegionNames(UserPlaceholdersService.java:73) ~[?:?]
	at net.dzikoysk.funnyguilds.user.placeholders.UserPlaceholdersService.lambda$createPlayerPlaceholders$12(UserPlaceholdersService.java:53) ~[?:?]
	at net.dzikoysk.funnyguilds.user.placeholders.UserPlaceholders.lambda$playerProperty$1(UserPlaceholders.java:19) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.placeholder.Placeholder.getRaw(Placeholder.java:15) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.placeholder.Placeholder.get(Placeholder.java:19) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.lambda$toCustomFormatter$7(Placeholders.java:123) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.toCustomFormatter(Placeholders.java:123) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.toVariablesFormatter(Placeholders.java:104) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.formatVariables(Placeholders.java:100) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.AbstractPlaceholdersService.format(AbstractPlaceholdersService.java:67) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.TablistPlaceholdersService.format(TablistPlaceholdersService.java:35) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.putVars(IndividualPlayerList.java:156) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.putVarsPrepareCells(IndividualPlayerList.java:139) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.send(IndividualPlayerList.java:100) ~[?:?]
	at net.dzikoysk.funnyguilds.listener.PlayerJoin.onJoin(PlayerJoin.java:51) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor26.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:173) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1582) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1402) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Kamilkime** [comment]
A wersja WorldGuarda jaka?

**Comment by Ravis96** [comment]
```
[20:51:34 ERROR]: [FunnyGuilds] Server Information:
[20:51:34 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.10.2 Snowdrop-6f65021
[20:51:34 ERROR]: [FunnyGuilds]   Bukkit: 1.16.5-R0.1-SNAPSHOT
[20:51:34 ERROR]: [FunnyGuilds]   Java: 16.0.2
[20:51:34 ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,7,main]
[20:51:34 ERROR]: [FunnyGuilds]   Loaded plugins: LuckPerms 5.4.21, WorldEdit 7.2.5+57d5ac9, HolographicDisplays 2.4.9, WorldGuard 7.0.5+3827266
[20:51:34 ERROR]: [FunnyGuilds]   Reload count: 0
```

**Comment by Kamilkime** [comment]
Możesz jeszcze dla pewności wrzucić pełny log z serwera?

**Comment by Ravis96** [comment]
Ogólnie mam wrażenie, że to problem głównie WorldGuard, bo platform jest null od startu serwera.

**Comment by Kamilkime** [comment]
Javy 16 używasz... Dałbyś radę sprawdzić pod 11? W sumie to 1.16, cholera wie jak to wszystko może z 16 działać, dopiero od 1.17 bardziej coś ruszyli pod nowszą Javę

**Comment by Ravis96** [comment]
```
System Info: Java 11 (OpenJDK 64-Bit Server VM 11.0.14+9-LTS) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
2022-07-07 21:01:55,749 main WARN Advanced terminal features are not available in this environment
[21:01:59 ERROR]: No key layers in MapLike[{}]; No key structures in MapLike[{}]
[21:02:00 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:02:00 INFO]: Reloading ResourceManager: Default, bukkit
[21:02:01 INFO]: Loaded 7 recipes
[21:02:02 INFO]: Starting minecraft server version 1.16.5
[21:02:02 INFO]: Loading properties
[21:02:02 INFO]: This server is running Tuinity version git-Tuinity-"9f3435b" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[21:02:02 INFO]: Debug logging is disabled
[21:02:02 INFO]: Using 4 threads for Netty based IO
[21:02:02 INFO]: Server Ping Player Sample Count: 12
[21:02:02 INFO]: Default game type: SURVIVAL
[21:02:02 INFO]: Generating keypair
[21:02:02 INFO]: Starting Minecraft server on *:25565
[21:02:02 INFO]: Using default channel type
[21:02:02 INFO]: Tuinity: Using Java 11 compression from Velocity.
[21:02:02 INFO]: Tuinity: Using Java cipher from Velocity.
[21:02:03 INFO]: [LuckPerms] Loading LuckPerms v5.4.21
[21:02:03 INFO]: [WorldEdit] Loading WorldEdit v7.2.5+57d5ac9
[21:02:04 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@5e65e75a]
[21:02:04 INFO]: [HolographicDisplays] Loading HolographicDisplays v2.4.9
[21:02:04 INFO]: [WorldGuard] Loading WorldGuard v7.0.5+3827266
[21:02:04 INFO]: [FunnyGuilds] Loading FunnyGuilds v4.10.2 Snowdrop-6f65021
[21:02:04 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[21:02:10 INFO]: [FunnyGuilds] Available Processors: 4
[21:02:10 INFO]: [FunnyGuilds] Active Threads: 31
[21:02:10 INFO]: [FunnyGuilds] Pool size: 1
[21:02:10 INFO]: [FunnyGuilds] WorldGuard plugin hook has been early initialized!
[21:02:10 INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:02:10 INFO]: [LuckPerms] Enabling LuckPerms v5.4.21
[21:02:11 INFO]:         __    
[21:02:11 INFO]:   |    |__)   LuckPerms v5.4.21
[21:02:11 INFO]:   |___ |      Running on Bukkit - Tuinity
[21:02:11 INFO]: 
[21:02:11 INFO]: [LuckPerms] Loading configuration...
[21:02:12 INFO]: [LuckPerms] Loading storage provider... [H2]
[21:02:12 INFO]: [LuckPerms] Loading internal permission managers...
[21:02:12 INFO]: [LuckPerms] Performing initial data load...
[21:02:12 INFO]: [LuckPerms] Successfully enabled. (took 2838ms)
[21:02:12 INFO]: [WorldEdit] Enabling WorldEdit v7.2.5+57d5ac9
[21:02:12 INFO]: WEPIF: Using the Bukkit Permissions API.
[21:02:13 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3 as the Bukkit adapter
[21:02:14 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[21:02:14 WARN]: The server will make no attempt to authenticate usernames. Beware.
[21:02:14 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[21:02:14 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[21:02:14 INFO]: Preparing level "world"
[21:02:14 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[21:02:14 INFO]: Preparing start region for dimension minecraft:overworld
[21:02:14 INFO]: Time elapsed: 143 ms
[21:02:14 INFO]: Preparing start region for dimension minecraft:the_nether
[21:02:14 INFO]: Time elapsed: 46 ms
[21:02:14 INFO]: Preparing start region for dimension minecraft:the_end
[21:02:14 INFO]: Time elapsed: 56 ms
[21:02:14 INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.4.9
[21:02:15 INFO]: [WorldGuard] Enabling WorldGuard v7.0.5+3827266
[21:02:15 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[21:02:15 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[21:02:15 INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[21:02:15 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[21:02:15 INFO]: [WorldGuard] Loaded configuration for world 'world'
[21:02:15 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[21:02:15 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[21:02:15 INFO]: [WorldGuard] (world_nether) Lava fire is PERMITTED.
[21:02:15 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[21:02:15 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[21:02:15 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[21:02:15 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[21:02:15 INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
[21:02:15 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[21:02:15 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[21:02:15 INFO]: [WorldGuard] Loading region data...
[21:02:15 INFO]: [FunnyGuilds] Enabling FunnyGuilds v4.10.2 Snowdrop-6f65021
[21:02:15 WARN]: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
[21:02:15 INFO]: [FunnyGuilds] Loaded users: 1
[21:02:15 INFO]: [FunnyGuilds] No regions to load
[21:02:15 INFO]: [FunnyGuilds] No guilds to load
[21:02:15 INFO]: [FunnyGuilds] BungeeTabListPlus plugin could not be found, some features may not be available
[21:02:15 INFO]: [FunnyGuilds] Vault plugin could not be found, some features may not be available
[21:02:15 INFO]: [FunnyGuilds] MVdWPlaceholderAPI plugin could not be found, some features may not be available
[21:02:15 INFO]: [FunnyGuilds] PlaceholderAPI plugin could not be found, some features may not be available
[21:02:15 INFO]: [FunnyGuilds] WorldEdit plugin hook has been initialized!
[21:02:15 INFO]: [FunnyGuilds] HolographicDisplays plugin hook has been initialized!
[21:02:15 INFO]: [FunnyGuilds] ~ Created by FunnyGuilds Team ~
[21:02:16 INFO]: Running delayed init tasks
[21:02:16 INFO]: Done (13.564s)! For help, type "help"
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Please update the version of Java you use to run Paper
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] * to at least Java 16. When Paper for Minecraft 1.17 is
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] * released support for versions of Java before 16 will
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] * be dropped.
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Current Java version: 11.0.14
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Check this forum post for more information: 
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] *   https://papermc.io/java16
[21:02:16 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[21:02:16 INFO]: Timings Reset
[21:02:17 INFO]: [HolographicDisplays] Found a new version available: v3.0.0
[21:02:17 INFO]: [HolographicDisplays] Download it on Bukkit Dev:
[21:02:17 INFO]: [HolographicDisplays] dev.bukkit.org/projects/holographic-displays
[21:02:17 INFO]: 
[21:02:17 INFO]: -----------------------------------
[21:02:17 INFO]: Dostepna jest nowa wersja FunnyGuilds Nightly!
[21:02:17 INFO]: Obecna: 4.10.2 Snowdrop-6f65021
[21:02:17 INFO]: Najnowsza: 4.10.3-SNAPSHOT Snowdrop
-73349d3
[21:02:17 INFO]: GitHub: https://github.com/funnyguilds/funnyguilds
[21:02:17 INFO]: Discord: https://discord.com/invite/CYvyq3u
[21:02:17 INFO]: -----------------------------------
[21:02:17 INFO]: 
[21:02:20 INFO]: UUID of player Ravis96 is 2dd9e7bf-bd39-38b5-a7fb-6287b1271ac7
[21:02:20 ERROR]: Could not pass event PlayerJoinEvent to FunnyGuilds v4.10.2 Snowdrop-6f65021
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionSet(WorldGuard7Hook.java:93) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionNames(WorldGuard7Hook.java:103) ~[?:?]
	at net.dzikoysk.funnyguilds.user.placeholders.UserPlaceholdersService.lambda$getWorldGuardRegionNames$17(UserPlaceholdersService.java:73) ~[?:?]
	at panda.std.Option.map(Option.java:137) ~[?:?]
	at net.dzikoysk.funnyguilds.user.placeholders.UserPlaceholdersService.getWorldGuardRegionNames(UserPlaceholdersService.java:73) ~[?:?]
	at net.dzikoysk.funnyguilds.user.placeholders.UserPlaceholdersService.lambda$createPlayerPlaceholders$12(UserPlaceholdersService.java:53) ~[?:?]
	at net.dzikoysk.funnyguilds.user.placeholders.UserPlaceholders.lambda$playerProperty$1(UserPlaceholders.java:19) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.placeholder.Placeholder.getRaw(Placeholder.java:15) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.placeholder.Placeholder.get(Placeholder.java:19) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.lambda$toCustomFormatter$7(Placeholders.java:123) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.toCustomFormatter(Placeholders.java:123) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.toVariablesFormatter(Placeholders.java:104) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.Placeholders.formatVariables(Placeholders.java:100) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.placeholders.AbstractPlaceholdersService.format(AbstractPlaceholdersService.java:67) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.TablistPlaceholdersService.format(TablistPlaceholdersService.java:35) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.putVars(IndividualPlayerList.java:156) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.putVarsPrepareCells(IndividualPlayerList.java:139) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.tablist.IndividualPlayerList.send(IndividualPlayerList.java:100) ~[?:?]
	at net.dzikoysk.funnyguilds.listener.PlayerJoin.onJoin(PlayerJoin.java:51) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor176.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:173) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1582) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1402) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[21:02:20 INFO]: Ravis96 joined the game
[21:02:20 INFO]: Ravis96[/127.0.0.1:58688] logged in with entity id 50 at ([world]104.66295521931573, 4.5491385452200195, 101.22975514896046)
[21:02:36 INFO]: Ravis96 issued server command: /zaloz ELOO cootam
[21:02:36 ERROR]: [FunnyGuilds] 
[21:02:36 ERROR]: [FunnyGuilds] An exception has been caught while executing the command
[21:02:36 ERROR]: [FunnyGuilds] 
[21:02:36 ERROR]: [FunnyGuilds] java.lang.NullPointerException
[21:02:36 ERROR]: [FunnyGuilds] 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
[21:02:36 ERROR]: [FunnyGuilds] 	at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getRegionSet(WorldGuard7Hook.java:93)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.isInNonGuildsRegion(WorldGuard7Hook.java:53)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.feature.command.user.CreateCommand.execute(CreateCommand.java:156)
[21:02:36 ERROR]: [FunnyGuilds] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:02:36 ERROR]: [FunnyGuilds] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:02:36 ERROR]: [FunnyGuilds] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:02:36 ERROR]: [FunnyGuilds] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[21:02:36 ERROR]: [FunnyGuilds] 	at org.panda_lang.utilities.inject.DefaultMethodInjector.invoke(DefaultMethodInjector.java:46)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:232)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:111)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:83)
[21:02:36 ERROR]: [FunnyGuilds] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:02:36 ERROR]: [FunnyGuilds] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2267)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2082)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2035)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138)
[21:02:36 ERROR]: [FunnyGuilds] 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[21:02:36 ERROR]: [FunnyGuilds] 	at java.base/java.lang.Thread.run(Thread.java:829)
[21:02:36 ERROR]: [FunnyGuilds] 
[21:02:36 ERROR]: [FunnyGuilds] Server Information:
[21:02:36 ERROR]: [FunnyGuilds]   FunnyGuilds: 4.10.2 Snowdrop-6f65021
[21:02:36 ERROR]: [FunnyGuilds]   Bukkit: 1.16.5-R0.1-SNAPSHOT
[21:02:36 ERROR]: [FunnyGuilds]   Java: 11.0.14
[21:02:36 ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,7,main]
[21:02:36 ERROR]: [FunnyGuilds]   Loaded plugins: LuckPerms 5.4.21, WorldEdit 7.2.5+57d5ac9, HolographicDisplays 2.4.9, WorldGuard 7.0.5+3827266
[21:02:36 ERROR]: [FunnyGuilds]   Reload count: 0
[21:02:36 ERROR]: [FunnyGuilds] 
```

**Comment by Ravis96** [comment]
Error solved, widocznie samo sie naprawiło, bo wstawiłem tą samą wersje (z tym samym kodem), tylko inny build. Java jest super. <3
