### ISSUE TITLE
Create guild bug

### ISSUE THREAD

**Issue by eki-github** [FunnyGuilds/FunnyGuilds#2187]
[17:54:58] [Server thread/INFO]: _eki issued server command: /zaloz
[17:55:02] [Server thread/INFO]: _eki issued server command: /zaloz EYsee STEAWD
[17:55:06] [Server thread/INFO]: _eki issued server command: /zaloz EYse STEAWD
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] Could not retrieve class
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.ItemStack
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/java.lang.Class.forName0(Native Method)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/java.lang.Class.forName(Class.java:375)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.nms.Reflections.getClass(Reflections.java:57)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.nms.Reflections.getNMSClass(Reflections.java:69)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.shared.spigot.ItemComponentUtils.<clinit>(ItemComponentUtils.java:30)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.shared.bukkit.ItemUtils.playerHasEnoughItems(ItemUtils.java:69)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.feature.command.user.CreateCommand.execute(CreateCommand.java:152)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//org.panda_lang.utilities.inject.DefaultMethodInjector.invoke(DefaultMethodInjector.java:46)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:232)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:111)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:83)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2262)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] Server Information:
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   FunnyGuilds: 4.10.2 Snowdrop-6f65021
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   Bukkit: 1.17.1-R0.1-SNAPSHOT
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   Java: 17.0.4
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,7,main]
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   Loaded plugins: WorldEdit 7.2.9+e20e013, Skript 2.5-beta1, SafeMC-AntiCrash 1.0, PlaceholderAPI 2.10.9, AdvancedBan 2.3.0, kSwear 1.0 Public Version, FancyBags 1.8.4, InventoryRollback 1.4.0, Report 1.0, ChestCommands 4.0.3, PL-Hide 1.5.20, _ekiAntiAd 1.0-SNAPSHOT, ViaVersion 4.2.1, NexEngine 2.1.2 build-24/04/2022, ViaBackwards 4.2.0, ViaRewind 2.0.2, LuckPerms 5.4.9, PlayerKits 2.22.2, Essentials 2.19.7, PlotSquared 6.0.6-SNAPSHOT, ProtocolLib 4.7.0, WorldGuard 7.0.7+216b061, Multiverse-Core 4.3.1-b861, SkinsRestorer 14.2.3, Citizens 2.0.29-SNAPSHOT (build 2470), Vouchers 2.2.1, Vulcan 2.3.1, Shopkeepers 2.14.0, TradeSystem 2.1.0, WolfyUtilities 4.16.7.0, TAB 3.1.5, GSit [6.0.4.1], SuperVanish 6.2.7, MineResetLite 4.2.14-VK, EssentialsSpawn 2.19.7, PvPManager 3.16.7, LPC 3.5.0, WorldGuardExtraFlags 4.1.5-SNAPSHOT, Matrix 6.5.0, CustomCrafting 3.16.8.1, HolographicDisplays 2.4.9, ItemEdit 2.19, ExcellentCrates 4.0.6, HolographicExtension 1.10.9
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   Reload count: 0
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] Could not retrieve class
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.NBTTagCompound
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/java.lang.Class.forName0(Native Method)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/java.lang.Class.forName(Class.java:375)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.nms.Reflections.getClass(Reflections.java:57)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.nms.Reflections.getNMSClass(Reflections.java:69)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.shared.spigot.ItemComponentUtils.<clinit>(ItemComponentUtils.java:31)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.shared.bukkit.ItemUtils.playerHasEnoughItems(ItemUtils.java:69)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.feature.command.user.CreateCommand.execute(CreateCommand.java:152)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//org.panda_lang.utilities.inject.DefaultMethodInjector.invoke(DefaultMethodInjector.java:46)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:232)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:111)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at FunnyGuilds 4.10.2 (MC 1.8-1.19).jar//net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:83)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2262)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] Server Information:
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   FunnyGuilds: 4.10.2 Snowdrop-6f65021
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   Bukkit: 1.17.1-R0.1-SNAPSHOT
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   Java: 17.0.4
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   Thread: Thread[Server thread,7,main]
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   Loaded plugins: WorldEdit 7.2.9+e20e013, Skript 2.5-beta1, SafeMC-AntiCrash 1.0, PlaceholderAPI 2.10.9, AdvancedBan 2.3.0, kSwear 1.0 Public Version, FancyBags 1.8.4, InventoryRollback 1.4.0, Report 1.0, ChestCommands 4.0.3, PL-Hide 1.5.20, _ekiAntiAd 1.0-SNAPSHOT, ViaVersion 4.2.1, NexEngine 2.1.2 build-24/04/2022, ViaBackwards 4.2.0, ViaRewind 2.0.2, LuckPerms 5.4.9, PlayerKits 2.22.2, Essentials 2.19.7, PlotSquared 6.0.6-SNAPSHOT, ProtocolLib 4.7.0, WorldGuard 7.0.7+216b061, Multiverse-Core 4.3.1-b861, SkinsRestorer 14.2.3, Citizens 2.0.29-SNAPSHOT (build 2470), Vouchers 2.2.1, Vulcan 2.3.1, Shopkeepers 2.14.0, TradeSystem 2.1.0, WolfyUtilities 4.16.7.0, TAB 3.1.5, GSit [6.0.4.1], SuperVanish 6.2.7, MineResetLite 4.2.14-VK, EssentialsSpawn 2.19.7, PvPManager 3.16.7, LPC 3.5.0, WorldGuardExtraFlags 4.1.5-SNAPSHOT, Matrix 6.5.0, CustomCrafting 3.16.8.1, HolographicDisplays 2.4.9, ItemEdit 2.19, ExcellentCrates 4.0.6, HolographicExtension 1.10.9
[17:55:06] [Server thread/ERROR]: [FunnyGuilds]   Reload count: 0
[17:55:06] [Server thread/ERROR]: [FunnyGuilds] 
[17:55:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'zaloz EYse STEAWD' in net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand(zaloz)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.FunnyCommandsException: Cannot invoke command
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.lambda$execute$2(DynamicCommand.java:122) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at panda.std.Option.orThrow(Option.java:219) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:122) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:83) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-408]
	... 20 more
Caused by: java.lang.ExceptionInInitializerError
	at net.dzikoysk.funnyguilds.shared.bukkit.ItemUtils.playerHasEnoughItems(ItemUtils.java:69) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.feature.command.user.CreateCommand.execute(CreateCommand.java:152) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.panda_lang.utilities.inject.DefaultMethodInjector.invoke(DefaultMethodInjector.java:46) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:232) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:111) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:83) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-408]
	... 20 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredConstructors()" because "clazz" is null
	at net.dzikoysk.funnyguilds.nms.Reflections.getConstructor(Reflections.java:241) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.shared.spigot.ItemComponentUtils.<clinit>(ItemComponentUtils.java:33) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.shared.bukkit.ItemUtils.playerHasEnoughItems(ItemUtils.java:69) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.feature.command.user.CreateCommand.execute(CreateCommand.java:152) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.panda_lang.utilities.inject.DefaultMethodInjector.invoke(DefaultMethodInjector.java:46) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:232) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:111) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:83) ~[FunnyGuilds 4.10.2 (MC 1.8-1.19).jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-408]
	... 20 more

Engine: paper-1.17.1-408.jar
![image](https://user-images.githubusercontent.com/65031661/200895307-0b41305d-ab74-45f6-a0e5-b89ae5ee28e3.png)

**Comment by Kamilkime** [comment]
Na najnowszym nightly błąd też występuje?

**Comment by eki-github** [comment]
tak na każdym

**Comment by eki-github** [comment]
mam wyłączone wszystko z regionami a tak to działa
ale chce mieć wyłączone

**Comment by Kamilkime** [comment]
Wygląda, że nie działa funkcja od pokazywania itemów po najechaniu na wiadomość na chacie. Wyłączenie funkcji w configu powinno pomóc.

**Comment by eki-github** [comment]
okej zobacze i napisze

**Comment by eki-github** [comment]
Dziękuje działa
