### ISSUE TITLE
Błąd podczas włączania serwera

### ISSUE THREAD

**Issue by Vejzak** [FunnyGuilds/FunnyGuilds#2417]
[14:28:09 INFO]: Done (69.378s)! For help, type "help"
container@pterodactyl~ Serwer oznaczony jako running...
[14:28:09 INFO]: Timings Reset
[14:28:09 INFO]: Checking for updates via Spigot...
[14:28:17 INFO]: Could not get skin data from session servers!
[14:28:17 INFO]: Could not get skin data from session servers!
[14:28:17 INFO]: Could not get skin data from session servers!
[14:28:17 INFO]: Could not get skin data from session servers!
[14:28:17 INFO]: Could not get skin data from session servers!
[14:28:17 WARN]: [ViaVersion] Could not check for updates, check your connection.
[14:28:17 WARN]: [HolographicDisplays] Could not contact BukkitDev to check for updates.
[14:28:17 INFO]: [FunnyGuilds] [Updater] > Connection to the server (https://api.github.com/repos/FunnyGuilds/FunnyGuilds/commits) failed!
[14:28:17 INFO]: [FunnyGuilds] [Updater] > Reason: java.net.UnknownHostException: api.github.com
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2035)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2030)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2029)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at net.dzikoysk.funnyguilds.shared.FunnyIOUtils.getContent(FunnyIOUtils.java:84)
        at net.dzikoysk.funnyguilds.FunnyGuildsVersion.lambda$isNewAvailable$0(FunnyGuildsVersion.java:47)
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.net.UnknownHostException: api.github.com
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
        at java.base/java.net.Socket.connect(Socket.java:645)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3206)
        at java.base/java.net.URLConnection.getContentEncoding(URLConnection.java:530)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:380)
        at net.dzikoysk.funnyguilds.shared.FunnyIOUtils.getContent(FunnyIOUtils.java:81)
        ... 7 more

[14:28:17 INFO]: [FunnyGuilds] [Updater] > Could not retrieve latest nightly version!
[14:28:17 INFO]: [FunnyGuilds] [Updater] > java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonArray.size()" because "ghCommits" is null
        at net.dzikoysk.funnyguilds.FunnyGuildsVersion.lambda$isNewAvailable$0(FunnyGuildsVersion.java:50)
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)

[14:28:19 INFO]: [CratesPlus] Failed to check for updates. Will try again later.

**Comment by P3ridot** [comment]
Nie masz połączenia z internetem co widać po logach z innych pluginów

Jeśli używasz jakiegoś hostingu to może on blokować takie requesty i nic się z tym nie zrobi ¯\_(ツ)_/¯
