### ISSUE TITLE
[WorldGuard] NullPointerException przy zadawaniu damage'u

### ISSUE THREAD

**Issue by deestt** [FunnyGuilds/FunnyGuilds#2439]
```
[18:33:50 ERROR]: Could not pass event EntityDamageByEntityEvent to FunnyGuilds v4.12.1-SNAPSHOT Snowdrop-0060740
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:209) ~[?:?]
        at java.util.Optional.of(Optional.java:113) ~[?:?]
        at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:194) ~[?:?]
        at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:191) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at panda.std.stream.PandaStream.head(PandaStream.java:202) ~[FunnyGuilds 4.12.1-SNAPSHOT.1694 (MC 1.8-1.19).jar:?]
        at net.dzikoysk.funnyguilds.feature.hooks.worldguard.WorldGuard7Hook.getFriendlyFireStatus(WorldGuard7Hook.java:79) ~[FunnyGuilds 4.12.1-SNAPSHOT.1694 (MC 1.8-1.19).jar:?]
        at net.dzikoysk.funnyguilds.listener.EntityDamage.lambda$onDamage$3(EntityDamage.java:61) ~[FunnyGuilds 4.12.1-SNAPSHOT.1694 (MC 1.8-1.19).jar:?]
        at panda.std.Option.map(Option.java:154) ~[FunnyGuilds 4.12.1-SNAPSHOT.1694 (MC 1.8-1.19).jar:?]
        at net.dzikoysk.funnyguilds.listener.EntityDamage.lambda$onDamage$6(EntityDamage.java:60) ~[FunnyGuilds 4.12.1-SNAPSHOT.1694 (MC 1.8-1.19).jar:?]
        at panda.std.Option.peek(Option.java:200) ~[FunnyGuilds 4.12.1-SNAPSHOT.1694 (MC 1.8-1.19).jar:?]
        at net.dzikoysk.funnyguilds.listener.EntityDamage.onDamage(EntityDamage.java:22) ~[FunnyGuilds 4.12.1-SNAPSHOT.1694 (MC 1.8-1.19).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor313.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1984]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:252) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1192) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1049) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:992) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1226) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2220) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1098) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1427) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1005) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1124) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1359) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2239) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2969) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2891) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1984]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Kamilkime** [comment]
Jakiś opis byłby fajny, np. informacja kiedy to się dzieje

**Comment by deestt** [comment]
Właśnie nie wiem, bo ja tylko widze w konsoli ze wyrzuca errory

**Comment by ghost** [comment]
user issue

**Comment by P3ridot** [comment]
Wypróbuj najnowszego nightly, tam powinno to już być naprawione

**Comment by P3ridot** [comment]
Problem dalej występuje

![image](https://github.com/FunnyGuilds/FunnyGuilds/assets/28200355/2f1e21c5-9ff7-482f-9c1a-df0066b34814)
Podsyłam trochę nowszą wersje błędu

**Comment by P3ridot** [comment]
Trzeba wytestować najnowsze Nightly, tam powinno już to być naprawione

Na razie zostawię otwarte i jeśli nikt nie zgłosi, że jest problem to się zamknie

**Comment by P3ridot** [comment]
Chyba completed
