### ISSUE TITLE
Hologramy się nie pokazują

### ISSUE THREAD

**Issue by Erdef119** [FunnyGuilds/FunnyGuilds#2441]
Hologramy nad sercem gildii się nie pokazują i na konsoli serwera co około 5-10 sekund wyświetla się błąd:

[FunnyGuilds] Plugin FunnyGuilds v4.12.1-SNAPSHOT Snowdrop-f5e2ed7 generated an exception while executing task 9562
java.lang.IllegalArgumentException: Hologram name can only contain alphanumeric characters, underscores and dashes! (funnyguilds:guild:Administracja)
	at eu.decentsoftware.holograms.api.DHAPI.createHologram(DHAPI.java:85) ~[DecentHolograms-2.8.2.jar:?]
	at eu.decentsoftware.holograms.api.DHAPI.createHologram(DHAPI.java:53) ~[DecentHolograms-2.8.2.jar:?]
	at net.dzikoysk.funnyguilds.feature.hooks.decentholograms.DecentHologramsHook.lambda$update$1(DecentHologramsHook.java:72) ~[FunnyGuilds 4.12.1-SNAPSHOT.1681 (MC 1.8-1.19).jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.hooks.decentholograms.DecentHologramsHook.update(DecentHologramsHook.java:70) ~[FunnyGuilds 4.12.1-SNAPSHOT.1681 (MC 1.8-1.19).jar:?]
	at net.dzikoysk.funnyguilds.feature.hooks.decentholograms.DecentHologramsHook.update(DecentHologramsHook.java:54) ~[FunnyGuilds 4.12.1-SNAPSHOT.1681 (MC 1.8-1.19).jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.dzikoysk.funnyguilds.feature.hooks.decentholograms.DecentHologramsHook.lambda$init$0(DecentHologramsHook.java:43) ~[FunnyGuilds 4.12.1-SNAPSHOT.1681 (MC 1.8-1.19).jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-97]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.1.jar:git-Paper-97]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

Kawałek configu w którym konfiguruje się hologramy:

displayed-lines:
    - '&7&m-------------------'
    - '&7- &bGildia {TAG} &7-'
    - '&7- &bZycia {LIVES} &7-'
    - '&7&m-------------------'

**Comment by Kamilkime** [comment]
Pobierz najnowsze FG 4.x, powinno pomóc: https://ci.insertt.dev/job/FunnyGuilds/job/4.x/
