### ISSUE TITLE
Błąd podczas dołączania do gildii [4.13.1-SNAPSHOT Snowdrop-7c21433]

### ISSUE THREAD

**Issue by DYNIUU** [FunnyGuilds/FunnyGuilds#2603]
Najnowsza wersja FunnyGuilds Nightly posada błąd podczas dołączania do gildii!

( Wersja z lip 31 nie posiadała takiego błędu)

Gracz próbując dołączyć do gildii przez /dolacz CWEL (CWEL to tag gildii) wyskakuje błąd na chat gracza: 

`"[17:41:02] [Render thread/INFO] [minecraft/ChatComponent]: [CHAT] An internal error occurred while attempting to perform this command"`

W konsoli  log:

```
[15:41:02] [Server thread/INFO]: _NazwaGracza_ issued server command: /dolacz CWEL
[15:41:02] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'dolacz CWEL' in net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand(dolacz)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2231) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2191) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:112) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1564) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.FunnyCommandsException: Cannot invoke command
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.lambda$execute$1(DynamicCommand.java:113) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at panda.std.Option.orThrow(Option.java:244) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:113) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:82) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 28 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.dzikoysk.funnyguilds.shared.adventure.LegacyItemHoverEventHelper
	at net.dzikoysk.funnyguilds.shared.adventure.ItemComponentHelper.itemAsComponent(ItemComponentHelper.java:48) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.shared.adventure.ItemComponentHelper$ItemReplacement.<init>(ItemComponentHelper.java:78) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.shared.adventure.ItemComponentHelper$ItemReplacement.<init>(ItemComponentHelper.java:66) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.shared.adventure.ItemComponentHelper.prepareItemReplacement(ItemComponentHelper.java:59) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.shared.bukkit.ItemUtils.playerHasEnoughItems(ItemUtils.java:66) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.feature.command.user.JoinCommand.execute(JoinCommand.java:63) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.panda_lang.utilities.inject.DefaultMethodInjector.invoke(DefaultMethodInjector.java:47) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:223) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:110) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:82) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 28 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException: net.minecraft.world.item [in thread "Server thread"]
	at java.util.Objects.requireNonNull(Objects.java:360) ~[?:?]
	at net.dzikoysk.funnyguilds.nms.Reflections.getNMSClass(Reflections.java:79) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.shared.adventure.LegacyItemHoverEventHelper.<clinit>(LegacyItemHoverEventHelper.java:21) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.shared.adventure.ItemComponentHelper.itemAsComponent(ItemComponentHelper.java:48) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.shared.adventure.ItemComponentHelper$ItemReplacement.<init>(ItemComponentHelper.java:78) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.shared.adventure.ItemComponentHelper$ItemReplacement.<init>(ItemComponentHelper.java:66) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.shared.adventure.ItemComponentHelper.prepareItemReplacement(ItemComponentHelper.java:59) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.shared.bukkit.ItemUtils.playerHasEnoughItems(ItemUtils.java:66) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.feature.command.user.JoinCommand.execute(JoinCommand.java:63) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.panda_lang.utilities.inject.DefaultMethodInjector.invoke(DefaultMethodInjector.java:47) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.invoke(DynamicCommand.java:223) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:110) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at net.dzikoysk.funnyguilds.libs.net.dzikoysk.funnycommands.commands.DynamicCommand.execute(DynamicCommand.java:82) ~[FunnyGuilds 4.13.1-SNAPSHOT.1732 (MC 1.8-1.21).jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2231) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2191) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	... 2 more
```
![image](https://github.com/user-attachments/assets/fa3cb920-e0d0-4609-97ef-e4c151a831b9)

**Comment by Kamilkime** [comment]
Przestaw `enable-item-component` na false w configu i powinno działać
