### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by MattiGB** [FunnyGuilds/FunnyGuilds#392]
W trakcie działania serwera dostaję taki błąd:

```
[18:26:53] [IndependentThread/WARN]: java.lang.NullPointerException
[18:26:53] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:37)
[18:26:53] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:86)
[18:26:53] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:48)
[18:26:53] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:28)
[18:26:53] [IndependentThread/WARN]: java.lang.NullPointerException
[18:26:53] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:51)
[18:26:53] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:86)
[18:26:53] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:48)
[18:26:53] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:28)
```

Później mam masę ostrzeżeń:

```
> [[19:03:11] [IndependentThread/WARN]: java.lang.NullPointerException
> [19:03:11] [IndependentThread/WARN]: java.lang.NullPointerException
> [19:03:11] [IndependentThread/WARN]: java.lang.NullPointerException
> [19:03:11] [IndependentThread/WARN]: java.lang.NullPointerException
> [19:03:12] [IndependentThread/WARN]: java.lang.NullPointerException
> [19:03:12] [IndependentThread/WARN]: java.lang.NullPointerException
```

Używam najnowszej wersji FG 3.9.9.7 i wersję mc 1.7.10
FG podpięte pod bazę danych lokalnie.

**Comment by dzikoysk** [comment]
Stary błąd, na szczęście niegroźny, ale za to irytujący :/ Poprawię w wolnej chwili

**Comment by MattiGB** [comment]
Dzięki wielkie za szybką odpowiedź. Konsola płacze ;D

**Comment by dzikoysk** [comment]
Testuj :P 
https://funnyguilds.net/download/cleaned/3.9.9.8/funnyguilds-3.9.9.7.jar

**Comment by MattiGB** [comment]
Wszystko działa ;)
