### ISSUE TITLE
Problem z wersją Javy

### ISSUE THREAD

**Issue by ALISTAR1234** [FunnyGuilds/FunnyGuilds#394]
Plugin nie działa wersja BUKKIT 1.7.2 LOGI:
[18:19:41] [Server thread/INFO]: [FunnyGuilds] Loading FunnyGuilds v3.9.9.7 Cleaned
[18:19:41] [Server thread/ERROR]: org/panda_lang/panda/util/configuration/PandaConfiguration : Unsupported major.minor version 52.0 initializing FunnyGuilds v3.9.9.7 Cleaned (Is it up to date?)
java.lang.UnsupportedClassVersionError: org/panda_lang/panda/util/configuration/PandaConfiguration : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_80]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_80]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_80]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_80]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at net.dzikoysk.funnyguilds.util.Reloader.init(Reloader.java:16) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:43) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]

**Comment by Inuun** [comment]
> BUKKIT 1.7.2

Wgraj Spigot 1.7.10

**Comment by ALISTAR1234** [comment]
Właśnie używam Javy 8. Wgrałem Spigot 1.7.10 dalej to samo.

**Comment by kamcio96** [comment]
Podeślij log z: `java -version`

**Comment by Inuun** [comment]
`sudo apt-get install oracle-java8-set-default` w terminalu
