### ISSUE TITLE
Wygasanie gildii

### ISSUE THREAD

**Issue by dzikoysk** [FunnyGuilds/FunnyGuilds#405]
_Zgłoszone przez jednego z użytkowników_

https://pastebin.com/raw/uCuyskin

**Comment by ProgrammingWizzard** [comment]
```
[17:01:04 INFO]: _an0[/127.0.0.1:60617] logged in with entity id 190 at ([world] 198.54083537921093, 66.33352325081522, 507.4313549096746)
[17:01:42 ERROR]: [Server thread/ERROR] #!# [MySQL] Update: INSERT INTO `users` (`uuid`, `name`, `points`, `kills`, `deaths`, `ban`, `reason`) VALUES ('6477d13c-835e-4701-ae79-238324166a85','_an0','1000','0','0','0','') ON DUPLICATE KEY UPDATE `name`='_an0',`points`='1000',`kills`='0',`deaths`='0',`ban`='0',`reason`=''
[17:01:42 WARN]: java.lang.NullPointerException
[17:01:42 WARN]:        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:119)
[17:01:42 WARN]:        at net.dzikoysk.funnyguilds.data.database.DatabaseUser.save(DatabaseUser.java:22)
[17:01:42 WARN]:        at net.dzikoysk.funnyguilds.data.database.DatabaseBasic.save(DatabaseBasic.java:97)
[17:01:42 WARN]:        at net.dzikoysk.funnyguilds.data.Manager.save(Manager.java:44)
[17:01:42 WARN]:        at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:41)
[17:01:42 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:48)
[17:01:42 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:28)
```

Obecny error przy zapisie użytkowników do DB.

**Comment by ProgrammingWizzard** [comment]
Dobra, zapis śmiga jak należy. Zostało jeszcze naprawienie tego błędu:
```
[18:07:05 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'ban'
[18:07:05 WARN]:        at sun.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source)
[18:07:05 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:07:05 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:07:05 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[18:07:05 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[18:07:05 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[18:07:05 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[18:07:05 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[18:07:05 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[18:07:05 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[18:07:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[18:07:05 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[18:07:05 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[18:07:05 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[18:07:05 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[18:07:05 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[18:07:05 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[18:07:05 WARN]:        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:118)
[18:07:05 WARN]:        at net.dzikoysk.funnyguilds.data.database.DatabaseBasic.usersTable(DatabaseBasic.java:192)
[18:07:05 WARN]:        at net.dzikoysk.funnyguilds.data.database.DatabaseBasic.load(DatabaseBasic.java:27)
[18:07:05 WARN]:        at net.dzikoysk.funnyguilds.data.Manager.<init>(Manager.java:23)
[18:07:05 WARN]:        at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:55)
[18:07:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:07:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[18:07:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[18:07:05 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[18:07:05 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[18:07:05 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:866)
[18:07:05 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:301)
[18:07:05 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
[18:07:05 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[18:07:05 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
[18:07:05 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:753)
[18:07:05 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:326)
[18:07:05 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:290)
[18:07:05 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[18:07:05 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[18:07:05 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[18:07:06 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'reason'
[18:07:06 WARN]:        at sun.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:118)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.database.DatabaseBasic.guildsTable(DatabaseBasic.java:162)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.database.DatabaseBasic.load(DatabaseBasic.java:29)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.Manager.<init>(Manager.java:23)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:55)
[18:07:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:07:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[18:07:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:866)
[18:07:06 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:301)
[18:07:06 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
[18:07:06 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:753)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:326)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:290)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[18:07:06 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'pvp'
[18:07:06 WARN]:        at sun.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source)
[18:07:06 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:07:06 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:07:06 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[18:07:06 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[18:07:06 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[18:07:06 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[18:07:06 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[18:07:06 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[18:07:06 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[18:07:06 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[18:07:06 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[18:07:06 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[18:07:06 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[18:07:06 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[18:07:06 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[18:07:06 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:118)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.database.DatabaseBasic.guildsTable(DatabaseBasic.java:163)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.database.DatabaseBasic.load(DatabaseBasic.java:29)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.Manager.<init>(Manager.java:23)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:55)
[18:07:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:07:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[18:07:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:866)
[18:07:06 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:301)
[18:07:06 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
[18:07:06 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:753)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:326)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:290)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[18:07:06 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'deputy'
[18:07:06 WARN]:        at sun.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source)
[18:07:06 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:07:06 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:07:06 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[18:07:06 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[18:07:06 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[18:07:06 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[18:07:06 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[18:07:06 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[18:07:06 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[18:07:06 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[18:07:06 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[18:07:06 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[18:07:06 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[18:07:06 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[18:07:06 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[18:07:06 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.database.Database.executeUpdate(Database.java:118)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.database.DatabaseBasic.guildsTable(DatabaseBasic.java:164)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.database.DatabaseBasic.load(DatabaseBasic.java:29)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.data.Manager.<init>(Manager.java:23)
[18:07:06 WARN]:        at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:55)
[18:07:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:07:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[18:07:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:866)
[18:07:06 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:301)
[18:07:06 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
[18:07:06 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
[18:07:06 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:753)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:326)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:290)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[18:07:06 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
```

**Comment by ProgrammingWizzard** [comment]
Naprawiono, zostanie wdrożone w 3.9.9.9.
