### ISSUE TITLE
Nie działa tablista ~ FunnyGuilds 3.9.9.10

### ISSUE THREAD

**Issue by sittles** [FunnyGuilds/FunnyGuilds#419]
Witam, w ogóle nie wyświetla się tab lista i wyskakuje parę błędów. Proszę o pomoc:)
```
[20:26:46 INFO]: CONSOLE: Reload complete.
[20:26:46 WARN]: [FunnyGuilds] Task #1288 for FunnyGuilds v3.9.9.10 Cleaned generated an exception
java.lang.NoClassDefFoundError: net/minecraft/util/io/netty/channel/ChannelHandler
        at net.dzikoysk.funnyguilds.FunnyGuilds.lambda$patch$1(FunnyGuilds.java:130) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:720) [spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-870264a-0a645a2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.ChannelHandler
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-870264a-0a645a2]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        ... 8 more
[20:26:51 WARN]: Exception in thread "FunnyGuilds | IndependentThread"
[20:26:51 WARN]: java.lang.NoClassDefFoundError: net/minecraft/util/com/mojang/authlib/GameProfile
[20:26:51 WARN]:        at net.dzikoysk.funnyguilds.basic.OfflineUser.init(OfflineUser.java:66)
[20:26:51 WARN]:        at net.dzikoysk.funnyguilds.basic.OfflineUser.<init>(OfflineUser.java:31)
[20:26:51 WARN]:        at net.dzikoysk.funnyguilds.util.element.PlayerListManager.send(PlayerListManager.java:49)
[20:26:51 WARN]:        at net.dzikoysk.funnyguilds.util.element.PlayerList.send(PlayerList.java:160)
[20:26:51 WARN]:        at net.dzikoysk.funnyguilds.util.element.PlayerListManager.updatePlayers(PlayerListManager.java:24)
[20:26:51 WARN]:        at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:38)
[20:26:51 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:48)
[20:26:51 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:28)
```

```
#########################################################################
                                                                               config
#########################################################################
# Czy wlaczyc dummy z punktami
dummy-enable: true
# Wyglad nazwy wyswietlanej (suffix, za punktami)
dummy-suffix: 'pkt'

# Wyglad listy graczy. Przedzial od 1 do 60
# Limit znakow: 30
# > Spis zmiennych:
# {ONLINE} - Liczba graczy online
# {PLAYER} - Gracz
# {PING} - Ping
# {TPS} - TPS
# {GUILD} - Gildia do której należy gracz
# {TAG} - Tag gildii gracza
# {POINTS} - Punkty
# {RANK} - pozycja w rankingu gracza
# {KILLS} - Zabojstwa
# {DEATHS} - Smierci
# {SECOND} - Sekunda
# {MINUTE} - Minuta
# {HOUR} - Godzina
# {PTOP-<pozycja>} - Gracz na podanym miejscu w rankingu (np. {PTOP-1}, {PTOP-60})
# {GTOP-<pozycja>} - Gildia na podanej pozycji w rankingu (np. {GTOP-1}, {PTOP-50})
# {GPOINTS} - punkty gildii
# {GRANK} - pozycja gildii w rankingu
# {SIZE} - wielkość terenu gildii
# {LIVES} - życia gildii
player-list:
# Kolumna Pierwsza:
  1: '&8----------------------'
  4: '     &4&lTop Graczy'
  7: '&8----------------------'
  10: '&71. &f{PTOP-1}'
  13: '&72. &f{PTOP-2}'
  16: '&73. &f{PTOP-3}'
  19: '&73. &f{PTOP-4}'
  22: '&74. &f{PTOP-5}'
  25: '&75. &f{PTOP-6}'
  28: '&76. &f{PTOP-7}'
  31: '&77. &f{PTOP-8}'
  34: '&78. &f{PTOP-9}'
  37: '&79. &f{PTOP-10}'
  40: '&710. &f{PTOP-11}'
  43: '&711. &f{PTOP-12}'
  46: '&712. &f{PTOP-13}'
  49: '&713. &f{PTOP-14}'
  52: '&714. &f{PTOP-15}'
  55: '&8----------------------'
  58: '&f&fLessCraft.myts.pw'

  
# Kolumna Druga 
  2: '&8----------------------'
  5: '     &4&lLessCraft'
  8: '&8----------------------'
  11: '&7Nick: &f{PLAYER}'
  14: '&7Punkty: &f{POINTS}'
  17: '&7Zabojstwa: &f{KILLS}'
  20: '&7Zgony: &f{DEATHS}'
  23: ''
  26: '&7Online: &f{ONLINE}'
  29: '&7Godzina: &f{HOUR}:{MINUTE}'
  32: '&8-----------------'
  35: ' &4&lTwoja Gildia'
  38: '&8-----------------'
  41: '&7Tag: &f{TAG}'
  44: '&7Punkty: &f{GPOINTS}'
  47: '&7Zabojstwa: &f{GKILLS}'
  50: '&7Zgony: &f{GDEATHS}'
  53: '&7Zycia: &f{LIVES}'
  56: '&8----------------------'
  59: '&cYT: &fSittles'
# Kolumna Trzecia
  3: '&8---------------'
  6: '     &4&lTop Gildii'
  9: '&8---------------'
  12: '&71. {GTOP-1}'
  15: '&71. {GTOP-2}'
  18: '&72. {GTOP-3}'
  21: '&73. {GTOP-4}'
  24: '&74. {GTOP-5}'
  27: '&75. {GTOP-6}'
  30: '&76. {GTOP-7}'
  33: '&77. {GTOP-8}'
  36: '&78. {GTOP-9}'
  39: '&79. {GTOP-10}'
  42: '&710. {GTOP-11}'
  45: '&711. {GTOP-12}'
  48: '&712. {GTOP-13}'
  51: '&713. {GTOP-14}'
  54: '&714. {GTOP-15}'
  57: '&8---------------'
  60: '&cSklep: &fBRAK'

# Tablista wlaczona
player-list-enable: true
# Co ile sekund ma odswiezac liste graczy
player-list-interval: 1
# Ping wyswietlany na tab
player-list-ping: 0
# Jezeli buguje Ci sie tablista
# - Po wejsciu gracza wszystko sie rozjezdza
# Wlacz ta opcje
player-list-patch: false
# Wyglad punktow wyswietlanych przy gildii w rankingu
```

**Comment by dzikoysk** [comment]
Masz serwer pod 1.8, a fg obecnie wspiera jedynie 1.7
