### ISSUE TITLE
Ranking nie działa

### ISSUE THREAD

**Issue by Shargann** [FunnyGuilds/FunnyGuilds#426]
Po update do 3.9.9.11 nie działa ranking graczy, log z konsoli:
```
[14:57:58] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to FunnyGuilds v3.9.9.11 Cleaned
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:397) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityPlayer.die(EntityPlayer.java:386) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:745) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityHuman.damageEntity(EntityHuman.java:765) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityPlayer.damageEntity(EntityPlayer.java:465) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:950) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1204) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:37) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(PacketPlayInUseEntity.java:49) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.util.hook.WorldGuardHook.isOnNonPointsRegion(WorldGuardHook.java:19) ~[?:?]
	at net.dzikoysk.funnyguilds.listener.PlayerDeath.onDeath(PlayerDeath.java:35) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	... 19 more
```
Wersja spigota:
[15:02:40 INFO]: This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by ProgrammingWizzard** [comment]
@Shargann wgrałeś najnowszego hotfixa?

**Comment by Shargann** [comment]
Tak, pobierałem wersję z -fix1

**Comment by kacperduras** [comment]
Dobra, leci do naprawy. Postaram się jeszcze fixa wypuścić dzisiaj ;)
