### ISSUE TITLE
Ranking nie działa, raz jeszcze

### ISSUE THREAD

**Issue by Shargann** [FunnyGuilds/FunnyGuilds#428]
3.9.9.12, to samo co przedtem :(
```
[16:06:31] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to FunnyGuilds v3.9.9.12 Cleaned
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:397) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityPlayer.die(EntityPlayer.java:386) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:745) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityHuman.damageEntity(EntityHuman.java:765) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityPlayer.damageEntity(EntityPlayer.java:465) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:950) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1204) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:37) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(PacketPlayInUseEntity.java:49) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.util.hook.WorldGuardHook.isOnNonPointsRegion(WorldGuardHook.java:22) ~[?:?]
	at net.dzikoysk.funnyguilds.listener.PlayerDeath.onDeath(PlayerDeath.java:35) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	... 19 more
```

**Comment by kacperduras** [comment]
Dobra, zadam pytanie pro-forma. Czy posiadasz zaktualizowane WG do najnowszej wersji?

**Comment by Shargann** [comment]
WG 6.1, ostatnie co oficjalnie jest wspierane w 1.7.x. WG 6.1.2 ma "This version supports Minecraft 1.9 through 1.10, and should be backwards compatible with 1.8 and 1.7." tylko że nie wiem czy chcemy ryzykować że WG zdechnie. WG 6.2 też ma podobnie.

**Comment by kacperduras** [comment]
@Shargann mam prawdopodobne rozwiązanie problemu, już wypuszczam hot-fixa ;)

**Comment by kacperduras** [comment]
@Shargann pobierz teraz, link ten sam ;)

**Comment by kacperduras** [comment]
@Shargann i jak, działa?

**Comment by Shargann** [comment]
Nope, ```
[16:31:52] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to FunnyGuilds v3.9.9.12 Cleaned
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:397) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityPlayer.die(EntityPlayer.java:386) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:745) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityHuman.damageEntity(EntityHuman.java:765) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityPlayer.damageEntity(EntityPlayer.java:465) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:950) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1204) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:37) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(PacketPlayInUseEntity.java:49) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.util.hook.WorldGuardHook.isOnNonPointsRegion(WorldGuardHook.java:22) ~[?:?]
	at net.dzikoysk.funnyguilds.listener.PlayerDeath.onDeath(PlayerDeath.java:35) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[silnik.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	... 19 more
```
Ostatecznie mogę próbować tego najnowszego WG, tylko tak jak mówiłem, ten support nie do końca jest oficjalny na 1.7.x.

**Comment by kacperduras** [comment]
Spróbuj, bo ja już szczerze powiedziawszy nie mam pomysłów.

**Comment by kacperduras** [comment]
U mnie wszystko działa jak należy, z WG i bez.

**Comment by kacperduras** [comment]
@Shargann dobra, mój błąd. Już wrzucam prawidłową wersję na serwer :V
Wybacz, za problemy. Coś dzisiaj jest ze mną nie tak xD

**Comment by kacperduras** [comment]
@Shargann wrzucone, po ciężkich męczarniach, ale wrzucone. Sprawdź ;)

**Comment by kacperduras** [comment]
Okej, powodzenia życzę ;)

**Comment by dzikoysk** [comment]
Brak odpowiedzi ze strony OP, zamykam
