### ISSUE TITLE
Jakiś error w konsolce 

### ISSUE THREAD

**Issue by Patrys003** [FunnyGuilds/FunnyGuilds#430]
```
[17:32:48] [Server thread/INFO]: [FunnyGuilds] Loading FunnyGuilds v3.9.9.12 Cleaned-110a992
[17:32:49] [Server thread/ERROR]: IO exception when creating config file: /home/e119853/pliki/plugins/FunnyGuilds/config.yml initializing FunnyGuilds v3.9.9.12 Cleaned-110a992 (Is it up to date?)
java.lang.RuntimeException: IO exception when creating config file: /home/e119853/pliki/plugins/FunnyGuilds/config.yml
	at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.<init>(Settings.java:15) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.getConfig(Settings.java:21) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374) [mc.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:169) [mc.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494) [mc.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [mc.jar:git-PaperSpigot-1f7d532]
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_91]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_91]
	at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:25) ~[?:?]
	... 7 more
```

**Comment by Patrys003** [comment]
@Reff

**Comment by kacperduras** [comment]
Widać, że nawyki z mpcforum ( ͡° ͜ʖ ͡°)
W PR #431 naprawiłem ten błąd, tylko czeka na zaakceptowanie.
Musisz czekać cierpliwie.

**Comment by TheMolkaPL** [comment]
Naprawione w 7a4d9a0ae4f65830eacf03f55ac0718f334c8a1e - będzie to dopiero widoczne w najbliższej wersji.
