### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by xPiwkoPL** [FunnyGuilds/FunnyGuilds#432]
[18:27:26 ERROR]: Could not load 'plugins/funnyguilds-3.9.9.12.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/dzikoysk/funnyguilds/FunnyGuilds : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:313) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:236) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugins(CraftServer.java:350) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.<init>(CraftServer.java:312) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.PlayerList.<init>(PlayerList.java:63) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:126) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
Caused by: java.lang.UnsupportedClassVersionError: net/dzikoysk/funnyguilds/FunnyGuilds : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_80]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_80]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_80]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_80]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_80]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	... 9 more

**Comment by MrGregorix** [comment]
FG wspiera tylko Jave 8 i wyżej

**Comment by xPiwkoPL** [comment]
aaa
czyli przestawic serwer na java 8?

**Comment by xPiwkoPL** [comment]
teraz wykrywa mi plugin i normalnie jest pod /plugins ale nie dzialaja komendy ani folder sie nie tworzy

[18:53:23 INFO]: [FunnyGuilds] Loading FunnyGuilds v3.9.9.12 Cleaned-110a992
[18:53:24 ERROR]: IO exception when creating config file: /home/servers/558198/plugins/FunnyGuilds/config.yml initializing FunnyGuilds v3.9.9.12 Cleaned-110a992 (Is it up to date?)
java.lang.RuntimeException: IO exception when creating config file: /home/servers/558198/plugins/FunnyGuilds/config.yml
	at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.<init>(Settings.java:15) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.getConfig(Settings.java:21) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugins(CraftServer.java:355) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.<init>(CraftServer.java:312) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.PlayerList.<init>(PlayerList.java:63) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:126) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_91]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_91]
	at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:25) ~[?:?]
	... 10 more
[18:53:24 INFO]: [AutoSaveWorld] Enabling AutoSaveWorld v4.7
[18:53:24 INFO]: [AutoSaveWorld] AutoSaveThread Started: Interval is 300 seconds
[18:53:24 INFO]: [AutoSaveWorld] AutoBackupThread Started: Interval is 216000 seconds
[18:53:24 INFO]: [AutoSaveWorld] AutoPurgeThread Started: Interval is 86400 seconds
[18:53:24 INFO]: [AutoSaveWorld] CrashRestartThread started
[18:53:24 INFO]: [AutoSaveWorld] AutoRestartThread started
[18:53:24 INFO]: [AutoSaveWorld] Version 4.7 is enabled
[18:53:24 INFO]: [AutoSaveWorld] AutoConsoleCommandThread Started
[18:53:24 INFO]: [Vault] Enabling Vault v1.2.25-b320
[18:53:24 INFO]: [Vault][Economy] Essentials Economy found: Waiting
[18:53:24 INFO]: [Vault][Permission] PermissionsEx found: Waiting
[18:53:24 INFO]: [Vault][Permission] SuperPermissions loaded as backup permission system.
[18:53:24 INFO]: [Vault][Chat] PermissionsEx found: Waiting
[18:53:24 INFO]: [Vault] Enabled Version 1.2.25-b320
[18:53:24 INFO]: [Vault][Economy] Essentials Economy hooked.
[18:53:24 INFO]: [Vault][Permission] PermissionsEx hooked.
[18:53:24 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[18:53:24 WARN]: The server will make no attempt to authenticate usernames. Beware.
[18:53:24 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[18:53:24 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[18:53:24 INFO]: Preparing level "Bezfrajernik5"
[18:53:24 INFO]: Preparing start region for level 0 (Seed: -2101265071795412393)
[18:53:23 ERROR]: Could not load 'plugins/BasicEssentials.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `me.opverify.opverify'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:42) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:313) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:236) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugins(CraftServer.java:350) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.<init>(CraftServer.java:312) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.PlayerList.<init>(PlayerList.java:63) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:126) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
Caused by: java.lang.ClassNotFoundException: me.opverify.opverify
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	... 10 more
[18:53:23 INFO]: [PermissionsEx] sql backend registered!
[18:53:23 INFO]: [PermissionsEx] file backend registered!
[18:53:23 WARN]: Exception in thread "Thread-8" 
[18:53:23 WARN]: org.bukkit.craftbukkit.libs.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 7
[18:53:23 WARN]: at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
[18:53:23 WARN]: at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:755)
[18:53:23 WARN]: at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:694)
[18:53:23 WARN]: at org.bukkit.craftbukkit.v1_7_R1.updater.BukkitDLUpdaterService.fetchArtifact(BukkitDLUpdaterService.java:53)
[18:53:23 WARN]: at org.bukkit.craftbukkit.v1_7_R1.updater.BukkitDLUpdaterService.getArtifact(BukkitDLUpdaterService.java:30)
[18:53:23 WARN]: at org.bukkit.craftbukkit.v1_7_R1.updater.AutoUpdater$1.run(AutoUpdater.java:77)
[18:53:23 WARN]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 7
[18:53:23 WARN]: at org.bukkit.craftbukkit.libs.com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
[18:53:23 WARN]: at org.bukkit.craftbukkit.libs.com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
[18:53:23 WARN]: at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
[18:53:23 WARN]: ... 5 more
[18:53:23 INFO]: [AutoSaveWorld] Loading AutoSaveWorld v4.7
[18:53:23 INFO]: [NoCheatPlus] Loading NoCheatPlus v3.9.4-DEV-b554
[18:53:23 INFO]: [Essentials] Loading Essentials vDev2.12.4
[18:53:23 INFO]: [EssentialsChat] Loading EssentialsChat vDev2.12.4
[18:53:23 INFO]: [PermissionsEx] Loading PermissionsEx v1.20.2
[18:53:23 INFO]: [PermissionsEx] Initializing file backend
[18:53:23 INFO]: Permissions file successfully reloaded
[18:53:23 INFO]: [AutoMessage] Loading AutoMessage v2.3.3
[18:53:23 INFO]: [BuycraftX] Loading BuycraftX v10.2
[18:53:23 INFO]: [Vault] Loading Vault v1.2.25-b320
[18:53:23 INFO]: [EssentialsSpawn] Loading EssentialsSpawn vDev2.12.4
[18:53:23 INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5-b670
[18:53:23 INFO]: [AZRank] Loading AZRank v1.3.b4
[18:53:23 INFO]: [EssentialsProtect] Loading EssentialsProtect vPre2.11.1.2
[18:53:23 INFO]: [AuthMe] Loading AuthMe v2.8
[18:53:23 INFO]: [Multiverse-Portals] Loading Multiverse-Portals v2.5-b696
[18:53:23 INFO]: [WorldEdit] Loading WorldEdit v6.1.7;dd00bb1
[18:53:23 INFO]: [WorldGuard] Loading WorldGuard v880-60c3ed4
[18:53:23 INFO]: [OtherDrops] Loading OtherDrops v2.8b.573
[18:53:23 INFO]: [FunnyGuilds] Loading FunnyGuilds v3.9.9.12 Cleaned-110a992
[18:53:24 ERROR]: IO exception when creating config file: /home/servers/558198/plugins/FunnyGuilds/config.yml initializing FunnyGuilds v3.9.9.12 Cleaned-110a992 (Is it up to date?)
java.lang.RuntimeException: IO exception when creating config file: /home/servers/558198/plugins/FunnyGuilds/config.yml
	at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.<init>(Settings.java:15) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.getConfig(Settings.java:21) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugins(CraftServer.java:355) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.<init>(CraftServer.java:312) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.PlayerList.<init>(PlayerList.java:63) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:126) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit-beta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_91]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_91]
	at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:25) ~[?:?]
	... 10 more

**Comment by MrGregorix** [comment]
To bug w aktualnej wersji, wystarczy stworzyc folder FunnyGuilds w plugins

**Comment by TheMolkaPL** [comment]
Bug z tworzeniem domyślnych plików został naprawiony w 7a4d9a0ae4f65830eacf03f55ac0718f334c8a1e. Będzie to dopiero widoczne w najbliższej wersji.
