### ISSUE TITLE
Tworzenie plików na PaperSpigot 1.7.10 R0.1

### ISSUE THREAD

**Issue by szymex73** [FunnyGuilds/FunnyGuilds#471]
Error z konsoli (info o reszcie pluginów wycięte):
```[20:15:50 INFO]: Format wersji Bukkita jest zmieniony. Wersja nie jest sprawdzana.
[20:15:50 INFO]: git-PaperSpigot-1f7d532 (MC: 1.7.10)
[20:15:50 INFO]: 1.7.10-R0.1-SNAPSHOT
[20:15:50 INFO]: Essentials: Using config file enhanced permissions.
[20:15:50 INFO]: Permissions listed in as player-commands will be given to all users.
[20:15:50 INFO]: [FunnyGuilds] Enabling FunnyGuilds v3.9.9.12 Cleaned-110a992
[20:15:50 INFO]: [FunnyGuilds] Available Processors: 2
[20:15:50 INFO]: [FunnyGuilds] Active Threads: 18
[20:15:50 ERROR]: Error occurred while enabling FunnyGuilds v3.9.9.12 Cleaned-110a992 (Is it up to date?)
java.lang.RuntimeException: IO exception when creating config file: /home/szymex/moje/mc/srvTest/plugins/FunnyGuilds/messages.yml
	at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Messages.<init>(Messages.java:18) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Messages.getInstance(Messages.java:39) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Manager.<init>(Manager.java:22) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:58) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[server.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [server.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [server.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [server.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:867) [server.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.Bukkit.reload(Bukkit.java:301) [server.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [server.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [server.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:765) [server.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:751) [server.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:344) [server.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:308) [server.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [server.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [server.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:git-PaperSpigot-1f7d532]
Caused by: java.io.IOException: Nie ma takiego pliku ani katalogu
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_131]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_131]
	at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:25) ~[?:?]
	... 20 more
```

**Comment by TheMolkaPL** [comment]
Stwórz folder `FunnyGuilds` w folderze `plugins`.

**Comment by TheMolkaPL** [comment]
Błąd został właśnie naprawiony w 7a4d9a0ae4f65830eacf03f55ac0718f334c8a1e - będzie widoczny dopiero w najbliższej wersji pluginu.
