### ISSUE TITLE
Błędy przy tworzeniu gildii na 1.8

### ISSUE THREAD

**Issue by InformatykPL** [FunnyGuilds/FunnyGuilds#511]
Po wpisaniu komendy /zaloz tworzy się gildia, ale widoczny jest błąd **"An internal error has occured"**, a w konsoli:
**Caused by: java.lang.NoClassDefFoundError: net/minecraft/util/com/mojang/authlib/GameProfile
        at net.dzikoysk.funnyguilds.basic.OfflineUser.init(OfflineUser.java:66) ~[?:?]
        at net.dzikoysk.funnyguilds.basic.OfflineUser.<init>(OfflineUser.java:31) ~[?:?]
        at net.dzikoysk.funnyguilds.basic.User.getOfflineUser(User.java:288) ~[?:?]
        at net.dzikoysk.funnyguilds.command.ExcCreate.execute(ExcCreate.java:222) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:97) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:122) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:21) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[jedenosiem.jar:git-Spigot-db6de12-18fbb24]**

**Comment by kacperduras** [comment]
Najprawdopodobniej zła wersja serwera, obecnie oficjalnie FG wspiera tylko i wyłącznie wersje 1.7.x.

Podaj wersję pluginu.
