### ISSUE TITLE
Błędy w konsoli

### ISSUE THREAD

**Issue by krzukosz** [FunnyGuilds/FunnyGuilds#512]
Dziwne błędy w konsoli przy wchodzeniu każdego gracza
`[10:20:21] [Thread-9/INFO]: UUID of player krzukosz is 60ad5db1-91c6-3781-8a57-8774fd2c7f8d
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: Exception in thread "FunnyGuilds | IndependentThread" 
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/util/com/mojang/authlib/GameProfile
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.basic.OfflineUser.init(OfflineUser.java:66)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.basic.OfflineUser.<init>(OfflineUser.java:31)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.basic.User.getOfflineUser(User.java:288)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.Dummy.initialize(Dummy.java:51)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.Dummy.<init>(Dummy.java:20)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.basic.User.getDummy(User.java:226)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.DummyManager.updateScore(DummyManager.java:17)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:53)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:49)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:29)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.util.com.mojang.authlib.GameProfile
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:20:21] [FunnyGuilds | IndependentThread/WARN]: 	... 10 more
[10:20:21] [Server thread/INFO]: krzukosz[/188.******:61475] logged in with entity id 253 at ([world]12.443241830610464, 77.0, 332.32945092407766)
[10:20:23] [Craft Scheduler Thread - 3/WARN]: Exception in thread "Craft Scheduler Thread - 3" 
[10:20:23] [Craft Scheduler Thread - 3/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v3.9.9.14 Cleaned-4fe93a7 generated an exception while executing task 23
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/util/io/netty/channel/ChannelHandler
	at net.dzikoysk.funnyguilds.listener.PlayerJoin.lambda$onJoin$0(PlayerJoin.java:36)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.ChannelHandler
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more`

**Comment by krzukosz** [comment]
https://hastebin.com/lenexoyadu.md

**Comment by kacperduras** [comment]
Zobacz #511

**Comment by krzukosz** [comment]
A jest jakaś nieoficialna wersja 1.8?

**Comment by kacperduras** [comment]
@krzukosz [Tutaj](https://github.com/TheMolkaPL/FunnyGuilds), jednak jest trochę nieaktualna względem obecnego kodu, natomiast działa na wersjach 1.8+.
