### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by SzymoonDev** [FunnyGuilds/FunnyGuilds#524]
Przy próbie zniszczenia bądź zmiany ramki na item, pojawia się poniższy błąd w konsoli.
[11:05:30 WARN]: java.lang.NullPointerException
[11:05:30 WARN]:        at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:51)
[11:05:30 WARN]:        at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:86)
[11:05:30 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:49)
[11:05:30 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:29)

**Comment by SzymoonDev** [comment]
Przy jakiejkolwiek interakcji (gracz, mob, zwierzę) pojawia się ciągły spam w konsoli.
[11:13:20 WARN]: java.lang.NullPointerException

**Comment by kacperduras** [comment]
@SzymoonDev 1 problem = 1 issue.
