### ISSUE TITLE
Niesprawny "TAB"

### ISSUE THREAD

**Issue by Przemo12** [FunnyGuilds/FunnyGuilds#526]
Witam, niestety na nowej wersji 3.9.9.15 nie działa TAB, oto błąd z konsoli
.`[15:15:39] [Server thread/ERROR]: Error occurred while enabling FunnyGuilds v3.9.9.15 Cleaned-fce99e1 (Is it up to date?)
java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1456) ~[?:1.8.0_131]
	at java.util.Collections.sort(Collections.java:141) ~[?:1.8.0_131]
	at net.dzikoysk.funnyguilds.basic.util.RankManager.update(RankManager.java:43) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.util.RankManager.update(RankManager.java:29) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.User.getRank(User.java:236) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.Rank.getPoints(Rank.java:101) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.Rank.compareTo(Rank.java:56) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.Rank.compareTo(Rank.java:6) ~[?:?]
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320) ~[?:1.8.0_131]
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188) ~[?:1.8.0_131]
	at java.util.Arrays.sort(Arrays.java:1312) ~[?:1.8.0_131]
	at java.util.Arrays.sort(Arrays.java:1506) ~[?:1.8.0_131]
	at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_131]
	at java.util.Collections.sort(Collections.java:141) ~[?:1.8.0_131]
	at net.dzikoysk.funnyguilds.basic.util.RankManager.update(RankManager.java:43) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.util.RankManager.update(RankManager.java:29) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.User.getRank(User.java:236) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.Rank.getPoints(Rank.java:101) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.Rank.compareTo(Rank.java:56) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.Rank.compareTo(Rank.java:6) ~[?:?]
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320) ~[?:1.8.0_131]
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188) ~[?:1.8.0_131]
	at java.util.Arrays.sort(Arrays.java:1312) ~[?:1.8.0_131]
	at java.util.Arrays.sort(Arrays.java:1506) ~[?:1.8.0_131]
	at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_131]
	at java.util.Collections.sort(Collections.java:141) ~[?:1.8.0_131]
	at net.dzikoysk.funnyguilds.basic.util.RankManager.update(RankManager.java:43) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.Guild.updateRank(Guild.java:144) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.Guild.addMember(Guild.java:61) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.Guild.setOwner(Guild.java:178) ~[?:?]
	at net.dzikoysk.funnyguilds.data.util.DeserializationUtils.deserializeGuild(DeserializationUtils.java:23) ~[?:?]
	at net.dzikoysk.funnyguilds.data.flat.FlatGuild.deserialize(FlatGuild.java:194) ~[?:?]
	at net.dzikoysk.funnyguilds.data.flat.Flat.loadGuilds(Flat.java:144) ~[?:?]
	at net.dzikoysk.funnyguilds.data.flat.Flat.load(Flat.java:30) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Manager.<init>(Manager.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:63) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
`

**Comment by kacperduras** [comment]
Będzie naprawione w 4.0 ;)

**Comment by Przemo12** [comment]
Sory, po usunięciu configu oraz messages ze starej wersji, działa wszystko okej na ten moment. Mój błąd przepraszam jeszcze raz.
