### ISSUE TITLE
messages.yml - błąd

### ISSUE THREAD

**Issue by SzymoonDev** [FunnyGuilds/FunnyGuilds#527]
Podczas zmiany jakiejkolwiek wiadomości w pliku messages.yml, plugin usuwa znaki "", a następie pokazuje błąd w konsoli.

Zamieniam sekcje:
_# <------- Permission Messages -------> #
permission: "&cNie masz wystarczajacych uprawnien do uzycia tej komendy!"
blockedWorld: "&cZarzadzanie gildiami jest zablokowane na tym swiecie!"_
na:
_# <------- Permission Messages -------> #
permission: " &8» &cNie masz uprawnien. &8(&7funnyguilds.admin&8)"
blockedWorld: " &8» &cZarzadzanie gildiami jest zablokowane na tym swiecie."_

Koduję plik w UTF-8, plugin pomyślnie ładuje plik, lecz usuwa z niego znaki "":
_# <------- Permission Messages -------> #
permission:  &8» &cNie masz uprawnien. &8(&7funnyguilds.admin&8)
blockedWorld:  &8» &cZarzadzanie gildiami jest zablokowane na tym swiecie._

Nie mam pojęcia z czego to wynika. Wrzucę jeszcze błąd z konsoli:
_>funnyguilds reload
[19:05:29 INFO]: Przeladowywanie...
[19:05:29 WARN]: Exception in thread "Thread-12"
[19:05:29 WARN]: while scanning an anchor
 in 'reader', line 3, column 14:
    permission:  &8? &cNie masz uprawnien. &8(&7f ...
                 ^
expected alphabetic or numeric character, but found ?(187)
 in 'reader', line 3, column 16:
    permission:  &8? &cNie masz uprawnien. &8(&7fun ...
                   ^

[19:05:29 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1446)
[19:05:29 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchAnchor(ScannerImpl.java:939)
[19:05:29 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:370)
[19:05:29 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
[19:05:29 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586)
[19:05:29 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[19:05:29 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
[19:05:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:132)
[19:05:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
[19:05:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
[19:05:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
[19:05:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[19:05:29 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
[19:05:29 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
[19:05:29 WARN]:        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:441)
[19:05:29 WARN]:        at org.diorite.cfg.system.BaseTemplate.load(BaseTemplate.java:267)
[19:05:29 WARN]:        at org.diorite.cfg.system.Template.load(Template.java:166)
[19:05:29 WARN]:        at org.diorite.cfg.system.Template.load(Template.java:182)
[19:05:29 WARN]:        at org.diorite.cfg.system.Template.load(Template.java:197)
[19:05:29 WARN]:        at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:33)
[19:05:29 WARN]:        at net.dzikoysk.funnyguilds.data.Messages.<init>(Messages.java:18)
[19:05:29 WARN]:        at net.dzikoysk.funnyguilds.command.ExcFunnyGuilds$1.run(ExcFunnyGuilds.java:32)_

**Comment by insertt** [comment]
Aktualnym workaroundem jest usunięcie spacji na początku, jak będę miał czas to poprawie parsowanie w configach.

**Comment by kacperduras** [comment]
Naprawione w 6f27458c480562a1a22ddf1bc450eba5e13781e2 dzięki pomocy @insertt ;)
