### ISSUE TITLE
Komenda "/ga" - błąd ConsoleSender 

### ISSUE THREAD

**Issue by SzymoonDev** [FunnyGuilds/FunnyGuilds#528]
Przy użyciu komendy /ga w konsoli, pokazuje się błąd:
>ga
[21:41:55 WARN]: Unexpected exception while parsing console command "ga"
org.bukkit.command.CommandException: Unhandled exception executing 'ga' in net.dzikoysk.funnyguilds.command.util.Performer(ga)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[Spigot-1.7.10.jar:git-PaperSpigot-38]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:766) ~[Spigot-1.7.10.jar:git-PaperSpigot-38]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:752) [Spigot-1.7.10.jar:git-PaperSpigot-38]
        at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:344) [Spigot-1.7.10.jar:git-PaperSpigot-38]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:308) [Spigot-1.7.10.jar:git-PaperSpigot-38]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [Spigot-1.7.10.jar:git-PaperSpigot-38]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [Spigot-1.7.10.jar:git-PaperSpigot-38]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Spigot-1.7.10.jar:git-PaperSpigot-38]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_7_R4.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
        at net.dzikoysk.funnyguilds.command.admin.AxcMain.execute(AxcMain.java:18) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:97) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:122) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:21) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[Spigot-1.7.10.jar:git-PaperSpigot-38]
        ... 7 more

Szybkie i proste do naprawy, =)

**Comment by MrGregorix** [comment]
To nie używaj /ga w konsoli ¯\_(ツ)_/¯

**Comment by kacperduras** [comment]
@SzymoonDev jak takie proste do naprawy, to czemu na dasz PR'a?
