### ISSUE TITLE
Blad z podbijaniem krysztalu

### ISSUE THREAD

**Issue by sokrates1231** [FunnyGuilds/FunnyGuilds#534]
blad:
[FunnyGuilds | IndependentThread/WARN]: java.lang.NullPointerException
[FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:51)
[FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:86)
 [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:49)
[FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:29)

**Comment by sokrates1231** [comment]
Czasami go nawet nie widac...

**Comment by kacperduras** [comment]
A może jakieś szczegóły, apropo specyfikacji serwera i samego pluginu? Kryształowe kule obecnie w serwisie.

**Comment by sokrates1231** [comment]
Wersja najnowsza: http://screenshot.sh/oAHgs2AypwpiX
silnik: 1.7.2-1.8.9
Czasami po restarcie lub stworzeniu gildii nie tworzy sie KRYSZTAL, a jesli nawet tworzy sie to klikajac nie widze informacji gildii lub o ataku... i wywala te bledy w konsoli ;p

**Comment by kacperduras** [comment]
Sam błąd z tym NPE został naprawiony (0d04df56e8a0e33a7b832724c74e5f9a4f4ceabd), tak samo z kryształami (66f68ebdcf9a87caf033f40a2c9f996fea9026d1), jednak dopiero on będzie zaimplementowany w 4.0, które ma być tylko i wyłącznie na wersje 1.8+. Na wcześniejszych wersjach takowe problemy się nie pojawiały?

**Comment by sokrates1231** [comment]
Wlasnie chce odpalic nowa edycje..., a tu taki myk z bledem.. podobno na tej wersji poprawili ten blad: http://screenshot.sh/mG1kT1wfB2YXx

**Comment by kacperduras** [comment]
`Na wcześniejszych wersjach takowe problemy się nie pojawiały?`

**Comment by sokrates1231** [comment]
ost. uzywalem 3.9.9.7 xD, i wgl serca nie bylo XD

**Comment by kacperduras** [comment]
Dobra, najprawdopodobniej winowajcą jest commit 227931bcb24db9351c660326d6ab0c16845bf240 od @Xierip (brawo!), który został naprawiony w 66f68ebdcf9a87caf033f40a2c9f996fea9026d1 (też przez @Xierip ). Ostatnia wersja na której była zgłaszania najmniejsza ilość błędów to 3.9.9.12. Na ten moment mogę zalecić Ci tylko downgrade do tej wersji, innego pomysłu na dzień dzisiejszy nie mam.

**Comment by sokrates1231** [comment]
ta testowalem 3.9.9.14, i teraz 12 i wgl: 
[15:20:24] [Server thread/INFO]: [FunnyGuilds] Loading FunnyGuilds v3.9.9.12 Cleaned-110a992
[15:20:24] [Server thread/ERROR]: IO exception when creating config file: /home/xtop/megadrop/plugins/FunnyGuilds/config.yml initializing FunnyGuilds v3.9.9.12 Cleaned-110a992 (Is it up to date?)
java.lang.RuntimeException: IO exception when creating config file: /home/xtop/megadrop/plugins/FunnyGuilds/config.yml
	at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.<init>(Settings.java:15) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.getConfig(Settings.java:21) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374) [craftbukkit.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:169) [craftbukkit.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494) [craftbukkit.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-PaperSpigot-1f7d532]
Caused by: java.io.IOException: Nie ma takiego pliku ani katalogu
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_72]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_72]
	at net.dzikoysk.funnyguilds.util.ConfigUtils.loadConfig(ConfigUtils.java:25) ~[?:?]
	... 7 more 

XDD

**Comment by kacperduras** [comment]
To już akurat nie wina pluginu, wtedy ten błąd został przeze mnie załatany i działa tak jak trzeba.

**Comment by sokrates1231** [comment]
Nie tworzy folderu.

**Comment by kacperduras** [comment]
To utwórz go ręcznie, najwyraźniej coś z chmod'ami jest nie tak.

**Comment by Xierip** [comment]
@kacperduras Zaraz popatrze co tam mogło polecieć :/

**Comment by sokrates1231** [comment]
ok 3.9.9.12 dziala, co moze nie dzialac? Czego mam sie obawiac?

**Comment by kacperduras** [comment]
Naprawione w 4.0.0.0
