### ISSUE TITLE
Warn w najnowszej wersji

### ISSUE THREAD

**Issue by ScoreBoardDEV** [FunnyGuilds/FunnyGuilds#539]
`[22:22:50] [Craft Scheduler Thread - 996/INFO]: [FunnyGuilds][Updater] > 
[22:22:50] [Craft Scheduler Thread - 996/INFO]: [FunnyGuilds][Updater] > A new version of FunnyGuilds is available!
[22:22:50] [Craft Scheduler Thread - 996/INFO]: [FunnyGuilds][Updater] > Current: 3.9.9.15 Cleaned-fce99e1
[22:22:50] [Craft Scheduler Thread - 996/INFO]: [FunnyGuilds][Updater] > Latest: 3.9.9.15 Cleaned
[22:22:50] [Craft Scheduler Thread - 996/INFO]: [FunnyGuilds][Updater] > 
[22:23:10] [FunnyGuilds | IndependentThread/WARN]: java.lang.NullPointerException
[22:23:10] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:37)
[22:23:10] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:86)
[22:23:10] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:49)
[22:23:10] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:29)
[22:23:10] [FunnyGuilds | IndependentThread/WARN]: java.lang.NullPointerException
[22:23:10] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:51)
[22:23:10] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:86)
[22:23:10] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:49)
[22:23:10] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:29)
[22:23:15] [FunnyGuilds | IndependentThread/WARN]: java.lang.NullPointerException
[22:23:15] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:51)
[22:23:15] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:86)
[22:23:15] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:49)
[22:23:15] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:29)
[22:23:17] [FunnyGuilds | IndependentThread/WARN]: java.lang.NullPointerException
[22:23:17] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:51)
[22:23:17] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:86)
[22:23:17] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:49)
[22:23:17] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:29)`

**Comment by kacperduras** [comment]
#525
