### ISSUE TITLE
Błąd w pluginie

### ISSUE THREAD

**Issue by Patryk003** [FunnyGuilds/FunnyGuilds#543]
``[16:31:13 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v3.9.9.15 Cleaned-fce99e1 generated an exception while executing task 102
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/util/io/netty/channel/ChannelHandler
        at net.dzikoysk.funnyguilds.listener.PlayerJoin.lambda$onJoin$0(PlayerJoin.java:36)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.ChannelHandler
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more
```

**Comment by kacperduras** [comment]
```
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.ChannelHandler
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 6 more
```

Oficjalna, **stabilna** wersja pluginu na dzień dzisiejszy wspiera tylko wersje 1.7.X. W celu użycia FG na nowszej wersji, zaleca się użycie [tego](https://github.com/TheMolkaPL/FunnyGuilds) forka ;)
