### ISSUE TITLE
blad updatera pluginu

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#556]
Błąd:

`[00:07:55 WARN]: java.net.ConnectException: Connection timed out
[00:07:55 WARN]:at java.net.PlainSocketImpl.socketConnect(Native Method)
[00:07:55 WARN]:at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[00:07:55 WARN]:at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[00:07:55 WARN]:at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[00:07:55 WARN]:at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[00:07:55 WARN]:at java.net.Socket.connect(Socket.java:589)
[00:07:55 WARN]:at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[00:07:55 WARN]:at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[00:07:55 WARN]:at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[00:07:55 WARN]:at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[00:07:55 WARN]:at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[00:07:55 WARN]:at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[00:07:55 WARN]:at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[00:07:55 WARN]:at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[00:07:55 WARN]:at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
[00:07:55 WARN]:at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
[00:07:55 WARN]:at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[00:07:55 WARN]:at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
[00:07:55 WARN]:at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
[00:07:55 WARN]:at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[00:07:55 WARN]:at net.dzikoysk.funnyguilds.util.IOUtils.getContent(IOUtils.java:37)
[00:07:55 WARN]:at net.dzikoysk.funnyguilds.FunnyGuilds.lambda$update$0(FunnyGuilds.java:191)
[00:07:55 WARN]:at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[00:07:55 WARN]:at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[00:07:55 WARN]:at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:07:55 WARN]:at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:07:55 WARN]:at java.lang.Thread.run(Thread.java:745)
[00:07:55 INFO]: [FunnyGuilds][Updater] > Failed to check the newest version of FunnyGuilds..`

**Comment by kacperduras** [comment]
Naprawione w 091d062be9c3a2ad5bf1cc8129ef3d151844eba9

**Comment by MrGregorix** [comment]
Wcale że nie

**Comment by MrGregorix** [comment]
Co nie zmienia faktu że to błąd połączenia z serwerem, albo nie masz internetu albo coś blokuje ci ruch.

**Comment by kacperduras** [comment]
Też jest taka hipoteza, spróbuje jakoś ten błąd odtworzyć.

**Comment by MrGregorix** [comment]
Wystarczy wylać szklanke wody na routeri  odpalić FG. Błąd odtworzony.

**Comment by kacperduras** [comment]
Potwierdzam, na szybko zabrałem sobie dostęp do łącza i odpaliłem serwer testowy na localu - ten sam błąd. Winowajcą jest Twój serwer, który jakimś cudem blokuje połączenie na zewnątrz.

**Comment by MentosPL** [comment]
Poprzednie wersje FG (3.9.9.15 i wcześniej) bez problemowo się łączyły i sprawdzały wersję.

**Comment by kacperduras** [comment]
Bo serwer trzymający plik znajdował się na dzikoysk.net, od 4.0.0.1 przerzuciliśmy na github.com.
Jak pisałem - ten sam błąd się pojawiał u mnie przy braku możliwości połączenia z siecią, więc najwyraźniej dostawca Twojej usługi wyciął do niej dostęp **jakimś cudem**. Mi osobiście tylko tak się udało zreprodukować ten błąd,

**Comment by MentosPL** [comment]
Proponował bym wydania jakiejś łatki by nie było błędu przy braku połączenia, tylko wiadomość że nie udało się połączyć. Co do problemu z połączeniem napiszę na Discordzie i spróbuję dodać do whitelist.

**Comment by kacperduras** [comment]
```
Proponował bym wydania jakiejś łatki by nie było błędu przy braku połączenia [...]
```

Odpada, a wiesz dlaczego? Stacktrace, czyli ten błąd, daje nam cenną wskazówkę, dlaczego Tobie właśnie np. ta funkcjonalność nie działa.

**Comment by dzikoysk** [comment]
dzikoysk.net > github.com

GitHub może was wyrzucać jako zwykłego bota, ogólnie mało pewne źródło. Jak już to chociaż wyciszajcie ten exception i piszcie że nie udało się sprawdzić wersji

**Comment by kacperduras** [comment]
```
dzikoysk.net > github.com
```

To wiadome, tylko **pewien pan** nie zawsze może wyrabiać z wersjonowaniem, jak to było np. wczoraj.

**Comment by dzikoysk** [comment]
Chyba go nie znam ಠ_ಠ

**Comment by MrGregorix** [comment]
Nazywa się ludwik i pochodzi z Warszawy :/
