### ISSUE TITLE
Błąd updatera FunnyGuilds 4.0.0.2

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#567]
Błąd:
`[16:30:04] [Craft Scheduler Thread - 10/WARN]: java.net.ConnectException: Connection timed out
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at net.dzikoysk.funnyguilds.util.IOUtils.getContent(IOUtils.java:37)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at net.dzikoysk.funnyguilds.FunnyGuilds.lambda$update$0(FunnyGuilds.java:196)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[16:30:04] [Craft Scheduler Thread - 10/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:30:04] [Craft Scheduler Thread - 10/INFO]: [FunnyGuilds][Updater] > Failed to check the newest version of FunnyGuilds..`

**Comment by kacperduras** [comment]
#556
