### ISSUE TITLE
Nieaktywna tablista

### ISSUE THREAD

**Issue by KrifixYT** [FunnyGuilds/FunnyGuilds#586]
Witam! Posiadam błąd z tablistą!
ZDJĘCIE: https://imgur.com/a/Dn0oT

Wersja serwera: 1.8
Wersja pluginu: 3.9.6.5 Cleaned

Config.yml: https://pastebin.com/ZV5wZYAB #

**Comment by Kamilkime** [comment]
![image](https://user-images.githubusercontent.com/10383567/32282224-5479f3f6-bf21-11e7-9140-3447f7dc0d4e.png)

**Comment by KrifixYT** [comment]
@Kamilkime wersja serwera: 1.8
najnowsza wersja pluginu (już),

teraz, tablista wgl nie zmieniona.

**Comment by Kamilkime** [comment]
No, wypadałoby jeszcze wygenerować nowy config dla pewności i poustawiać, nie?

**Comment by KrifixYT** [comment]
dobra, sprobuje

**Comment by KrifixYT** [comment]
czyli usunac stary?

**Comment by Kamilkime** [comment]
Może zmień nazwę starego na coś innego (żeby go sobie zachować) i wygeneruj config na nowo

**Comment by KrifixYT** [comment]
gotowe. Dalej to samo. Tablista nie ruszona

info-player-enabled: true

**Comment by kacperduras** [comment]
Poproszę:
* log z uruchamiania serwera (**cały**)

**Comment by KrifixYT** [comment]
@kacperduras https://pastebin.com/bWCDxSPJ

**Comment by kacperduras** [comment]
Dziwne, w logu wszystkie rzeczy związane z FG uruchamiają się prawidłowo. [Implementacja tab listy](https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/util/element/tablist/impl/v1_8_R1/TablistImpl.java) dla tej wersji też jest dostępna. Zrób tak - uruchom osobny serwer ze samym FG i na tym samym silniku. Jeśli będzie działać - błąd jest po Twojej stronie.

**Comment by KrifixYT** [comment]
Dora, potem sprawdze! Dzieki!

**Comment by kacperduras** [comment]
Nie ma problemu.
Napisz jak sprawdzisz, póki co issue zostawiam otwarte.

**Comment by KrifixYT** [comment]
@kacperduras https://imgur.com/a/SKpGH
nie działa ;/

**Comment by Kamilkime** [comment]
A jakbyś użył czystego MC?

**Comment by KrifixYT** [comment]
aaa, juz sprawdzam

**Comment by KrifixYT** [comment]
dodam, ze teraz spami w konsoli gdy gracz jest, jak niema to nie spami:

[19:53:27] [Craft Scheduler Thread - 1025/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.0.0.2 Tribute-26f168c generated an exception while executing task 3818
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.dzikoysk.funnyguilds.util.element.tablist.impl.v1_8_R1.TablistImpl
	at net.dzikoysk.funnyguilds.util.element.tablist.AbstractTablist.createTablist(AbstractTablist.java:63)
	at net.dzikoysk.funnyguilds.util.runnable.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:67)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by KrifixYT** [comment]
na czystym tez niema

**Comment by Kamilkime** [comment]
Jakiego silnika używasz?

**Comment by KrifixYT** [comment]
PaperSpigot - 1.8

**Comment by Kamilkime** [comment]
A jakbyś spróbował np. z tym?
https://yivesmirror.com/grab/paperspigot/PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar

**Comment by KrifixYT** [comment]
spox

**Comment by KrifixYT** [comment]
dobra, działa! DZIENA
