### ISSUE TITLE
FunnyGuilds gryzie się z WorldGuard

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#589]
FunnyGuilds uniemożliwia załadowanie się WorldGuard, mam ok 52 pluginów, i wszystkie są aktualizowane do najnowszej wersji, gdy dodaje do listy pluginów FG, WorldGuard daje błąd typu "nie odnaleziono WorldEdit"

błąd WG:

`[19:36:18] [Server thread/ERROR]: Could not load 'plugins\worldguard-legacy-6.2.2-SNAPSHOT-dist.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandsManager
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:326) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:308) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandsManager
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_112]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.minecraft.util.commands.CommandsManager
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_112]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	... 6 more
`

**Comment by Kamilkime** [comment]
Jest to poprawione w https://github.com/FunnyGuilds/FunnyGuilds/commit/575294c7cc984a33fd6ce10d22511a779ca261b1, zbuduj sobie najnowsze FG przy użyciu FunnyCreator'a

**Comment by kacperduras** [comment]
@Kamilkime objaśnił, zamykam.
