### ISSUE TITLE
NPE podczas wygasania gildii.

### ISSUE THREAD

**Issue by insertt** [FunnyGuilds/FunnyGuilds#591]
```java
[18:00:42 WARN]: java.lang.NullPointerException
[18:00:42 WARN]: 	at net.dzikoysk.funnyguilds.util.reflect.EntityUtil.despawn(EntityUtil.java:105)
[18:00:42 WARN]: 	at net.dzikoysk.funnyguilds.basic.util.GuildUtils.deleteGuild(GuildUtils.java:40)
[18:00:42 WARN]: 	at net.dzikoysk.funnyguilds.system.validity.ValiditySystem.run(ValiditySystem.java:25)
[18:00:42 WARN]: 	at net.dzikoysk.funnyguilds.util.runnable.AsynchronouslyRepeater.validitySystem(AsynchronouslyRepeater.java:80)
[18:00:42 WARN]: 	at net.dzikoysk.funnyguilds.util.runnable.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:58)
[18:00:42 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[18:00:42 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[18:00:42 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:00:42 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:00:42 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:00:42 WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dzikoysk** [comment]
:)
