### ISSUE TITLE
Pasek Smoka

### ISSUE THREAD

**Issue by Przemo12** [FunnyGuilds/FunnyGuilds#592]
Gdy na teren naszej gildii wbije gracz bez gildii, nie wyswietla sie pasek smoka :/

**Comment by dzikoysk** [comment]
Powiadomienie nie wysyła się, jeżeli admin (~op/osoba z uprawnieniem) wejdzie na teren gildii. https://github.com/FunnyGuilds/FunnyGuilds/blob/f345a40d96e33c0c4829c6f6bb2535e4e1d1c888/src/main/java/net/dzikoysk/funnyguilds/listener/region/PlayerMove.java#L71 Jesteś pewien, że takowego nie masz?

**Comment by Przemo12** [comment]
Przepraszam, mój błąd.

**Comment by kacperduras** [comment]
Otwieram w związku z #597

**Comment by Ixidi** [comment]
Jakis blad w konsoli jest?

**Comment by Przemo12** [comment]
Żadnego błędu nie ma. Po prostu pasek smoka inaczej działa niż na 1.7, gdy plugin działał na wersji 1.7-1.8 gdy grałeś na 1.8 pasek smoka też się nie wyświetlał :/

**Comment by Ixidi** [comment]
Pisales, ze nie wyswietla sie tez info na chcie. Jaka masz wersje fg?

**Comment by kacperduras** [comment]
@Przemo12 poproszę cały log z uruchomienia serwera.

**Comment by Przemo12** [comment]
`[12:28:24] [Server thread/INFO]: Starting minecraft server version 1.8.8
[12:28:24] [Server thread/INFO]: Loading properties
[12:28:24] [Server thread/INFO]: Default game type: SURVIVAL
[12:28:24] [Server thread/INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[12:28:24] [Server thread/INFO]: Spigot Timings: true - Verbose: true - Interval: 5m - Length: 60m
[12:28:24] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:28:24] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:28:24] [Server thread/INFO]: Debug logging is disabled
[12:28:24] [Server thread/INFO]: Data value allowed items: 
[12:28:24] [Server thread/INFO]: Generating keypair
[12:28:24] [Server thread/INFO]: Starting Minecraft server on *:21111
[12:28:24] [Server thread/INFO]: Using epoll channel type
[12:28:25] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[12:28:25] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v1.23.3
[12:28:25] [Server thread/WARN]: [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!
[12:28:25] [Server thread/INFO]: [iAntyLogout] Loading iAntyLogout v1.3
[12:28:25] [Server thread/INFO]: [Skript] Loading Skript v2.2-Fixes-V8b
[12:28:25] [Server thread/INFO]: [Essentials] Loading Essentials vTeamCity
[12:28:25] [Server thread/INFO]: [Vault] Loading Vault v1.4.1-b436
[12:28:25] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn vTeamCity
[12:28:25] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat vTeamCity
[12:28:25] [Server thread/INFO]: [ChestCommands] Loading ChestCommands v3.1.4
[12:28:25] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.0;3342-78f975b9
[12:28:25] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v5.9
[12:28:25] [Server thread/INFO]: [FunnyGuilds] Loading FunnyGuilds v4.0.0.2 Tribute-26f168c
[12:28:25] [Server thread/WARN]: [FunnyGuilds] FunnyGuilds supports only WorldGuard v6.2 or newer
[12:28:25] [Server thread/INFO]: [Vault] Enabling Vault v1.4.1-b436
[12:28:25] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[12:28:25] [Server thread/INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[12:28:25] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[12:28:25] [Server thread/INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[12:28:25] [Server thread/INFO]: [Vault] Enabled Version 1.4.1-b436
[12:28:25] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[12:28:25] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[12:28:25] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[12:28:25] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[12:28:25] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[12:28:25] [Server thread/INFO]: Preparing level "world"
[12:28:25] [Server thread/INFO]: -------- World Settings For [world] --------
[12:28:25] [Server thread/INFO]: Item Despawn Rate: 6000
[12:28:25] [Server thread/INFO]: Item Merge Radius: 2.5
[12:28:25] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:28:25] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:28:25] [Server thread/INFO]: View Distance: 10
[12:28:25] [Server thread/INFO]: Chunks to Grow per Tick: 650
[12:28:25] [Server thread/INFO]: Clear tick list: false
[12:28:25] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:28:25] [Server thread/INFO]: Anti X-Ray: true
[12:28:25] [Server thread/INFO]: 	Engine Mode: 1
[12:28:25] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[12:28:25] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[12:28:25] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:28:25] [Server thread/INFO]: Mob Spawn Range: 4
[12:28:25] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[12:28:25] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:28:25] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[12:28:25] [Server thread/INFO]: Random Lighting Updates: false
[12:28:25] [Server thread/INFO]: Structure Info Saving: true
[12:28:25] [Server thread/INFO]: Sending up to 10 chunks per packet
[12:28:25] [Server thread/INFO]: Max Entity Collisions: 8
[12:28:25] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[12:28:25] [Server thread/INFO]: Max TNT Explosions: 100
[12:28:25] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:28:25] [Server thread/INFO]: Arrow Despawn Rate: 1200
[12:28:25] [Server thread/INFO]: -------- World Settings For [world] --------
[12:28:25] [Server thread/INFO]: Allow undead horse types to be leashed: false
[12:28:25] [Server thread/INFO]: Keep spawn chunk loaded: true
[12:28:25] [Server thread/INFO]: WorldServer TickNextTick cap set at 10000
[12:28:25] [Server thread/INFO]: WorldServer TickNextTickList cap always processes redstone: false
[12:28:25] [Server thread/INFO]: World async lighting: false
[12:28:25] [Server thread/INFO]: Player blocking damage multiplier set to 0.5
[12:28:25] [Server thread/INFO]: Remove invalid mob spawner tile entities: true
[12:28:25] [Server thread/INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[12:28:25] [Server thread/INFO]: Max height for cactus growth 3. Max height for reed growth 3
[12:28:25] [Server thread/INFO]: Living Entity Despawn Ranges:  Soft: 32 Hard: 128
[12:28:25] [Server thread/INFO]: Water over lava flow speed: 5
[12:28:25] [Server thread/INFO]: Fix TNT cannons: false
[12:28:25] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[12:28:25] [Server thread/INFO]: Item Despawn Rate: 6000
[12:28:25] [Server thread/INFO]: Item Merge Radius: 2.5
[12:28:25] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:28:25] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:28:25] [Server thread/INFO]: View Distance: 10
[12:28:25] [Server thread/INFO]: Chunks to Grow per Tick: 650
[12:28:25] [Server thread/INFO]: Clear tick list: false
[12:28:25] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:28:25] [Server thread/INFO]: Anti X-Ray: true
[12:28:25] [Server thread/INFO]: 	Engine Mode: 1
[12:28:25] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[12:28:25] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[12:28:25] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:28:25] [Server thread/INFO]: Mob Spawn Range: 4
[12:28:25] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[12:28:25] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[12:28:25] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:28:25] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[12:28:25] [Server thread/INFO]: Random Lighting Updates: false
[12:28:25] [Server thread/INFO]: Structure Info Saving: true
[12:28:25] [Server thread/INFO]: Sending up to 10 chunks per packet
[12:28:25] [Server thread/INFO]: Max Entity Collisions: 8
[12:28:25] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[12:28:25] [Server thread/INFO]: Max TNT Explosions: 100
[12:28:25] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:28:25] [Server thread/INFO]: Arrow Despawn Rate: 1200
[12:28:25] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[12:28:25] [Server thread/INFO]: Allow undead horse types to be leashed: false
[12:28:25] [Server thread/INFO]: Keep spawn chunk loaded: true
[12:28:25] [Server thread/INFO]: WorldServer TickNextTick cap set at 10000
[12:28:25] [Server thread/INFO]: WorldServer TickNextTickList cap always processes redstone: false
[12:28:25] [Server thread/INFO]: World async lighting: false
[12:28:25] [Server thread/INFO]: Player blocking damage multiplier set to 0.5
[12:28:25] [Server thread/INFO]: Remove invalid mob spawner tile entities: true
[12:28:25] [Server thread/INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[12:28:25] [Server thread/INFO]: Max height for cactus growth 3. Max height for reed growth 3
[12:28:25] [Server thread/INFO]: Living Entity Despawn Ranges:  Soft: 32 Hard: 128
[12:28:25] [Server thread/INFO]: Water over lava flow speed: 5
[12:28:25] [Server thread/INFO]: Fix TNT cannons: false
[12:28:26] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[12:28:26] [Server thread/INFO]: Item Despawn Rate: 6000
[12:28:26] [Server thread/INFO]: Item Merge Radius: 2.5
[12:28:26] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:28:26] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:28:26] [Server thread/INFO]: View Distance: 10
[12:28:26] [Server thread/INFO]: Chunks to Grow per Tick: 650
[12:28:26] [Server thread/INFO]: Clear tick list: false
[12:28:26] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:28:26] [Server thread/INFO]: Anti X-Ray: true
[12:28:26] [Server thread/INFO]: 	Engine Mode: 1
[12:28:26] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[12:28:26] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[12:28:26] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:28:26] [Server thread/INFO]: Mob Spawn Range: 4
[12:28:26] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:28:26] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:28:26] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:28:26] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:28:26] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:28:26] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:28:26] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:28:26] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[12:28:26] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[12:28:26] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:28:26] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[12:28:26] [Server thread/INFO]: Random Lighting Updates: false
[12:28:26] [Server thread/INFO]: Structure Info Saving: true
[12:28:26] [Server thread/INFO]: Sending up to 10 chunks per packet
[12:28:26] [Server thread/INFO]: Max Entity Collisions: 8
[12:28:26] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[12:28:26] [Server thread/INFO]: Max TNT Explosions: 100
[12:28:26] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:28:26] [Server thread/INFO]: Arrow Despawn Rate: 1200
[12:28:26] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[12:28:26] [Server thread/INFO]: Allow undead horse types to be leashed: false
[12:28:26] [Server thread/INFO]: Keep spawn chunk loaded: true
[12:28:26] [Server thread/INFO]: WorldServer TickNextTick cap set at 10000
[12:28:26] [Server thread/INFO]: WorldServer TickNextTickList cap always processes redstone: false
[12:28:26] [Server thread/INFO]: World async lighting: false
[12:28:26] [Server thread/INFO]: Player blocking damage multiplier set to 0.5
[12:28:26] [Server thread/INFO]: Remove invalid mob spawner tile entities: true
[12:28:26] [Server thread/INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[12:28:26] [Server thread/INFO]: Max height for cactus growth 3. Max height for reed growth 3
[12:28:26] [Server thread/INFO]: Living Entity Despawn Ranges:  Soft: 32 Hard: 128
[12:28:26] [Server thread/INFO]: Water over lava flow speed: 5
[12:28:26] [Server thread/INFO]: Fix TNT cannons: false
[12:28:26] [Server thread/INFO]: Preparing start region for level 0 (Seed: 8022276141567175133)
[12:28:27] [Server thread/INFO]: Preparing spawn area: 84%
[12:28:27] [Server thread/INFO]: Preparing start region for level 1 (Seed: -8802918393880657970)
[12:28:28] [Server thread/INFO]: Preparing start region for level 2 (Seed: -8802918393880657970)
[12:28:28] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.3
[12:28:28] [Server thread/INFO]: [PermissionsEx] Initializing file backend
[12:28:28] [Server thread/INFO]: [PermissionsEx] Permissions file successfully reloaded
[12:28:28] [Server thread/INFO]: [Vault][Permission] PermissionsEx hooked.
[12:28:28] [Server thread/INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
[12:28:28] [Server thread/INFO]: [iAntyLogout] Enabling iAntyLogout v1.3
[12:28:28] [Server thread/INFO]: [iAntyLogout] Uzywasz wersji serwera: 1.8
[12:28:28] [Server thread/INFO]: [iAntyLogout] Ladowanie config.yml...
[12:28:28] [Server thread/INFO]: [iAntyLogout] Wladowano config.yml
[12:28:28] [Server thread/INFO]: [Skript] Enabling Skript v2.2-Fixes-V8b
[12:28:29] [Server thread/INFO]: [Skript] Loaded a total of 11504 english aliases
[12:28:29] [Server thread/WARN]: [Skript] There are no aliases defined for the following ids: 165, 166, 167, 168, 169, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 409, 410, 411, 412, 413, 414, 415, 416, 423, 424, 425, 427, 428, 429, 430, 431
[12:28:29] [Server thread/INFO]: [Skript]  ~ created by & ? Peter G?ttinger aka Njol ~
[12:28:30] [Server thread/INFO]: [Essentials] Enabling Essentials vTeamCity
[12:28:30] [Server thread/INFO]: Bukkit version format changed. Version not checked.
[12:28:30] [Server thread/INFO]: git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[12:28:30] [Server thread/INFO]: 1.8.8-R0.1-SNAPSHOT
[12:28:30] [Server thread/INFO]: Using locale pl
[12:28:30] [Server thread/INFO]: Using locale pl
[12:28:30] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.
[12:28:30] [Server thread/INFO]: Essentials: Using PermissionsEx based permissions.
[12:28:30] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vTeamCity
[12:28:30] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat vTeamCity
[12:28:30] [Server thread/INFO]: [ChestCommands] Enabling ChestCommands v3.1.4
[12:28:30] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.0;3342-78f975b9
[12:28:30] [Server thread/INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[12:28:30] [Server thread/WARN]: [WorldEdit] 
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and biome-related functions.
**
** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
**********************************************

[12:28:30] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v5.9
[12:28:30] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[12:28:30] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[12:28:30] [Server thread/INFO]: [WorldGuard] (world) Lava fire is blocked.
[12:28:30] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[12:28:30] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[12:28:30] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[12:28:30] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[12:28:30] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[12:28:30] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[12:28:30] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[12:28:30] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[12:28:30] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[12:28:30] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[12:28:30] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[12:28:30] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[12:28:30] [Server thread/INFO]: [WorldGuard] 0 regions loaded for 'world'
[12:28:30] [Server thread/INFO]: [WorldGuard] 0 regions loaded for 'world_nether'
[12:28:30] [Server thread/INFO]: [WorldGuard] 0 regions loaded for 'world_the_end'
[12:28:30] [Server thread/INFO]: [FunnyGuilds] Enabling FunnyGuilds v4.0.0.2 Tribute-26f168c
[12:28:30] [Server thread/INFO]: [FunnyGuilds] Available Processors: 2
[12:28:30] [Server thread/INFO]: [FunnyGuilds] Active Threads: 12
[12:28:30] [Server thread/INFO]: [FunnyGuilds] Loaded users: 7
[12:28:30] [Server thread/INFO]: [FunnyGuilds] Loaded regions: 1
[12:28:30] [Server thread/INFO]: [FunnyGuilds] Loaded guilds: 1
[12:28:30] [Server thread/INFO]: [FunnyGuilds] ~ Created by & ? Dzikoysk ~
[12:28:31] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:28:31] [Server thread/INFO]: Done (5.308s)! For help, type "help" or "?"
[12:28:31] [Server thread/INFO]: Timings Reset
[12:28:31] [Craft Scheduler Thread - 3/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Checking for the latest version of Skript...[m
[12:28:31] [Server thread/INFO]: [Skript] Loading variables...
[12:28:31] [Server thread/INFO]: [Skript] Loaded 0 variables in 0.0 seconds
[12:28:31] [Craft Scheduler Thread - 5/INFO]: [FunnyGuilds][Updater] > You have the newest version of FunnyGuilds.
[12:28:31] [Server thread/INFO]: [Skript] All scripts loaded without errors.
[12:28:31] [Server thread/INFO]: [Skript] Loaded 1 script with a total of 0 triggers and 1 command in 0.12 seconds
[12:28:31] [Server thread/INFO]: [Skript] Finished loading.`

**Comment by Przemo12** [comment]
@Ixidi  Najnowszą

**Comment by dzikoysk** [comment]
26f168c czyli 21 dniowa wersja, bo nie wydaliście ostatnio żadnej oficjalnie. Możesz spróbować zbuildować najnowszą wersję indev FunnyCreatorem i sprawdzić czy błąd dalej występuje. Insert chyba coś tam też się bawił tak mi się kojarzy

**Comment by Przemo12** [comment]
Wgrałem teraz wersję z funnyguilds creator, wyskakuje błąd:
`[13:51:56] [Craft Scheduler Thread - 1/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.ChatMessageType
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at java.lang.Class.forName0(Native Method)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at java.lang.Class.forName(Class.java:264)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at net.dzikoysk.funnyguilds.util.reflect.Reflections.getClass(Reflections.java:48)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at net.dzikoysk.funnyguilds.util.reflect.Reflections.getCraftClass(Reflections.java:60)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at net.dzikoysk.funnyguilds.util.NotificationUtil.<clinit>(NotificationUtil.java:27)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at net.dzikoysk.funnyguilds.util.element.tablist.AbstractTablist.createBaseComponent(AbstractTablist.java:109)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at net.dzikoysk.funnyguilds.util.element.tablist.impl.v1_8_R3.TablistImpl.send(TablistImpl.java:95)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at net.dzikoysk.funnyguilds.util.runnable.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:70)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:51:56] [Craft Scheduler Thread - 1/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

Do tego logi gdy wchodze na teren gildii:
`[13:52:06] [Server thread/INFO]: tester[/178.216.24.51:57573] logged in with entity id 271 at ([world]417.9202755692616, 69.0, -165.37032096243937)
[13:52:07] [Server thread/INFO]: [0;33;22m[21m[[0;37;22mGracz[0;33;22m[21m][0;30;1mtester[m [0;32;1m+[m
[13:52:19] [Server thread/INFO]: tester issued server command: /tpa tester
[13:52:45] [Server thread/INFO]: tester issued server command: /tpa tester
[13:52:48] [Server thread/INFO]: tester issued server command: /tpa KucykNasz
[13:52:51] [Server thread/INFO]: KucykNasz issued server command: /tpaccept
`
oraz screenshot
https://imgur.com/a/gcqnz:

**Comment by Przemo12** [comment]
Odświeżam temat, w nowej wersji pluginu, informacja nie działa nadal na pasku smoka, a wiadomosc ze intruz wszedl na teren gildii, pojawia się intruzowi, zamiast ludziom z gildii.

**Comment by kacperduras** [comment]
Nie potrzeby odświeżania zgłoszenia, ponieważ jest otwarte.

**Comment by Przemo12** [comment]
Wiesz może kiedy to będzie naprawione?

**Comment by MrGregorix** [comment]
Tak, to będzie naprawione zaraz po tym jak ktoś to naprawi =)

**Comment by Kamilkime** [comment]
No, to problemy już chyba zostały rozwiązane, nie @Przemo12 ?

**Comment by kacperduras** [comment]
Zakładam, że tak. Jak dalej nie bedzie działało - pisz tutaj.

**Comment by Przemo12** [comment]
W ostatnim release zostało to naprawione tak, że wiadomość wysyła się intruzowi, zamiast ludziom z gildii. Mogę sprawdzić wersję zbudowaną funnycreatorem.

**Comment by Kamilkime** [comment]
W ostatnim release nie było to naprawiane, ja poprawiłem to wczoraj, więc musisz użyć FunnyCreator'a

**Comment by MrGregorix** [comment]
Dzięki Kamil, kiedy 51 odcinek?

**Comment by kamcio96** [comment]
Dzięki Kamil, kiedy usuniesz kanał?

**Comment by Bartssqu** [comment]
Dzięki Kamil, kiedy pijemy?

**Comment by Kamilkime** [comment]
Błagam... Niech ktoś jakoś zablokuje to issue i @Przemo12 ewentualnie napisze nowy issue...

**Comment by kacperduras** [comment]
Dzięki Kamil....
a tak serio, zważywszy na to - nie ma problemu ;)
