### ISSUE TITLE
ClassNotFoundException: ChatMessageType

### ISSUE THREAD

**Issue by JucyJ** [FunnyGuilds/FunnyGuilds#601]
```
[20:59:14 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.ChatMessageType
[20:59:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[20:59:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[20:59:14 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[20:59:14 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[20:59:14 WARN]:        at java.lang.Class.forName0(Native Method)
[20:59:14 WARN]:        at java.lang.Class.forName(Unknown Source)
[20:59:14 WARN]:        at net.dzikoysk.funnyguilds.util.reflect.Reflections.getClass(Reflections.java:48)
[20:59:14 WARN]:        at net.dzikoysk.funnyguilds.util.reflect.Reflections.getCraftClass(Reflections.java:60)
[20:59:14 WARN]:        at net.dzikoysk.funnyguilds.util.NotificationUtil.<clinit>(NotificationUtil.java:27)
[20:59:14 WARN]:        at net.dzikoysk.funnyguilds.util.element.tablist.AbstractTablist.createBaseComponent(AbstractTablist.java:109)
[20:59:14 WARN]:        at net.dzikoysk.funnyguilds.util.element.tablist.impl.v1_8_R3.TablistImpl.send(TablistImpl.java:95)
[20:59:14 WARN]:        at net.dzikoysk.funnyguilds.util.runnable.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:70)
[20:59:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[20:59:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:59:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:59:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:59:14 WARN]:        at java.lang.Thread.run(Unknown Source)
```
Ten błąd występuje na każdym testowanym silniku (TacoSpigot, PaperSpigot i Spigot) i na najnowszym buildzie.

**Comment by Kamilkime** [comment]
Klasa ChatMessageType jest tylko na 1.12, od 1.8 do 1.11 - nie ma jej w NMSie

**Comment by TheMolkaPL** [comment]
Masz nieaktualny silnik serwera.

**Comment by dzikoysk** [comment]
Tak czy inaczej do poprawy, skoro wsparcie chcemy utrzymać przy 1.8+

**Comment by insertt** [comment]
Naprawione w #7e4044e
