### ISSUE TITLE
Błędy, błędy i jeszcze więcej nulli

### ISSUE THREAD

**Issue by Inder00** [FunnyGuilds/FunnyGuilds#620]
Pierwszy i drugi blad podczas ladowania, a trzeci strzelanie tnt w endzie :+1: powodzenia
Hastebin: https://hastebin.com/kenapezupe.vbs (bardziej czytelniej)

```
[12:01:09] [Server thread/ERROR]: null initializing FunnyGuilds v4.0.1.1 Tribute-c3578f4 (Is it up to date?)
java.lang.NullPointerException
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at net.dzikoysk.funnyguilds.util.ItemBuilder.<init>(ItemBuilder.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.util.Parser.parseItem(Parser.java:71) ~[?:?]
	at net.dzikoysk.funnyguilds.data.configs.PluginConfig.loadItemStackList(PluginConfig.java:524) ~[?:?]
	at net.dzikoysk.funnyguilds.data.configs.PluginConfig.reload(PluginConfig.java:543) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.<init>(Settings.java:16) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.getConfig(Settings.java:21) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:127) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

[12:08:45] [FunnyGuilds | IndependentThread/WARN]: java.lang.NullPointerException
[12:08:45] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.IndividualPrefix.replace(IndividualPrefix.java:213)
[12:08:45] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.IndividualPrefix.initialize(IndividualPrefix.java:162)
[12:08:45] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.IndividualPrefix.<init>(IndividualPrefix.java:22)
[12:08:45] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.basic.User.getIndividualPrefix(User.java:192)
[12:08:45] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.IndividualPrefixManager.updatePlayer(IndividualPrefixManager.java:24)
[12:08:45] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.IndividualPrefixManager.updatePlayers(IndividualPrefixManager.java:14)
[12:08:45] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:70)
[12:08:45] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:107)
[12:08:45] [FunnyGuilds | IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:87)
[12:08:45] [Server thread/INFO]: [FunnyGuilds] Loaded guilds: 1
[12:08:45] [Server thread/ERROR]: Error occurred while enabling FunnyGuilds v4.0.1.1 Tribute-c3578f4 (Is it up to date?)
java.lang.IllegalArgumentException: Display name cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftObjective.setDisplayName(CraftObjective.java:39) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at net.dzikoysk.funnyguilds.util.element.Dummy.initialize(Dummy.java:46) ~[?:?]
	at net.dzikoysk.funnyguilds.util.element.Dummy.<init>(Dummy.java:20) ~[?:?]
	at net.dzikoysk.funnyguilds.basic.User.getDummy(User.java:203) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.patch(FunnyGuilds.java:224) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:174) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.Bukkit.reload(Bukkit.java:535) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]

[12:33:58] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to FunnyGuilds v4.0.1.1 Tribute-c3578f4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.Explosion.a(Explosion.java:184) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.createExplosion(World.java:1867) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldServer.createExplosion(WorldServer.java:1020) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityTNTPrimed.explode(EntityTNTPrimed.java:84) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityTNTPrimed.t_(EntityTNTPrimed.java:63) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.listener.region.EntityExplode.onExplode(EntityExplode.java:72) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	... 17 more
```

**Comment by kacperduras** [comment]
Niby taki kozak, ale PRa z fixami to nie da.

**Comment by Kamilkime** [comment]
Niby błąd zgłoszony... Ale to trochę wredne było, szczególnie gdy się spojrzy na to, kto ten błąd w taki sposób zgłasza...

**Comment by Bartssqu** [comment]
Wsadź do ryżu

**Comment by Kamilkime** [comment]
@Inder00 W sumie, mógłbyś jeszcze pokazać swój config

**Comment by insertt** [comment]
Każdy z tych błędów dotyczy błędnej konfiguracji, także wklej tutaj swoją konfigurację.

**Comment by Inder00** [comment]
Config: https://hastebin.com/iyerihedil.php

**Comment by Kamilkime** [comment]
W linijkach 59-63 i 100-101 są podane złe nazwy przedmiotów - np. **diamonds** zamiast **diamond**

**Comment by Kamilkime** [comment]
Stringi typu _tomabycwylaczoneboniemabycczegostakiegoxd@_ weź w cudzysłowy

**Comment by kacperduras** [comment]
Wygląda to na błędną konfigurację - błędy wymienione wyżej. Zamykam.
