### ISSUE TITLE
Błąd fg config (PRZEDMIOTY NA GILDIE)

### ISSUE THREAD

**Issue by AdireN** [FunnyGuilds/FunnyGuilds#648]
Przy dodaniu do itemów na gildie 
- 32 gold block
- 32 gold_block
- 32 Gold ingot 
ogólnie złote przedmioty nie są rozpoznawane przez fg a w logach występuje tylko.

`[16:20:06] [Server thread/ERROR]: [FunnyGuilds][Parser] #> Unknown item: GOLD
[16:20:06] [Server thread/ERROR]: null initializing FunnyGuilds v4.0.1.1 Tribute-c3578f4 (Is it up to date?)
java.lang.NullPointerException
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.dzikoysk.funnyguilds.util.ItemBuilder.<init>(ItemBuilder.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.util.Parser.parseItem(Parser.java:71) ~[?:?]
	at net.dzikoysk.funnyguilds.data.configs.PluginConfig.loadItemStackList(PluginConfig.java:524) ~[?:?]
	at net.dzikoysk.funnyguilds.data.configs.PluginConfig.reload(PluginConfig.java:534) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.<init>(Settings.java:16) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Settings.getConfig(Settings.java:21) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:127) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

**Comment by insertt** [comment]
Wklej tutaj kawałek konfiguracji z tym elementem

**Comment by AdireN** [comment]
`# ~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~ #
#                                 #
#           FunnyGuilds           #
#         4.0.1.1 Tribute         #
#                                 #
# ~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~ #
# Wyswietlana nazwa pluginu
plugin-name: FunnyGuilds
# Maksymalna dlugosc nazwy gildii
name-length: 22
# Minimalna dlugosc nazwy gildii
name-min-length: 4
# Maksymalna dlugosc tagu gildii
tag-length: 4
# Minimalna dlugosc tagu gildii
tag-min-length: 2
# Minimalna ilosc graczy w gildii aby zaliczala sie do rankingu.
guild-min-members: 3
# Przedmioty wymagane do zalozenia gildii
# Dwukropek i metadata po nazwie przedmiotu sa opcjonalne
# Wzor: <ilosc> <przedmiot>:[metadata] [name:lore:enchant]
# Spacja = _ 
# Nowa linia lore = #
items: 
- 64 diamond
- 64 emerald block
- 64 bookshelf
- 64 TNT
- 64 Golden block
# Przedmioty wymagane do zalozenia gildii dla osoby z uprawnieniem funnyguilds.vip
items-vip: 
- 32 diamond
- 32 emerald block
- 32 bookshelf
- 32 TNT
- 32 Golden block
# Odleglosc od spawnu
create-distance: 350
# Blok, jaki pojawi sie pod nami po stworzeniu gildii
create-material: ender crystal
# Na jakim poziomie ma byc wyznaczone centrum gildii
# - Wpisz 0, jezeli ma byc ustalone przez gracza
create-center-y: 50
# Czy ma tworzyc pusta przestrzen dookola centrum gildii
create-center-sphere: true
# Maksymalna ilosc czlonkow w gildii
max-members: 15
# Swiaty, na ktorych powinno byc zablokowane tworzenie gildii
blockedworlds: 
- some_world
# Mozliwosc teleportacji do gildii
base-enable: true
# Czas oczekiwania na teleportacje (w sekundach)
base-delay: 8
# Koszt teleportacji do gildii (jezeli brak, wystarczy zrobic: base-items: [])
base-items: []
# Koszt dolaczenia do gildii (jezeli brak, wystarczy zrobic: join-items: [])
join-items: 
- 128 diamond
# Mozliwosc powiekszania gildii
enlarge-enable: true
# O ile powieksza teren gildii 1 poziom
enlarge-size: 5
# Koszt powiekszania gildii
# - kazdy myslnik, to 1 poziom gildii
enlarge-items: 
- 128 diamond block
- 256 diamond block
- 64 diamond block
- 128 emerald block
- 128 emerald block
- 128 emerald block
- 250 emerald block
- 250 emerald block
- 250 emerald block
- 250 emerald block
# Wielkosc regionu gildii
region-size: 50
# Minimalna odleglosc miedzy terenami gildii
region-min-distance: 70
# Czas wyswietlania powiadomienia na pasku powiadomien (w sekundach)
region-notification-time: 15
# Co ile moze byc wywolywany pasek powiadomien przez jednego gracza (w sekundach)
region-notification-cooldown: 60
# Blokowane komendy dla graczy spoza gildii na jej terenie
region-commands: 
- sethome
- esethome
- ehome
- baza
- dom
- tpa
- tpaccept
- etpaccept
- etpa
- spawn
- schowek`

**Comment by Kamilkime** [comment]
Nie używa się spacji w nazwach itemu - **emerald_block**, a nie **emerald block**

**Comment by AdireN** [comment]
@Kamilkime  nie chodzi o emeraldy jeśli usunę przedmioty z dopiskiem gold to wszystko śmiga, nie jest to główny problem

**Comment by Kamilkime** [comment]
Używaj _ zamiast spacji w nazwach typów itemów, bo metoda ich zamiany jest niedoskonała :/

**Comment by Kamilkime** [comment]
To już zakończone i do zamknięcia

**Comment by kacperduras** [comment]
To zamknij :p

**Comment by Kamilkime** [comment]
No... chyba nie...
