### ISSUE TITLE
Baza danych mysql

### ISSUE THREAD

**Issue by Marceleq1321** [FunnyGuilds/FunnyGuilds#650]
Witam mam pewien problem z podłączeniem funnyguilds do bazy danych ;v
Uzupełniam config dobrze. Testowałem na localhoscie na 2 bazach danych i nic instalowałem nowe i starsze wersje funnyguilds i też nic tylko errory w konsoli ;<
Dodam że jest mi to bardzo potrzebne do stworzenia rankingów na stronę www
A może coś źle robię wytłumaczy mi ktoś krok po kroku jak to zrobić przeczesałem cały internet za tym i nic nie znalazłem.

Tutaj logi z konsoli 

> [23:01:09] [Server thread/INFO]: [FunnyGuilds] Enabling FunnyGuilds v4.0.0.2 Tribute-26f168c
[23:01:09] [Server thread/INFO]: [FunnyGuilds] Available Processors: 8
[23:01:09] [Server thread/INFO]: [FunnyGuilds] Active Threads: 16
[23:01:09] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[23:01:09] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[23:01:09] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[23:01:09] [Server thread/ERROR]: Error occurred while enabling FunnyGuilds v4.0.0.2 Tribute-26f168c (Is it up to date?)
java.lang.IllegalArgumentException: maxPoolSize cannot be less than 1
at com.zaxxer.hikari.HikariConfig.setMaximumPoolSize(HikariConfig.java:658) ~[?:?]
at net.dzikoysk.funnyguilds.data.database.Database.(Database.java:29) ~[?:?]
at net.dzikoysk.funnyguilds.data.database.Database.getInstance(Database.java:101) ~[?:?]
at net.dzikoysk.funnyguilds.data.database.DatabaseBasic.load(DatabaseBasic.java:32) ~[?:?]
at net.dzikoysk.funnyguilds.data.Manager.(Manager.java:25) ~[?:?]
at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:140) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[23:01:09] [Server thread/INFO]: [FunnyGuilds] Disabling FunnyGuilds v4.0.0.2 Tribute-26f168c
[23:01:09] [Server thread/WARN]: java.lang.UnsupportedOperationException: AsynchronouslyRepeater is not setup!
[23:01:09] [Server thread/WARN]: at net.dzikoysk.funnyguilds.util.runnable.AsynchronouslyRepeater.getInstance(AsynchronouslyRepeater.java:32)
[23:01:09] [Server thread/WARN]: at net.dzikoysk.funnyguilds.FunnyGuilds.onDisable(FunnyGuilds.java:187)
[23:01:09] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
[23:01:09] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360)
[23:01:09] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
[23:01:09] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[23:01:09] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[23:01:09] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[23:01:09] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[23:01:09] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[23:01:09] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[23:01:09] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[23:01:09] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[23:01:09] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
[23:01:09] [Server thread/ERROR]: Error occurred while disabling FunnyGuilds v4.0.0.2 Tribute-26f168c (Is it up to date?)
java.lang.NullPointerException
at net.dzikoysk.funnyguilds.FunnyGuilds.onDisable(FunnyGuilds.java:187) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[PaperSpigot-1.8.8-R0.1.jar:git-PaperSpigot-"4c7641d"]

Z góry dzięki za pomoc!

**Comment by Kamilkime** [comment]
Co masz podane w configu, w ustawieniach połączenia z bazą MySQL, w sekcji **poolSize**?

**Comment by Marceleq1321** [comment]
A przyznam że tutaj może być własnie problem w tym pool-size bo mam domyślnie 16 
i nie za bardzo wiem o co z tym chodzi
Tutaj config 
``# Czy event PlayMoveEvent ma byc aktywny (odpowiada za wyswietlanie powiadomien o wejsciu na teren gildii)
event-move: true
# Co ile minut ma automatycznie zapisywac dane
data-interval: 1
# Typ zapisu danych
# Flat - Lokalne pliki
# MySQL - baza danych
data-type: 
  flat: false
  mysql: true

# Dane wymagane do polaczenia z baza
mysql: 
  hostname: ...
  port: 3306
  database: ...
  user: ...
  password: ...
  poolSize: 16

**Comment by Kamilkime** [comment]
Wrzuć cały config na pastebin i podeślij link (user'a i hasło do mysql zostaw puste)
https://pastebin.com/

**Comment by kacperduras** [comment]
Dobra, dzieki za zgloszenie bledu. Jutro sprawdze i dam znac jak to u mnie wyglada ;)

**Comment by Marceleq1321** [comment]
Testowana pierwsza baza danych
https://pastebin.com/JkWBR7U9
I tutaj drugi raz testowałem na innej
https://pastebin.com/VMe3r8dA

**Comment by Kamilkime** [comment]
@Marceleq1321 A jakbyś użył najnowszej wersji FG?

**Comment by Marceleq1321** [comment]
Ogólnie to testowałem każde praktycznie te nowsze FG i nic ;v

**Comment by Marceleq1321** [comment]
Ogólnie parę errorów po znikało lecz zostały takie:

> https://pastebin.com/nXQ0rB1A

**Comment by Kamilkime** [comment]
Wyłącz serwer, usuń z bazy danych tabele stworzone przez FG i odpal serwer na nowo

**Comment by Marceleq1321** [comment]
Sęk w tym że FG nie utworzył żadnych tabel ;v

**Comment by Kamilkime** [comment]
A czy na pewno podajesz dobre dane do logowania z MySQL? Niektóre hostingi mają inne IP do połączeń z poziomu serwera i inne do połączeń zewnętrznych

**Comment by Marceleq1321** [comment]
Na pewno testowałem na lokalnym + na serwerowej crafthost i tam jeszcze jednej

**Comment by Marceleq1321** [comment]
Jest w ogóle taka możliwość że to wina silnika? Sprawdzę to bo w sumie testowałem 2 silniki spigot i paper na 1.7.2 i 1.8 napisze jak zadziała

**Comment by Marceleq1321** [comment]
I mam jeszcze pytanie jeśli wszystko podepnę to plugin generuje wszystko automatycznie w bazie tak?
Czy jest możliwość np. dania gotowego pliku .sql może plugin ma jakiś problem z wygenerowaniem go?

**Comment by Kamilkime** [comment]
Nie no, wszystko jest w pluginie podane

**Comment by kacperduras** [comment]
```
Dobra, dzieki za zgloszenie bledu. Jutro sprawdze i dam znac jak to u mnie wyglada ;)
```

Sprawdziłem, u mnie działa - nie mogę odtworzyć błędu.

```
I mam jeszcze pytanie jeśli wszystko podepnę to plugin generuje wszystko automatycznie w bazie tak?
Czy jest możliwość np. dania gotowego pliku .sql może plugin ma jakiś problem z wygenerowaniem go?
```

Wszystko jest automatycznie generowane.

```
Jest w ogóle taka możliwość że to wina silnika? Sprawdzę to bo w sumie testowałem 2 silniki spigot i paper na 1.7.2 i 1.8 napisze jak zadziała
```

Wspieramy tylko 1.8+

**Comment by Kamilkime** [comment]
No, moim zdaniem to jest jakiś problem z samą bazą albo z połączeniem z nią

**Comment by Kamilkime** [comment]
@kacperduras zrób jakiś nowy label do issue, 'niemożliwe', czy coś

**Comment by MrGregorix** [comment]
Proponuje "możliwe-tak-bardzo-jak-to-że-eclipse-jest-dobrym-ide"

**Comment by kacperduras** [comment]
Zostawiam póki co tak, postaram się jakoś odtworzyć tą sytuację.

**Comment by Marceleq1321** [comment]
Oki dzięki wielkie za pomoc z waszej strony ;)
Spróbuje jakoś to rozwiązać jak mi się uda to napisze dla potomnych co się stało.

**Comment by Kamilkime** [comment]
Nie było tu odpowiedzi już od dawna, więc moim zdaniem do zamknięcia
