### ISSUE TITLE
Błąd w logach

### ISSUE THREAD

**Issue by Carvane** [FunnyGuilds/FunnyGuilds#665]
Jest to błąd z mojej winy czy z pluginu ? :D 

[20:08:24] [Craft Scheduler Thread - 9/INFO]: [Metrics] Connection timed out
[20:08:24] [Craft Scheduler Thread - 8/WARN]: java.net.ConnectException: Connection timed out
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at net.dzikoysk.funnyguilds.util.IOUtils.getContent(IOUtils.java:37)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at net.dzikoysk.funnyguilds.FunnyGuilds.lambda$update$0(FunnyGuilds.java:196)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[20:08:24] [Craft Scheduler Thread - 8/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:08:24] [Craft Scheduler Thread - 8/INFO]: [FunnyGuilds][Updater] > Failed to check the newest version of FunnyGuilds..

**Comment by Kamilkime** [comment]
Pokaż może jeszcze cały log

**Comment by ManiecTV** [comment]
Serwer dedykowany? VPS? czy Hosting? Wygląda jak zamknięty port DNS :D
(nie znajduje ipv4 po domenie [https://raw.githubusercontent.com/FunnyGuilds/FunnyGuilds/master/updater.txt]) jeśli vps/dedyk daj resultat komendy "curl https://raw.githubusercontent.com/FunnyGuilds/FunnyGuilds/master/updater.txt".

**Comment by kacperduras** [comment]
@Carvane Twoja - macierz blokuje tego typu połączenia na zewnątrz. Zamykam.
