### ISSUE TITLE
Problem Z Tabem!

### ISSUE THREAD

**Issue by EmersonYT** [FunnyGuilds/FunnyGuilds#689]
Mam taki problem, ponieważ włączając serwer komenda i wszystko inne działa, lecz gdy włączę tab w configu zaczyna wywalać błędy w consoli co sekundę i nadal nie działa.

Korzystam z oficjalnej wersji pluginu.

Błąd w konsoli po włączeniu w configu tabu:

```
[15:00:13 WARN]: Exception in thread "pool-3-thread-1123"
[15:00:13 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.0.2 Tribute-afb8589 generated an exception while executing task 34
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.dzikoysk.funnyguilds.util.element.tablist.impl.v1_8_R1.TablistImpl
        at net.dzikoysk.funnyguilds.util.element.tablist.AbstractTablist.createTablist(AbstractTablist.java:57)
        at net.dzikoysk.funnyguilds.util.runnable.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:61)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

Silnik - Craftbukkit-1.8-R0.1-SNAPSHOT-latest
Config:

```
# ~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~ #
#                                                                 #
#                        FunnyGuilds                     #
#                       4.0.1.1 Tribute                    #
#                                                                 #
# ~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~ #
# Wyswietlana nazwa pluginu
plugin-name: FunnyGuilds
# Maksymalna dlugosc nazwy gildii
name-length: 22
# Minimalna dlugosc nazwy gildii
name-min-length: 4
# Maksymalna dlugosc tagu gildii
tag-length: 4
# Minimalna dlugosc tagu gildii
tag-min-length: 2
# Minimalna ilosc graczy w gildii aby zaliczala sie do rankingu.
guild-min-members: 3
# Przedmioty wymagane do zalozenia gildii
# Dwukropek i metadata po nazwie przedmiotu sa opcjonalne
# Wzor: <ilosc> <przedmiot>:[metadata] [name:lore:enchant]
# Spacja = _ 
# Nowa linia lore = #
items: 
- 64 diamond_block
- 64 gold_block
- 64 iron_block
- 64 emerald_block
- 64 tnt
- 64 anvil
- 64 obsidian
# Przedmioty wymagane do zalozenia gildii dla osoby z uprawnieniem funnyguilds.vip
items-vip: 
- 32 diamond_block
- 32 gold_block
- 32 iron_block
- 32 emerald_block
- 32 tnt
- 32 anvil
- 32 obsidian
# Odleglosc od spawnu
create-distance: 100
# Blok, jaki pojawi sie pod nami po stworzeniu gildii
create-material: ender crystal
# Na jakim poziomie ma byc wyznaczone centrum gildii
# - Wpisz 0, jezeli ma byc ustalone przez gracza
create-center-y: 40
# Czy ma tworzyc pusta przestrzen dookola centrum gildii
create-center-sphere: true
# Maksymalna ilosc czlonkow w gildii
max-members: 15
# Swiaty, na ktorych powinno byc zablokowane tworzenie gildii
blockedworlds: 
- some_world
# Mozliwosc teleportacji do gildii
base-enable: true
# Czas oczekiwania na teleportacje (w sekundach)
base-delay: 5
# Koszt teleportacji do gildii (jezeli brak, wystarczy zrobic: base-items: [])
base-items: []
# Koszt dolaczenia do gildii (jezeli brak, wystarczy zrobic: join-items: [])
join-items: []
# Mozliwosc powiekszania gildii
enlarge-enable: true
# O ile powieksza teren gildii 1 poziom
enlarge-size: 5
# Koszt powiekszania gildii
# - kazdy myslnik, to 1 poziom gildii
enlarge-items: 
- 64 emerald block
- 128 emerald block
- 192 emerald block
- 256 emerald block
- 320 emerald block
- 384 emerald block
- 448 emerald block
- 512 emerald block
- 576 emerald block
- 640 emerald block
# Wielkosc regionu gildii
region-size: 50
# Minimalna odleglosc miedzy terenami gildii
region-min-distance: 250
# Czas wyswietlania powiadomienia na pasku powiadomien (w sekundach)
region-notification-time: 20
# Co ile moze byc wywolywany pasek powiadomien przez jednego gracza (w sekundach)
region-notification-cooldown: 60
# Blokowane komendy dla graczy spoza gildii na jej terenie
region-commands: 
- sethome
- esethome
# Czy mozna usunac gildie jezeli ktos spoza gildii jest na jej terenie
region-delete-if-near: true
# Przez ile sekund nie mozna budowac na terenie gildii po wybuchu
region-explode: 120
# Jaki ma byc zasieg pobieranych przedmiotow po wybuchu (jezeli chcesz wylaczyc, wpisz 0)
explode-radius: 3
# Jakie materialy i z jaka szansa maja byc niszczone po wybuchu
# <material>: <szansa (w %)
explode-materials: 
  obsidian: 5.0
  water: 25.0
  lava: 25.0
# Ile zyc ma gildia
war-lives: 3
# Po jakim czasie od zalozenia mozna zaatakowac gildie
war-protection: 24h
# Ile czasu trzeba czekac do nastepnego ataku na gildie
war-wait: 12h
# Jaka waznosc ma gildia po jej zalozeniu
validity-start: 365d
# Ile czasu dodaje przedluzenie gildii
validity-time: 1d
# Ile dni przed koncem wygasania mozna przedluzyc gildie (wpisz 0, jezeli funkcja ma byc wylaczona)
validity-when: 1d
# Koszt przedluzenia gildii
validity-items: 
- 100 emerald
# Ranking od ktorego rozpoczyna gracz
rank-start: 500
# Czy blokada nabijania rankingu na tych samych osobach powinna byc wlaczona
rank-farming-protect: true
# Czas (w sekundach) blokady nabijania rankingu po walce dwoch osob
rank-farming-cooldown: 120
# System rankingowy uzywany przez plugin, do wyboru:
# ELO - system bazujacy na rankingu szachowym ELO, najlepiej zbalansowany ze wszystkich trzech
# PERCENT - system, ktory obu graczom zabiera procent rankingu osoby zabitej
# STATIC - system, ktory zawsze zabiera iles rankingu zabijajacemu i iles zabitemu
rank-system: ELO
# Sekcja uzywana TYLKO jesli wybranym rank-system jest ELO!
# Lista stalych obliczen rankingowych ELO, uzywanych przy zmianach rankingu - im mniejsza stala, tym mniejsze zmiany rankingu
# Stale okreslaja tez o ile maksymalnie moze zmienic sie ranking pochodzacy z danego przedzialu
# Lista powinna byc podana od najmniejszych do najwiekszych rankingow i zawierac tylko liczby naturalne, z zerem wlacznie
# Elementy listy powinny byc postaci: "minRank-maxRank stala", np.: "0-1999 32"
# * uzyta w zapisie elementu listy oznacza wszystkie wartosci od danego minRank w gore, np.: "2401-* 16"
elo-constants: [0-1999 32, 2000-2400 24, 2401-* 16]
# Sekcja uzywana TYLKO jesli wybranym rank-system jest ELO!
# Dzielnik obliczen rankingowych ELO - im mniejszy, tym wieksze zmiany rankingu
# Dzielnik powinien byc liczba dodatnia, niezerowa
elo-divider: 400.0
# Sekcja uzywana TYLKO jesli wybranym rank-system jest ELO!
# Wykladnik potegi obliczen rankingowych ELO - im mniejszy, tym wieksze zmiany rankingu
# Wykladnik powinien byc liczba dodatnia, niezerowa
elo-exponent: 10.0
# Sekcja uzywana TYLKO jesli wybranym rank-system jest PERCENT!
# Procent rankingu osoby zabitej o jaki zmienia sie rankingi po walce
percent-rank-change: 1.0
# Sekcja uzywana TYLKO jesli wybranym rank-system jest STATIC!
# Punkty dawane osobie, ktora wygrywa walke
static-attacker-change: 15
# Sekcja uzywana TYLKO jesli wybranym rank-system jest STATIC!
# Punkty zabierane osobie, ktora przegrywa walke
static-victim-change: 10
# Czy pokazywac informacje przy kliknieciu prawym na gracza
info-player-enabled: true
# Cooldown pomiedzy pokazywanie informacji przez prawy klik (w sekundach)
info-player-cooldown: 0
# Czy trzeba kucac, zeby przy klikniecu prawym na gracza wyswietlilo informacje o nim
info-player-sneaking: true
# Czy czlonkowie gildii moga sobie zadawac obrazenia (domyslnie)
damage-guild: false
# Czy sojuszniczy moga sobie zadawac obrazenia
damage-ally: false
# Wyglad znaczika {TAG} wstawionego w format chatu
chat-guild: "&8{TAG} "
# Wyglad znaczika {RANK} wstawionego w format chatu
chat-rank: "&8{RANK} "
# Wyglad znaczika {POINTS} wstawionego w format chatu
chat-points: "&8{POINTS} "
# Symbol od ktorego zaczyna sie wiadomosc do gildii gildii
chat-priv: "!"
# Symbol od ktorego zaczyna sie wiadomosc do sojusznikow gildii
chat-ally: "!!"
# Symbol od ktorego zaczyna sie wiadomosc do wszystkich gildii
chat-global: "!!!"
# Wyglad wiadomosci wysylanej na czacie gildii
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-priv-design: "&bCZAT GILDYJNY &8{PLAYER} &8» &7{MESSAGE}"
# Wyglad wiadomosci wysylanej na czacie sojusznikow dla sojusznikow
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-ally-design: "&6CZAT SOJUSZNICZY &8{TAG} &8{PLAYER} &8» &7{MESSAGE}"
# Wyglad wiadomosci wysylanej na czacie globalnym gildii
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-global-design: "&1CZAT GLOBALNY GILDII &8{TAG} &8{PLAYER} &8» &7{MESSAGE}"
# Wyglad tagu osob w gildii
prefix-our: "&8{TAG}&8 "
# Wyglad tagu gildii sojuszniczej
prefix-allies: "&8{TAG}&8 "
# Wyglad tagu gildii neutralnej (widziany rowniez przez graczy bez gildii)
prefix-other: "&8{TAG}&8 "
# Czy wlaczyc dummy z punktami
dummy-enable: true
# Wyglad nazwy wyswietlanej (suffix, za punktami)
dummy-suffix: pkt
# Wyglad listy graczy. Przedzial od 1 do 80
# > Spis zmiennych gracza:
# {PLAYER} - nazwa gracza
# {PING} - ping gracza
# {POINTS} - punkty gracza
# {POSITION} - pozycja gracza w rankingu
# {KILLS} - liczba zabojstw gracza
# {DEATHS} - liczba smierci gracza
# > Spis zmiennych gildyjnych:
# {G-NAME} - nazwa gildii do ktorej nalezy gracz
# {G-TAG} - tag gildii gracza
# {G-OWNER} - wlasciciel gildii
# {G-LIVES} - liczba zyc gildii
# {G-ALLIES} - liczba sojusznikow gildii
# {G-POINTS} - punkty gildii
# {G-POSITION} - pozycja gildii gracza w rankingu
# {G-KILLS} - suma zabojstw czlonkow gildii
# {G-DEATHS} - suma smierci czlonkow gildii
# {G-MEMBERS-ONLINE} - ilosc czlonkow gildii online
# {G-MEMBERS-ALL} - ilosc wszystkich czlonkow gildii
# > Spis pozostalych zmiennych:
# {ONLINE} - liczba graczy online
# {TPS} - TPS serwera
# {SECOND} - Sekunda
# {MINUTE} - Minuta
# {HOUR} - Godzina
# {PTOP-<pozycja>} - Gracz na podanym miejscu w rankingu (np. {PTOP-1}, {PTOP-60})
# {GTOP-<pozycja>} - Gildia na podanej pozycji w rankingu (np. {GTOP-1}, {PTOP-50})
player-list: 
  1: ""
  2: ""
  3: ""
  4: ""
  5: "  &4SERWEREK"
  6: ""
  7: ""
  8: ""
  9: ""
  10: "     &7TOP GRACZY"
  11: "    &7INFORMACJE"
  12: "     &7TOP GILDII"
  13: ""
  14: ""
  15: ""
  16: "&71. &a{PTOP-1}"
  17: ""
  18: "&71. &a{GTOP-1}"
  19: "&72. &a{PTOP-2}"
  20: "&7Ranking: &a{POINTS}"
  21: "&72. &a{GTOP-2}"
  22: "&73. &a{PTOP-3}"
  23: "&7Gildia: &a{GUILD}"
  24: "&73. &a{GTOP-3}"
  25: "&74. &a{PTOP-4}"
  26: "&7Zabójstwa: &a{KILLS}"
  27: "&74. &a{GTOP-4}"
  28: "&75. &a{PTOP-5}"
  29: "&7Smierci: &a{DEATHS}"
  30: "&75. &a{GTOP-5}"
  31: "&76. &a{PTOP-6}"
  32: "&7Online: &a{ONLINE}"
  33: "&76. &a{GTOP-6}"
  34: "&77. &a{PTOP-7}"
  35: ""
  36: "&77. &a{GTOP-7}"
  37: "&78. &a{PTOP-8}"
  38: "&7TPS: &a{TPS}"
  39: "&78. &a{GTOP-8}"
  40: "&79. &a{PTOP-9}"
  41: ""
  42: "&79. &a{GTOP-9}"
  43: "&710. &a{PTOP-10}"
  44: ""
  45: "&710. &a{GTOP-10}"
  46: "&711. &a{PTOP-11}"
  47: "     &7Strona WWW"
  48: "&711. &a{GTOP-11}"
  49: "&712. &a{PTOP-12}"
  50: "  &awww.stronka.pl"
  51: "&712. &a{GTOP-12}"
  52: "&713. &a{PTOP-13}"
  53: "     &7Teamspeak3"
  54: "&713. &a{GTOP-13}"
  55: ""
  56: "    &a--"
  57: ""
  58: ""
  59: ""
  60: ""
# Wyglad naglowka w liscie graczy.
player-list-header: "&7FunnyGuilds &b4.0.1.1 Tribute"
# Wyglad stopki w liscie graczy.
player-list-footer: "&7GODZINKA: &8{HOUR}:{MINUTE}:{SECOND}"
# Ilosc pingu pokazana przy kazdej komorce.
player-list-ping: 0
# Tablista wlaczona
player-list-enable: true
# Co ile sekund ma odswiezac liste graczy
player-list-interval: 1
# Wyglad punktow wyswietlanych przy gildii w rankingu
player-list-points: "&7{POINTS}"
# Czy tagi gildii powinny byc pokazywane wielka litera
# Dziala dopiero po zrestartowaniu serwera
guild-tag-uppercase: false
# Czy wlaczyc tlumaczenie nazw przedmiotow przy zabojstwie
translated-materials-enable: true
# Tlumaczenia nazw przedmiotow przy zabojstwie
# Wypisywac w formacie nazwa_przedmiotu: "tlumaczona nazwa przedmiotu"
translated-materials-name: 
  diamond_sword: "&3diamentowy miecz"
  iron_sword: "&7zelazny miecz"
# Nazwy komend
commands: 
  funnyguilds: 
    name: 'funnyguilds'
    aliases: 
    - fg

  guild: 
    name: 'gildia'
    aliases: 
    - gildie
    - g

  create: 
    name: 'zaloz'
    aliases: []

  delete: 
    name: 'usun'
    aliases: []

  confirm: 
    name: 'potwierdz'
    aliases: []

  invite: 
    name: 'zapros'
    aliases: []

  join: 
    name: 'dolacz'
    aliases: []

  leave: 
    name: 'opusc'
    aliases: []

  kick: 
    name: 'wyrzuc'
    aliases: []

  base: 
    name: 'baza'
    aliases: []

  enlarge: 
    name: 'powieksz'
    aliases: []

  ally: 
    name: 'sojusz'
    aliases: []

  items: 
    name: 'przedmioty'
    aliases: []

  break: 
    name: 'rozwiaz'
    aliases: []

  info: 
    name: 'info'
    aliases: []

  player: 
    name: 'gracz'
    aliases: []

  top: 
    name: 'top'
    aliases: 
    - top10

  validity: 
    name: 'przedluz'
    aliases: []

  leader: 
    name: 'lider'
    aliases: 
    - zalozyciel

  deputy: 
    name: 'zastepca'
    aliases: []

  ranking: 
    name: 'ranking'
    aliases: []

  setbase: 
    name: 'ustawbaze'
    aliases: 
    - ustawdom

  pvp: 
    name: 'pvp'
    aliases: 
    - ustawpvp

  # Komendy administratora
  admin: 
    main: ga
    add: ga dodaj
    delete: ga usun
    kick: ga wyrzuc
    teleport: ga tp
    points: ga points
    kills: ga kills
    deaths: ga deaths
    ban: ga ban
    lives: ga zycia
    move: ga przenies
    unban: ga unban
    validity: ga przedluz
    name: ga nazwa


# Czy event PlayMoveEvent ma byc aktywny (odpowiada za wyswietlanie powiadomien o wejsciu na teren gildii)
event-move: true
# Co ile minut ma automatycznie zapisywac dane
data-interval: 1
# Typ zapisu danych
# Flat - Lokalne pliki
# MySQL - baza danych
data-type: 
  flat: true
  mysql: false

# Dane wymagane do polaczenia z baza
mysql: 
  hostname: localhost
  port: 3306
  database: db
  user: root
  password: passwd
  poolSize: 16
```

**Comment by Kamilkime** [comment]
Użyj silnika na wersję min. 1.8.8

**Comment by EmersonYT** [comment]
ale tak to nie będę mógł mieć serwera na 1.8 a stroszkę mi na tym zalezy :D

**Comment by Kamilkime** [comment]
No... A 1.8.8 nie wspiera przypadkiem wszystkich wersji 1.8?

**Comment by EmersonYT** [comment]
Zapomniałem... XD czyli z wersji 1.8 ktoś też wejdzie no nie?

**Comment by Kamilkime** [comment]
Nom

**Comment by EmersonYT** [comment]
No zmieniłem na 1.8.8 i dalej wywala blad i nie działa

[15:10:27 WARN]: Exception in thread "pool-3-thread-109"
[15:10:27 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.0.2 Tribute-afb8589 generated an exception while executing task 34
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at net.dzikoysk.funnyguilds.util.runnable.Ticker.getRecentTPS(Ticker.java:30)
        at net.dzikoysk.funnyguilds.util.element.tablist.variable.DefaultTablistVariables.lambda$install$10(DefaultTablistVariables.java:39)
        at net.dzikoysk.funnyguilds.util.element.tablist.variable.impl.SimpleTablistVariable.get(SimpleTablistVariable.java:29)
        at net.dzikoysk.funnyguilds.util.element.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:23)
        at net.dzikoysk.funnyguilds.util.element.tablist.AbstractTablist.putVars(AbstractTablist.java:129)
        at net.dzikoysk.funnyguilds.util.element.tablist.impl.v1_8_R3.TablistImpl.send(TablistImpl.java:92)
        at net.dzikoysk.funnyguilds.util.runnable.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:64)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by Kamilkime** [comment]
Hmm, nie wiem, czy to nie wymaga spigota do poprawnego działania

**Comment by EmersonYT** [comment]
Ale wszystkie pluginy które działają na bukkit bedą działały na spigot czy nie wszystkie?

**Comment by dzikoysk** [comment]
Będą działały normalnie

**Comment by EmersonYT** [comment]
Tak ale i tak mam problem bo teraz jak mam funnyguilds na spigot 1.8.8 to mi nie działa plugin na drop XD

**Comment by Kamilkime** [comment]
Emm, a co to za plugin?

**Comment by EmersonYT** [comment]
mh-drop

**Comment by Kamilkime** [comment]
A, to ciul wie czemu nie działa

**Comment by EmersonYT** [comment]
a masz chwile na discordzie popisac? XD

**Comment by Kamilkime** [comment]
Dobra, to #689 do zamknięcia

**Comment by dzikoysk** [comment]
Zamkniemy, jak  tylko @insertt naprawi pobieranie liczby tps
