### ISSUE TITLE
NPE while clicking on not related with FunnyGuilds ender crystal

### ISSUE THREAD

**Issue by insertt** [FunnyGuilds/FunnyGuilds#700]
`[01:09:01 WARN]: java.lang.NullPointerException
[01:09:01 WARN]:        at net.dzikoysk.funnyguilds.system.war.WarListener.use(WarListener.java:59)
[01:09:01 WARN]:        at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:79)
[01:09:01 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:107)
[01:09:01 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:87)
`

**Comment by dzikoysk** [comment]
🍾 🎈 🎆

**Comment by MrGregorix** [comment]
Powieneś to wstawić o 00:00 1 stycznia, przez ciebie dzikoysk zmarnował szampana na sylwestra
