### ISSUE TITLE
FunnyGuilds 4.0.2 spigot 1.8.8+ błąd

### ISSUE THREAD

**Issue by st4ge000** [FunnyGuilds/FunnyGuilds#714]
Witam, ostatniego czasu postanowiłem wgrać FunnyGuilds na swój serwer. Z racji, że mam Spigot 1.8x wgrałem FunnyGuilds 4.0.2 1.8.8+ spigot. Na początku jest wszystko okej, po jakimś czasie wywala błąd:

Po /funnyguids reload:
[17:48:58 ERROR]: Could not load 'plugins/funnyguilds-4.0.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:864) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.Bukkit.reload(Bukkit.java:301) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:753) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:326) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:290) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_121]
at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_121]
at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_121]
at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_121]
at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_121]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
... 13 more

W trakcie:
[17:52:37 WARN]: Exception in thread "FunnyGuilds | IndependentThread"
[17:52:37 WARN]: java.lang.NoClassDefFoundError: com/mojang/authlib/GameProfile
[17:52:37 WARN]:at net.dzikoysk.funnyguilds.basic.OfflineUser.init(OfflineUser.java:72)
[17:52:37 WARN]:at net.dzikoysk.funnyguilds.basic.OfflineUser.<init>(OfflineUser.java:31)
[17:52:37 WARN]:at net.dzikoysk.funnyguilds.basic.User.getOfflineUser(User.java:322)
[17:52:37 WARN]:at net.dzikoysk.funnyguilds.util.element.Dummy.initialize(Dummy.java:53)
[17:52:37 WARN]:at net.dzikoysk.funnyguilds.util.element.Dummy.<init>(Dummy.java:20)
[17:52:37 WARN]:at net.dzikoysk.funnyguilds.basic.User.getDummy(User.java:214)
[17:52:37 WARN]:at net.dzikoysk.funnyguilds.util.element.DummyManager.updateScore(DummyManager.java:17)
[17:52:37 WARN]:at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:46)
[17:52:37 WARN]:at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:107)
[17:52:37 WARN]:at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:87)
[17:52:37 WARN]: Caused by: java.lang.ClassNotFoundException: com.mojang.authlib.GameProfile
[17:52:37 WARN]:at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[17:52:37 WARN]:at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[17:52:37 WARN]:at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[17:52:37 WARN]:at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:52:37 WARN]:at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:52:37 WARN]:... 10 more

W trakcie:
[19:07:42 WARN]: java.net.ConnectException: Connection timed out (Connection timed out)
[19:07:42 WARN]:at java.net.PlainSocketImpl.socketConnect(Native Method)
[19:07:42 WARN]:at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[19:07:42 WARN]:at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[19:07:42 WARN]:at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[19:07:42 WARN]:at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[19:07:42 WARN]:at java.net.Socket.connect(Socket.java:589)
[19:07:42 WARN]:at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[19:07:42 WARN]:at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[19:07:42 WARN]:at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[19:07:42 WARN]:at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[19:07:42 WARN]:at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[19:07:42 WARN]:at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[19:07:42 WARN]:at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[19:07:42 WARN]:at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[19:07:42 WARN]:at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
[19:07:42 WARN]:at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
[19:07:42 WARN]:at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[19:07:42 WARN]:at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
[19:07:42 WARN]:at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[19:07:42 WARN]:at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[19:07:42 WARN]:at net.dzikoysk.funnyguilds.util.IOUtils.getContent(IOUtils.java:37)
[19:07:42 WARN]:at net.dzikoysk.funnyguilds.FunnyGuilds.lambda$update$0(FunnyGuilds.java:212)
[19:07:42 WARN]:at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[19:07:42 WARN]:at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:07:42 WARN]:at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[19:07:42 WARN]:at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[19:07:42 WARN]:at java.lang.Thread.run(Thread.java:745)
[19:07:42 INFO]: [FunnyGuilds][Updater] > Failed to check the newest version of FunnyGuilds..
[19:08:33 WARN]: java.net.ConnectException: Connection timed out (Connection timed out)
[19:08:33 WARN]:at java.net.PlainSocketImpl.socketConnect(Native Method)
[19:08:33 WARN]:at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[19:08:33 WARN]:at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[19:08:33 WARN]:at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[19:08:33 WARN]:at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[19:08:33 WARN]:at java.net.Socket.connect(Socket.java:589)
[19:08:33 WARN]:at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[19:08:33 WARN]:at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[19:08:33 WARN]:at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[19:08:33 WARN]:at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[19:08:33 WARN]:at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[19:08:33 WARN]:at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[19:08:33 WARN]:at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[19:08:33 WARN]:at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[19:08:33 WARN]:at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
[19:08:33 WARN]:at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
[19:08:33 WARN]:at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[19:08:33 WARN]:at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
[19:08:33 WARN]:at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[19:08:33 WARN]:at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[19:08:33 WARN]:at net.dzikoysk.funnyguilds.util.IOUtils.getContent(IOUtils.java:37)
[19:08:33 WARN]:at net.dzikoysk.funnyguilds.util.Version.lambda$isNewAvailable$0(Version.java:14)
[19:08:33 WARN]:at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[19:08:33 WARN]:at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:08:33 WARN]:at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[19:08:33 WARN]:at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[19:08:33 WARN]:at java.lang.Thread.run(Thread.java:745)

**Comment by Kamilkime** [comment]
Pobierz FG na nowo, coś chyba jest nie tak z samym plikiem .jar

**Comment by Kamilkime** [comment]
A błędy, które dałeś, chyba pochodzą z różnych serwerów - raz jest w błędzie wersja MC 1.7.10, raz 1.8.8

**Comment by st4ge000** [comment]
kamlikime, wersję serwera jest 1.7x - 1.8x, ale wykorzystywana jest tylko 1.8

**Comment by insertt** [comment]
Skoro wersja serwera jest 1.7.x - 1.8x, a wykorzystujesz tylko 1.8, to wgraj silnik 1.8.

**Comment by Kamilkime** [comment]
No, ale żeby FG dobrze działało - serwer musi być min. na 1.8, najlepiej min. na 1.8.8. Silnik 1.7-1.8 bazuje na kodzie 1.7.10, więc się nie nadaje

**Comment by st4ge000** [comment]
Ale nawet jeżeli było 1.8x występował ten sam błąd...

**Comment by Kamilkime** [comment]
No, bo jeszcze jest coś źle z plikiem .jar - pobierz FG na nowo i używaj wersji min. 1.8

**Comment by st4ge000** [comment]
Spigot 1.8.8 RO-1, pobrałem i wgrałem na nowo, błąd po jakimś czasie w konsoli (po restarcie itd):



[18:11:14] [Craft Scheduler Thread - 0/WARN]: java.net.ConnectException: Connection timed out (Connection timed out)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at net.dzikoysk.funnyguilds.util.IOUtils.getContent(IOUtils.java:37)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at net.dzikoysk.funnyguilds.FunnyGuilds.lambda$update$0(FunnyGuilds.java:212)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:11:14] [Craft Scheduler Thread - 0/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:11:14] [Craft Scheduler Thread - 0/INFO]: [FunnyGuilds][Updater] > Failed to check the newest version of FunnyGuilds..
Nw jeszcze czy to coś ma do tego błędu ale przy pobieraniu wyskakuje mi że plik (fg) może

**Comment by st4ge000** [comment]
...plik tego typu może uszkodzić komputer. i jest przerwij/zachowaj

**Comment by insertt** [comment]
`[18:11:14] [Craft Scheduler Thread - 0/WARN]: java.net.ConnectException: Connection timed out (Connection timed out)`
Coś blokuje połączenie z updaterem funnyguilds, sprawdź firewalla.

**Comment by st4ge000** [comment]
Firewall mam wyłączony

**Comment by st4ge000** [comment]
Na wersji 1.9.2 to samo...

**Comment by hamsterofficial** [comment]
Kolego Funnyguilds nie pod 1.9.2 tylko pod 1.8.8 wiec po co sprawdzasz? xD

**Comment by st4ge000** [comment]
Oj nie, rozumiem, że fg jest pod 1.8.8+, więc 1.9.2 powinno obejmować?

**Comment by Kamilkime** [comment]
Tak, FG jest kompatybilne z każdą wersją od 1.8, aż po 1.12.2. Co do błędu - coś nie pozwala na połączenie serwera ze stroną FG

**Comment by st4ge000** [comment]
Kamilkime, mam pytanie dotyczące tego "połączenia", mianowicie serwer jest na hostingu jakimśtam, więc na jakiej zasadzie to działa? To jest moja wina, czy hostingu? Bo jeżeli moja, to ktoś inny powinien nie mieć takiego błędu?

**Comment by st4ge000** [comment]
enderchest

**Comment by st4ge000** [comment]
Enderchest ma zakładkę "Zapora sieciowa", mam ją wyłączoną (z góry uprzedzam).
Napisałem do BOK'u enderchest'a, odpowiedzi, które dostałem:
Cytuję: "Nasz hosting nie blokuje tego pluginu, jeśli korzysta on z zewnętrznego adresu IP, to proszę go uzyskać i dodać do białej listy zapory sieciowej. Z tego co nam wiadomo to plugin ten nie wykorzystuje żadnego zewnętrznego adresu IP."

**Comment by st4ge000** [comment]
Miałem jeszcze zapytać czy może to byś wina dostawcy internetu?

**Comment by Kamilkime** [comment]
Hmm, no, szansa na to jest raczej żadna, no ale w sumie byłoby to możliwe

**Comment by st4ge000** [comment]
Nie wiem czy to ten sam błąd, bo się nie znam, ale na innym hostingu:
[21:28:15 ERROR]: Could not load 'plugins/funnyguilds-4.0.1.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/dzikoysk/funnyguilds/FunnyGuilds : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot_1.8.6.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot_1.8.6.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot_1.8.6.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot_1.8.6.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot_1.8.6.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot_1.8.6.jar:git-Spigot-044d928-e8c6403]
	at java.lang.Thread.run(Thread.java:748) [?:1.7.0_151]
Caused by: java.lang.UnsupportedClassVersionError: net/dzikoysk/funnyguilds/FunnyGuilds : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442) ~[?:1.7.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64) ~[?:1.7.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354) ~[?:1.7.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348) ~[?:1.7.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347) ~[?:1.7.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot_1.8.6.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_1.8.6.jar:git-Spigot-044d928-e8c6403]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_151]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_151]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot_1.8.6.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot_1.8.6.jar:git-Spigot-044d928-e8c6403]
	... 6 more

**Comment by hamsterofficial** [comment]
Nie umie załadować pluginu, a wgl dlaczego korzystasz z spigota 1.8.6 wez 1.8.8

**Comment by insertt** [comment]
`Caused by: java.lang.UnsupportedClassVersionError: net/dzikoysk/funnyguilds/FunnyGuilds : Unsupported major.minor version 52.0`
Zaktualizuj JRE, FunnyGuilds korzysta z Javy 8.

**Comment by st4ge000** [comment]
Następny błąd, kiedy założyłem gildie, po 5 sekundach (?) ona wygasła.

**Comment by st4ge000** [comment]
Wgrałem starszą wersję, mianowicie 3.9.9.1 Cleaned i działa normalnie, update nie wariuje, wszystko jest okej...

**Comment by insertt** [comment]
Podeślij log startowy oraz output komendy /version

**Comment by RafiXDD** [comment]
na spigot 1.7-1.8 mialem taki sam blad zmienielem versje na 1.8.8 i wszystko dzialalo ;)

**Comment by hamsterofficial** [comment]
Błąd jest taki że zepsules **plugin.yml** i dlatego wywala co błąd przy startowaniu, i dlatego tez ci wywala w trakcie serwera.

**Comment by hamsterofficial** [comment]
A potem jest taki że nie umie się połączyć z updaterem.

**Comment by st4ge000** [comment]
hamster tylko to wygląda tak, że ja go wgrywam takiego, jakiego pobrałem

**Comment by hamsterofficial** [comment]
To tak, zbuduj przez funnycreator i zrob tak zeby laczyl sie z updaterem.
