### ISSUE TITLE
Błąd podczas uruchamiania FunnyGuilds.

### ISSUE THREAD

**Issue by marcinkowalczyk2** [FunnyGuilds/FunnyGuilds#719]
Heja, zbudowałem sobie FunnyGuilds FunnyCreatorem i wrzuciłem na locala i wszystko działało (configu nie zmieniałem, zmieniłem tylko nazwę pliku na devGuilds). Wrzuciłem na serwer na hostingu (z tym samym silnikiem co na localu) i się posypało, pluginu nawet nie pokazuje pod /plugins.
Error:
Could not load 'plugins/devGuilds.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/dzikoysk/funnyguilds/FunnyGuilds : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:739) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.7.0_151]
Caused by: java.lang.UnsupportedClassVersionError: net/dzikoysk/funnyguilds/FunnyGuilds : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442) ~[?:1.7.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64) ~[?:1.7.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354) ~[?:1.7.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348) ~[?:1.7.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347) ~[?:1.7.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_151]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_151]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot_1.8.6.jar:git-Spigot-21fe707-e1ebe52]
	... 14 more

**Comment by Kamilkime** [comment]
FG wymaga min. Javy 8, ty masz 7

**Comment by marcinkowalczyk2** [comment]
Dzięki, myślałem że hosting ma automatycznie jave 8 :)

**Comment by Kamilkime** [comment]
To zamknij issue

**Comment by insertt** [comment]
Problem został rozwiązany - gdybyś miał jakiekolwiek pytanie/problem, stwórz nowy issue z opisem :-)
