### ISSUE TITLE
Problem z wylogowywaniem podczas walki

### ISSUE THREAD

**Issue by MattiGB** [FunnyGuilds/FunnyGuilds#756]
Cześć,
Napotkałem taki oto problem

```
[01:30:17] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to FunnyGuilds v4.1.0 Tribute-a26348e
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[spigot.jar:git-Paper-1327]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-Paper-1327]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Paper-1327]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [spigot.jar:git-Paper-1327]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [spigot.jar:git-Paper-1327]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:414) [spigot.jar:git-Paper-1327]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:449) [spigot.jar:git-Paper-1327]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:106) [spigot.jar:git-Paper-1327]
	at net.minelink.ctplus.listener.InstakillListener.onCombatLog(InstakillListener.java:27) [CombatTagPlus.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor370.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) [spigot.jar:git-Paper-1327]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [spigot.jar:git-Paper-1327]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Paper-1327]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [spigot.jar:git-Paper-1327]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [spigot.jar:git-Paper-1327]
	at net.minelink.ctplus.listener.PlayerListener.onLogout(PlayerListener.java:77) [CombatTagPlus.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor379.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) [spigot.jar:git-Paper-1327]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [spigot.jar:git-Paper-1327]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Paper-1327]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [spigot.jar:git-Paper-1327]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [spigot.jar:git-Paper-1327]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:429) [spigot.jar:git-Paper-1327]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1147) [spigot.jar:git-Paper-1327]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:342) [spigot.jar:git-Paper-1327]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) [spigot.jar:git-Paper-1327]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [spigot.jar:git-Paper-1327]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [spigot.jar:git-Paper-1327]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [spigot.jar:git-Paper-1327]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [spigot.jar:git-Paper-1327]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.basic.User.killedBy(User.java:323) ~[?:?]
	at net.dzikoysk.funnyguilds.listener.PlayerDeath.onDeath(PlayerDeath.java:96) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor122.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[spigot.jar:git-Paper-1327]
	... 30 more
```

Dzieje się tak gdy dany gracz wychodzi z serwera podczas walki. Testowałem to na pluginie Combat Tag Plus oraz CombatLogX. Niestety problem jest ten sam.
Na czystym configu również dzieje się tak samo.
Wersja silnika jaki używam to najnowszy build paperspigota 1.12.2.

Mam nadzieję, że to nie jest błąd wynikający z mojego przeoczenia :D

**Comment by Kamilkime** [comment]
No... Ale jak... Hashmapa musiałaby być null'em, a nie może przecież, jest inicjowana...
https://github.com/FunnyGuilds/FunnyGuilds/blob/master/src/main/java/net/dzikoysk/funnyguilds/basic/User.java#L51

**Comment by MattiGB** [comment]
Testowałem jeszcze inne silniki no i niestety efekt jest ten sam :P

**Comment by kacperduras** [comment]
Błąd zależy od wcześniej wspomnianego pluginu `CombatLog`. Bez jego obecności FG działa bez żadnych zarzutów, zamykam.

**Comment by insertt** [comment]
Udało mi się zreprodukować ten błąd, za chwilę pushnę fix.
