### ISSUE TITLE
NPE podczas śmierci gracza

### ISSUE THREAD

**Issue by T0fficzeG** [FunnyGuilds/FunnyGuilds#759]
Could not pass event PlayerDeathEvent to FunnyGuilds v4.1.0 Tribute-a26348e
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-"8b18730"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:425) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:822) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1382) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-"8b18730"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
at net.dzikoysk.funnyguilds.basic.User.killedBy(User.java:323) ~[?:?]
at net.dzikoysk.funnyguilds.listener.PlayerDeath.onDeath(PlayerDeath.java:96) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]

Wersja : 1.8.8
PaperSpigot
FunnyGuilds 4.10

**Comment by T0fficzeG** [comment]
Pomocy szybko ;(

**Comment by kacperduras** [comment]
Zbuduj FG za pośrednictwem [FunnyCreatora](https://github.com/FunnyGuilds/FunnyCreator), zostało to naprawione w e18124ef9b3c6820d33845c62b36129a0e6767b6. Dzisiaj wydam wersje stable, jak wszystko przetestuje i sprawdzę że będzie ok. Daj znać czy pomogło ;)

**Comment by kacperduras** [comment]
Zaraz wydaje update - wszystko działa jak powinno :D

**Comment by T0fficzeG** [comment]
Czyli musze pobrac funnycreator?

**Comment by T0fficzeG** [comment]
Sorry ale jestem nowy ;(

**Comment by Kamilkime** [comment]
Wyszedł już update 4.1.1, możesz go pobrać [stąd](https://github.com/FunnyGuilds/FunnyGuilds/releases/tag/4.1.1)

**Comment by T0fficzeG** [comment]
dziekuje! ale ja jestem tempy przepraszam za moja glupote ;c

**Comment by T0fficzeG** [comment]
Musze pobrac koniecznie funnycreatora czy wystarczy nowe funnyguilds?
Bo nie ogarniam zbyt nio FunnyCreatora ;(

**Comment by Kamilkime** [comment]
No, teraz już tylko nowe FG, FunnyCreator jest do budowania nieoficjalnych wersji

**Comment by T0fficzeG** [comment]
okej !! Dziekuje ! Sprawdze czy dziala

**Comment by T0fficzeG** [comment]
Kamilkime pytanie - umiesz zrobic config tak aby byl pod serwer pvp chodzi mi oto zeby nie robilo cuboidu itp na typu serwerach centrumpvp lub janpvp

**Comment by Kamilkime** [comment]
No, przejrzyj sobie config - jest tam m.in. opcja od wyłączenia regionów

**Comment by T0fficzeG** [comment]
dzieki!

**Comment by T0fficzeG** [comment]
Nadal nie dziala ;( 
Could not pass event PlayerDeathEvent to FunnyGuilds v4.1.1 Tribute-9c8c3b0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-"8b18730"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:425) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:822) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1382) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-"8b18730"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
at net.dzikoysk.funnyguilds.basic.User.killedBy(User.java:323) ~[?:?]
at net.dzikoysk.funnyguilds.listener.PlayerDeath.onDeath(PlayerDeath.java:100) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"8b18730"]
... 23 more

**Comment by T0fficzeG** [comment]
mam moze jakies skrypty/pluginy zle?

**Comment by T0fficzeG** [comment]
:(
