### ISSUE TITLE
Błąd z tagami nad głową

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyGuilds#769]
mam problem z tagami nad głową w pluginie który występuje od dawna.

a mianowicie, tagi raz są a raz ich nie ma.

+ przydała by się opcja wyłączenia ich w configu, ponieważ są niekompatybilne s bungeecord'em
i założenie gildii kończy się na wyrzuceniu wszystkich graczy z serwera z błędem "Team {TAG} already exist in this scoreboard."
Gdzie {TAG} to tag założonej gildii.

**Comment by MentosPL** [comment]
Po rozmowie na Discordzie dodaje szczegóły:
Błędy w konsoli serwera: brak
błędy w konsoli bungeecorda: brak
co spowodowało wystąpienie problemu: gracz założył gildię.
config FG: domyślny, tylko zmieniona kolorystyka na &6 i ustawione itemy na gildie i wyłaczony tab.
Wersja serwera: 1.12.2 paperspigot newest (czy bukkit czy spigot błąd występuje)
Wersja FG: 4.1.0 (błąd występuje od 3.9.x.x więc skoro do teraz nikt nic nie wieszał to nie ma to znaczenia)
Wersja Bungeecord: BungeeCord-Bootstrap:1.12-SNAPSHOT:5e67309:183 (1.12.2)

Więcej nie wiem ¯\_(ツ)_/¯

**Comment by MentosPL** [comment]
Wszystko najnowsze (FG, Bungeecord i PaperSpigot):
![image](https://user-images.githubusercontent.com/32804020/36923261-f947c1da-1e6a-11e8-897b-62649965e026.png)
błąd bungeecord:
[m>[2K 22:41:52 [SEVERE] [MentosPL] <-> DownstreamBridge <-> [xtrem] - encountered exception
java.lang.IllegalArgumentException: Team DARK already exists in this scoreboard
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73)
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:188)
at net.md_5.bungee.protocol.packet.Team.handle(Team.java:102)
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
at java.lang.Thread.run(Thread.java:745)
[m>[2K 22:41:52 [INFO] [MentosPL] disconnected with: [0;37;1mIllegalArgumentException : Team DARK already exists in this scoreboard @ com.google.common.base.Preconditions:191
[m>[2K 22:41:52 [INFO] [MentosPL] <-> DownstreamBridge <-> [xtrem] has disconnected
[m>[2K 22:41:52 [INFO] [MentosPL] -> UpstreamBridge has disconnected

W logach serwera jest tylko że wyszedłem z serwera (Disconnected)

**Comment by insertt** [comment]
Podaj listę pluginów na serwerze.

**Comment by MentosPL** [comment]
bungeecord, funnyguilds, to nie ma związku z innymi pluginami. każdy plugin który używa scoreboarda wywala błąd, nie tylko wasz.

**Comment by Kamilkime** [comment]
Zapytał o listę pluginów - albo ją podajesz, albo zamknij issue

**Comment by Kamilkime** [comment]
Każdy zawsze jest pewien, że to coś tam, że to nie jakiś inny plugin - może jednak zostawcie tę decyzję programistom pluginu, z którym macie problem, a nie podejmujcie ją sami?

**Comment by kacperduras** [comment]
```
każdy plugin który używa scoreboarda wywala błąd, nie tylko wasz.
```

To już nie jest wina FG, tylko konfiguracji serwera, konfiguracj proxy lub oprogramowania z którego korzystasz. Zamykam.
