### ISSUE TITLE
NPE przy asystach

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyGuilds#787]
```
[20:30:40] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to FunnyGuilds v4.1.0 Tribute-04f76af
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:425) [server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:89) [server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:493) [server.jar:git-PaperSpigot-"4c7641d"]
	at com.jackproehl.plugins.listeners.PlayerQuitListener.onPlayerQuit(PlayerQuitListener.java:83) [CombatLog.jar:?]
	at sun.reflect.GeneratedMethodAccessor341.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) [server.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:364) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:875) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.basic.User.killedBy(User.java:323) ~[?:?]
	at net.dzikoysk.funnyguilds.listener.PlayerDeath.onDeath(PlayerDeath.java:96) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor363.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"4c7641d"]
	... 26 more
```

**Comment by Kamilkime** [comment]
A to skąd?

**Comment by Kamilkime** [comment]
I stare FG 4.1.0

**Comment by kacperduras** [comment]
Zreprodukowałem u siebie na najnowszym, zaraz naprawię.

**Comment by Kamilkime** [comment]
Ale **net.dzikoysk.funnyguilds.basic.User.killedBy(User.java:323)**? Przecież już naprawiałem coś takiego ;/

**Comment by kacperduras** [comment]
Najwyraźniej błąd dalej występuje, przetestowałem fixa - już wrzucam.
