### ISSUE TITLE
Nie działa TAB wersja 1.8.8

### ISSUE THREAD

**Issue by Klaud3k** [FunnyGuilds/FunnyGuilds#829]
Witam nie działa TAB wersja serwera 1.8.8 czysty confing nic nie modyfikowane

**Comment by Kamilkime** [comment]
Podeślij log z serwera

**Comment by Klaud3k** [comment]
`[20:57:21] [Server thread/INFO]: [FunnyGuilds] Enabling FunnyGuilds v4.2.0 Tribute-d93656f
[20:57:21] [Server thread/INFO]: [FunnyGuilds] Available Processors: 2
[20:57:21] [Server thread/INFO]: [FunnyGuilds] Active Threads: 12
[20:57:22] [Server thread/INFO]: [FunnyGuilds] Loaded users: 0
[20:57:22] [Server thread/INFO]: [FunnyGuilds] Loaded regions: 0
[20:57:22] [Server thread/INFO]: [FunnyGuilds] Loaded guilds: 0
[20:57:22] [Server thread/ERROR]: Error occurred while enabling FunnyGuilds v4.2.0 Tribute-d93656f (Is it up to date?)
java.lang.IllegalArgumentException: Invalid UUID string: U,0,U
	at java.util.UUID.fromString(UUID.java:194) ~[?:1.8.0_161]
	at net.dzikoysk.funnyguilds.data.Data.invitations(Data.java:102) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Data.<init>(Data.java:28) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Data.getInstance(Data.java:43) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Manager.<init>(Manager.java:32) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:80) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

**Comment by Klaud3k** [comment]
http://wklej.org/id/3394023/

**Comment by Kamilkime** [comment]
Masz coś zepsute w pliku od zaproszeń, edytowałeś go ręcznie?

**Comment by Klaud3k** [comment]
Nic nie edytowałem , wgrałem czysty plugin :)

**Comment by Klaud3k** [comment]
Tylko plik .jar reszte samo generowało :D

**Comment by Kamilkime** [comment]
To skasuj plik **invitations.yml** i powinno działać

**Comment by Klaud3k** [comment]
Tab nadal nie działa a to konsoleta http://wklej.org/id/3394038/

**Comment by Kamilkime** [comment]
Najlepiej podeślij cały plik logów i cały config FG

**Comment by Klaud3k** [comment]
Mistrzu mówię ci .... FunnyGuilds , nic nie było zmieniane , generuje się automatycznie , a jak chcesz cały plik logów to pw

**Comment by Klaud3k** [comment]
http://wklej.org/id/3394042/

**Comment by Kamilkime** [comment]
Nadal potrzebuję cały plik logów, żeby wymyślić czemu nie działa

**Comment by Klaud3k** [comment]
Podesłałem na emaila

**Comment by Klaud3k** [comment]
:O Tab po jakimś czasie sam wskoczył

**Comment by insertt** [comment]
Czyli issue można uznać za rozwiązany - gdybyś potrzebował jeszcze pomocy, stwórz nowy issue wraz z opisem problemu :-)

**Comment by Kamilkime** [comment]
Może się gryźć ProtocolTab, który masz wgrany na serwerze

**Comment by kacperduras** [comment]
@Kamilkime nie `może`, tylko `na pewno`. Muszę pomyśleć nad opcjonalnym wsparciem ProtocolTab'a w FG by ten problem wyeliminować.
