### ISSUE TITLE
Źle wklejany schemat gildii przy jej zakładaniu

### ISSUE THREAD

**Issue by Pak3rP** [FunnyGuilds/FunnyGuilds#848]
po
1. Nie działają gildie na tabie! Po zalozeniu gildi nie pokazuję się w top na tabie... Albo coś popsułem!
2. Nie działa własne serce gildi! Dałem sobie gąbke i zrobiłem schemat, zapisałem go WorldEditem , zrobilem reload i zakladam gildie a tu nie dziala! zapisałem schemat komenda /schematic save schematic funnyguilds, i sie nie generuje to z gąbką jako serce.
Prosze o odpowiedz

**Comment by Kamilkime** [comment]
1. Sekcja **guild-min-members** w configu
2. Czy ustawiłeś ten schematic, i czy go włączyłeś, w configu FG?

**Comment by kacperduras** [comment]
```
Czy ustawiłeś ten schematic, i czy go włączyłeś, w configu FG?
```
Tak po za tym - czy wskazałeś właściwe lokalizacje pliku ze schematem? To też jest istotne.

**Comment by Pak3rP** [comment]
tak włączyłem go, ale robi się sama gąbka z powietrzem zamiast gabki i obsidianu

**Comment by Kamilkime** [comment]
To na pewno dobrze zrobiłeś schematic? Poleć gdzieś, wpisz **//schem load nazwaSchematica**, potem **//paste** i zobacz, czy pojawia się to co chciałeś

**Comment by Pak3rP** [comment]
tak robi się to co chciałem...
może na pw ip servera podac na ktorym to testuje ?? zobaczysz sam

**Comment by Kamilkime** [comment]
Wrzuć na pastebin log z serwera, config FG i podeślij screena folderu FG

**Comment by kacperduras** [comment]
Dobra, więc tak.
Zapisałeś schematic za pomocą tej komendy:
```
/schematic save schematic funnyguilds
```
a w configu masz podane:
```
# Nazwa pliku z schematem poczatkowym gildii
# Wklejenie schematu wymaga pluginu WorldEdit
guild-schematic-file-name: fg.schematic
```
gdzie powinno wyglądać tak:
```
# Nazwa pliku z schematem poczatkowym gildii
# Wklejenie schematu wymaga pluginu WorldEdit
guild-schematic-file-name: funnyguilds.schematic
```
Pominę tez fakt, że we folderze z plikami FunnyGuilds nie znajdziesz tego pliku, więc domyślnie wklei pustą przestrzeń, bo nie ma co wkleić - logiczne, co nie?

Wniosek: nie umiesz czytać konfiguracj.
Zamykam.

**Comment by Pak3rP** [comment]
Przepraszam że zawracam du** ale teraz zamiast robic się przynajmniej tego powietrza co bylo to wogóle pojawia się te kula(sphere).

**Comment by Pak3rP** [comment]
Config:
https://pastebin.com/w0jUmcUi

Schematic: 
![c](https://user-images.githubusercontent.com/38175675/38468678-e5f772dc-3b49-11e8-94ca-1230ba23cd92.jpg)
Co powstaje:
![a](https://user-images.githubusercontent.com/38175675/38468683-ee900a26-3b49-11e8-989d-0c75698424b2.jpg)
  
P.S
Kamilkime?? Czemu już nie nagrywasz ?

**Comment by Kamilkime** [comment]
Schematic ma być folerze FG, a ja nie mam czasu na nagrywanie

**Comment by kacperduras** [comment]
@Pak3rP 
```
Pominę tez fakt, że we folderze z plikami FunnyGuilds nie znajdziesz tego pliku, więc domyślnie wklei pustą przestrzeń, bo nie ma co wkleić - logiczne, co nie?
```

Czytasz co się do Ciebie piszę? Najwyraźniej nie.

**Comment by Pak3rP** [comment]
@kacperduras 
Ale spokojniej, ja poprostu chcę to ogarnąc bo fakt faktem to jest najlepszy plugin na gildie który w dalszym ciągu się rozwija.
Dodałem do folderu FunnyGuilds ten schematic i jak zakladam gildie to robi się tylko gąbka z pustą przestrzenią .
A chce aby było coś takiego po stworzeniu gildi.
a narazie robi się sama gąbka!

![a](https://user-images.githubusercontent.com/38175675/38468929-31f3d074-3b4d-11e8-8a02-fb85cbe163ff.jpg)

jak nie macie pomysłow jak to zrobić albo inne rady dac to może ktoś podeśle plugin z gotowym takim schematic'kiem ktory działa, ja sobie reszte skonfiguruje.

**Comment by Kamilkime** [comment]
Podeślij ten schematic

**Comment by Pak3rP** [comment]
https://www72.zippyshare.com/v/fAp2mhNj/file.html

**Comment by Pak3rP** [comment]
w consoli mam w dalszym ciągu:

[17:05:15 WARN]: [FunnyGuilds] Task #1152 for FunnyGuilds v4.3.0 Tribute-f23364a generated an exception java.lang.NullPointerException at net.dzikoysk.funnyguilds.basic.util.GuildUtils.lambda$deleteGuild$0(GuildUtils.java:48) ~[?:?] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]****

**Comment by Kamilkime** [comment]
Wiem, zrobiłem #850

**Comment by Pak3rP** [comment]
Nie dziala mi ten schematic! Próbuje , próbuje i nic... Może to wina wersji lub darmowego hostingu na ktorym testuje ?? (Wersja 1.8.8 Spigot)

**Comment by Kamilkime** [comment]
Dlatego jest #851, pracujemy nad tym

**Comment by kacperduras** [comment]
Czekaj na rozpatrzenie błędu #851

**Comment by Kamilkime** [comment]
Coś było nie tak ze schematem - użyłem tego i działa
https://drive.google.com/open?id=1lUNu4bSPxWMAQEMLoc08ziq0RkK9wQAy

**Comment by Pak3rP** [comment]
No teraz to odwaliloście. Niby cos sie robi ale wklepa sie Podzol z trawą.
Czym edytowac ten schematic ?

**Comment by Pak3rP** [comment]
Ostanie pytanie.
Można jakoś to zrobić żeby był ten schematic co ja chce, może bląd leży po stronie jakiegoś bloku.
Może trzeba użyc innych bloków. Albo jak to zrobic inaczej?? 
Jest cos do edytowania tych schematiców ?

**Comment by Kamilkime** [comment]
U mnie wszystko normalnie działa, możliwe, że ty masz coś nie tak z WorldEdit'em. Pobierz ponownie najnowszą wersję z bukkit.org

**Comment by jasuogra** [comment]
@uMnieDziała

**Comment by Pak3rP** [comment]
czyli problem dalej nie rozwiazany.
a moze byście difultowe dali takie wklejanie się tego schematicu zamiast kuli.
Ale i tak dziękuje za poswięcony czas.

**Comment by kacperduras** [comment]
```
czyli problem dalej nie rozwiazany.
```

Rozwiązany, problem z Twoim schematem i tyle.

**Comment by Kamilkime** [comment]
Kula domyślnie jest lepsza - nie trzeba dostarczać w FG żadnego schematu, wystarczy tylko prosta kula. A schemat każdy może sobie sam ustawić jaki chce (jeśli chce)
