### ISSUE TITLE
Błąd z wklejaniem schematów.

### ISSUE THREAD

**Issue by marcinkowalczyk2** [FunnyGuilds/FunnyGuilds#879]
Mimo posiadania schematu w WE, FunnyGuilds go nie wykrywa. Dzieję się tak tylko przy włączaniu pluginu, nie przy zakładaniu gildii.
Konfiguracja:
`paste-schematic-on-creation: true
guild-schematic-file-name: funnyguilds.schematic
paste-schematic-with-air: true`

Obecność schematu: https://imgur.com/a/SVphOlB

Bład:
`[14:47:52 ERROR]: [Server thread/ERROR] #!#
[14:47:52 ERROR]: [Server thread/ERROR] #!# [FunnyGuilds] Severe error:
[14:47:52 ERROR]: [Server thread/ERROR] #!#
[14:47:52 ERROR]: [Server thread/ERROR] #!# Server Information:
[14:47:52 ERROR]: [Server thread/ERROR] #!#   FunnyGuilds: 4.3.0 Tribute
[14:47:52 ERROR]: [Server thread/ERROR] #!#   Bukkit: 1.12.2-R0.1-SNAPSHOT
[14:47:52 ERROR]: [Server thread/ERROR] #!#   Java: 10.0.1
[14:47:52 ERROR]: [Server thread/ERROR] #!#   Thread: Thread[Server thread,5,main]
[14:47:52 ERROR]: [Server thread/ERROR] #!#   Running CraftBukkit: false
[14:47:52 ERROR]: [Server thread/ERROR] #!#
[14:47:52 ERROR]: [Server thread/ERROR] #!# Stack trace:
[14:47:52 ERROR]: [Server thread/ERROR] #!# Caused by: File with given name in field "guild-schematic-file-name" does not exist!
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at net.dzikoysk.funnyguilds.data.configs.PluginConfig.reload(PluginConfig.java:1191)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at net.dzikoysk.funnyguilds.data.Settings.<init>(Settings.java:16)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at net.dzikoysk.funnyguilds.data.Settings.getConfig(Settings.java:21)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:68)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:310)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:750)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at org.bukkit.Bukkit.reload(Bukkit.java:525)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[14:47:52 ERROR]: [Server thread/ERROR] #!#     at java.base/java.lang.Thread.run(Unknown Source)
[14:47:52 ERROR]: [Server thread/ERROR] #!#
[14:47:52 ERROR]: [Server thread/ERROR] #!# End of Error.
[14:47:52 ERROR]: [Server thread/ERROR] #!#`

**Comment by Kamilkime** [comment]
Plik ze schematem ma być w folderze FunnyGuilds

**Comment by marcinkowalczyk2** [comment]
Teraz pojawił się taki problem i występuje tylko gdy wklejanie schematów jest włączone.
`[15:17:03 INFO]: KrejzolekPR0 issued server command: /t zaloz ADMI adminii
[15:17:03 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 't zaloz ADMI adminii' in net.dzikoysk.funnyguilds.command.util.Performer(t)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_12_R1.TileEntity.a(Lnet/minecraft/server/v1_12_R1/NBTTagCompound;)V
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1.readTagIntoTileEntity(Spigot_v1_12_R1.java:116) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1.setBlock(Spigot_v1_12_R1.java:253) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:416) ~[?:?]
        at com.sk89q.worldedit.extent.world.FastModeExtent.setBlock(FastModeExtent.java:92) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.world.SurvivalModeExtent.setBlock(SurvivalModeExtent.java:88) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.world.BlockQuirkExtent.setBlock(BlockQuirkExtent.java:64) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.world.ChunkLoadingExtent.setBlock(ChunkLoadingExtent.java:66) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:67) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.inventory.BlockBagExtent.setBlock(BlockBagExtent.java:111) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.reorder.MultiStageReorder.setBlock(MultiStageReorder.java:93) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.ChangeSetExtent.setBlock(ChangeSetExtent.java:64) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.MaskingExtent.setBlock(MaskingExtent.java:69) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.validation.BlockChangeLimiter.setBlock(BlockChangeLimiter.java:87) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:504) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:547) ~[?:?]
        at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:78) ~[?:?]
        at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[?:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:57) ~[?:?]
        at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89) ~[?:?]
        at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[?:?]
        at net.dzikoysk.funnyguilds.element.schematic.SchematicHelper.pasteSchematic(SchematicHelper.java:46) ~[?:?]
        at net.dzikoysk.funnyguilds.command.ExcCreate.execute(ExcCreate.java:264) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:116) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:166) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:22) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        ... 14 more`

**Comment by marcinkowalczyk2** [comment]
Okej, zauważyłem jeszcze jedną rzecz, że jakaś cześć schematu zawsze się wkleja, a reszta nie ;)

**Comment by Kamilkime** [comment]
Jakiej dokładnie wersji FG używasz, oficjalnej 4.3.0?

**Comment by marcinkowalczyk2** [comment]
Tak

**Comment by Kamilkime** [comment]
To ściągnij najnowsze FG stąd: [FunnyGuilds Nightly](https://ci.kacperduras.pl/job/FunnyGuilds/)
Po kilku tygodniach od wydania 4.3.0 była poprawka we wklejaniu schematów, bo nie zawsze ono działało - może u ciebie też się to poprawi

**Comment by marcinkowalczyk2** [comment]
Wszystko działa, tylko trochę trwało zanim się wkleiło, ale to wina maszyny i wielkości schematu :/ Dzięki bardzo :)
