### ISSUE TITLE
Błąd player death event

### ISSUE THREAD

**Issue by mateulusz** [FunnyGuilds/FunnyGuilds#890]
Błąd:
`16:12:47] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to FunnyGuilds v4.3.0 Tribute-f23364a
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1311) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1621) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException: at index 0
	at net.dzikoysk.funnyguilds.libs.com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240) ~[?:?]
	at net.dzikoysk.funnyguilds.libs.com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231) ~[?:?]
	at net.dzikoysk.funnyguilds.libs.com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226) ~[?:?]
	at net.dzikoysk.funnyguilds.libs.com.google.common.collect.ImmutableList.construct(ImmutableList.java:303) ~[?:?]
	at net.dzikoysk.funnyguilds.libs.com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:258) ~[?:?]
	at net.dzikoysk.funnyguilds.concurrency.independent.IndependentThread.action(IndependentThread.java:43) ~[?:?]
	at net.dzikoysk.funnyguilds.concurrency.independent.IndependentThread.action(IndependentThread.java:67) ~[?:?]
	at net.dzikoysk.funnyguilds.listener.PlayerDeath.onDeath(PlayerDeath.java:176) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor349.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[easyhc.jar:git-Spigot-2086bb0-8cc5a7e]
	... 22 more`

**Comment by kacperduras** [comment]
Wersja FG?

**Comment by mateulusz** [comment]
Najnowsza

pon., 4 cze 2018, 17:55 użytkownik Kacper Duras <notifications@github.com>
napisał:

**Comment by insertt** [comment]
Zaktualizuj plugin do najnowszej wersji, ponieważ linijki wskazane w stacktrace nie pasują do aktualnego stanu kodu.
