### ISSUE TITLE
BungeeTabListPlus błąd

### ISSUE THREAD

**Issue by Gaway69** [FunnyGuilds/FunnyGuilds#899]
Hejka , jest jakiś problem btlp , nie działa :D Na moim 2 serwerze działa lecz na jednym nie . Dodam że jak wrzucę jarke 4.0.2 gdzie zostało dopiero dodane wsparcie to działa bez problemu. Oto błędy :
[13:38:45] [Server thread/INFO]: [FunnyGuilds] Enabling SmieszneGildie v4.3.0 Tribute-579555b
[13:38:45] [Server thread/WARN]: ERROR StatusLogger Unable to locate a logging implementation, using SimpleLogger
[13:38:46] [Server thread/INFO]: [FunnyGuilds] Loaded users: 4583
[13:38:46] [Server thread/INFO]: [FunnyGuilds] Loaded regions: 66
[13:38:46] [Server thread/INFO]: [FunnyGuilds] Loaded guilds: 66
[13:38:46] [Server thread/WARN]: java.lang.IllegalStateException: instance is null, is the plugin enabled?
[13:38:46] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
[13:38:46] [Server thread/WARN]: 	at codecrafter47.bungeetablistplus.api.bukkit.BungeeTabListPlusBukkitAPI.registerVariable(BungeeTabListPlusBukkitAPI.java:39)
[13:38:46] [Server thread/WARN]: 	at net.dzikoysk.funnyguilds.hook.BungeeTabListPlusHook.initVariableHook(BungeeTabListPlusHook.java:21)
[13:38:46] [Server thread/WARN]: 	at net.dzikoysk.funnyguilds.hook.PluginHook.lambda$init$1(PluginHook.java:35)
[13:38:46] [Server thread/WARN]: 	at net.dzikoysk.funnyguilds.hook.PluginHook.tryInit(PluginHook.java:54)
[13:38:46] [Server thread/WARN]: 	at net.dzikoysk.funnyguilds.hook.PluginHook.tryInit(PluginHook.java:65)
[13:38:46] [Server thread/WARN]: 	at net.dzikoysk.funnyguilds.hook.PluginHook.init(PluginHook.java:32)
[13:38:46] [Server thread/WARN]: 	at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:132)
[13:38:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[13:38:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[13:38:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[13:38:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[13:38:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[13:38:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[13:38:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[13:38:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[13:38:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[13:38:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[13:38:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:38:46] [Server thread/INFO]: [FunnyGuilds] MVdWPlaceholderAPI plugin could not be found, some features may not be available
[13:38:46] [Server thread/INFO]: [FunnyGuilds] Vault plugin could not be found, some features may not be available
[13:38:46] [Server thread/INFO]: [FunnyGuilds] PlaceholderAPI plugin could not be found, some features may not be available
[13:38:46] [Server thread/INFO]: [FunnyGuilds] ~ Created by FunnyGuilds Team ~

**Comment by hamsterofficial** [comment]
Plugin od API (BTLP) nie jest wykrywany, posiadasz najnowszą wersje?

**Comment by Kamilkime** [comment]
Hmm, to chyba pomoże
