### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Retrumek** [FunnyGuilds/FunnyGuilds#909]
```
[FunnyGuilds] Plugin FunnyGuilds v4.3.0 Tribute-55621fb generated an exception while executing task 25
java.lang.IllegalArgumentException: Can't compare unknown protocol type
    at protocolsupport.libs.org.apache.commons.lang3.Validate.isTrue(Validate.java:156) ~[?:?]
    at protocolsupport.api.ProtocolVersion$OrderId.compareTo(ProtocolVersion.java:363) ~[?:?]
    at protocolsupport.api.ProtocolVersion.isBefore(ProtocolVersion.java:136) ~[?:?]
    at net.dzikoysk.funnyguilds.system.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:52) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[fix.jar:git-Paper-1492]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [fix.jar:git-Paper-1492]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [fix.jar:git-Paper-1492]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by insertt** [comment]
Posiadasz zmodyfikowaną wersję pluginu, których niestety nie wspieramy
