### ISSUE TITLE
Błędy 1.13

### ISSUE THREAD

**Issue by Kamilkime** [FunnyGuilds/FunnyGuilds#913]
//FIXED:
```java
[02:59:12 WARN]: [FunnyGuilds] Plugin FunnyGuilds v4.3.0 Tribute-42c8fb0 generated an exception while executing task 1441
java.lang.IllegalArgumentException: Can not set net.minecraft.server.v1_13_R1.ChatMessageType field net.minecraft.server.v1_13_R1.PacketPlayOutChat.b to java.lang.Byte
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
        at jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:?]
        at java.lang.reflect.Field.set(Field.java:780) ~[?:?]
        at net.dzikoysk.funnyguilds.util.reflect.PacketCreator.withField(PacketCreator.java:71) ~[?:?]
        at net.dzikoysk.funnyguilds.element.notification.NotificationUtil.createActionbarNotification(NotificationUtil.java:92) ~[?:?]
        at net.dzikoysk.funnyguilds.listener.region.PlayerMove.lambda$onMove$2(PlayerMove.java:110) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.jar:git-Spigot-69774b3-23dc9a0]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.jar:git-Spigot-69774b3-23dc9a0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:844) [?:?]
```

```java
[03:06:04 ERROR]: [Server thread/ERROR] #!# An error occurred while saving data to flat file! Caused by: Exception
[03:06:04 WARN]: org.yaml.snakeyaml.error.YAMLException: No JavaBean properties found in net.dzikoysk.funnyguilds.element.Dummy
[03:06:04 WARN]:        at org.yaml.snakeyaml.introspector.PropertyUtils.getPropertiesMap(PropertyUtils.java:111)
[03:06:04 WARN]:        at org.yaml.snakeyaml.introspector.PropertyUtils.createPropertySet(PropertyUtils.java:138)
[03:06:04 WARN]:        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperties(PropertyUtils.java:131)
[03:06:04 WARN]:        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperties(PropertyUtils.java:124)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer.getProperties(Representer.java:272)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer$RepresentJavaBean.representData(Representer.java:75)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:106)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer.representJavaBeanProperty(Representer.java:148)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer.representJavaBean(Representer.java:106)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer$RepresentJavaBean.representData(Representer.java:75)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:106)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.BaseRepresenter.representSequence(BaseRepresenter.java:134)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentList.representData(SafeRepresenter.java:184)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer.representJavaBeanProperty(Representer.java:148)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer.representJavaBean(Representer.java:106)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer$RepresentJavaBean.representData(Representer.java:75)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:106)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer.representJavaBeanProperty(Representer.java:148)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer.representJavaBean(Representer.java:106)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.Representer$RepresentJavaBean.representData(Representer.java:75)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:106)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95)
[03:06:04 WARN]:        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65)
[03:06:04 WARN]:        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:306)
[03:06:04 WARN]:        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
[03:06:04 WARN]:        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245)
[03:06:04 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38)
[03:06:04 WARN]:        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68)
[03:06:04 WARN]:        at net.dzikoysk.funnyguilds.util.Yamler.save(Yamler.java:50)
[03:06:04 WARN]:        at net.dzikoysk.funnyguilds.data.flat.FlatGuild.serialize(FlatGuild.java:200)
[03:06:04 WARN]:        at net.dzikoysk.funnyguilds.data.flat.Flat.saveGuilds(Flat.java:190)
[03:06:04 WARN]:        at net.dzikoysk.funnyguilds.data.flat.Flat.save(Flat.java:89)
[03:06:04 WARN]:        at net.dzikoysk.funnyguilds.data.Manager.save(Manager.java:56)
[03:06:04 WARN]:        at net.dzikoysk.funnyguilds.concurrency.requests.DataSaveRequest.execute(DataSaveRequest.java:10)
[03:06:04 WARN]:        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.execute(ConcurrencyTask.java:33)
[03:06:04 WARN]:        at net.dzikoysk.funnyguilds.concurrency.ConcurrencyTask.run(ConcurrencyTask.java:22)
[03:06:04 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[03:06:04 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[03:06:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[03:06:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[03:06:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by Kamilkime** [comment]
BossBar wciąż nie został naprawiony :/

**Comment by kacperduras** [comment]
Wybacz, leci do TODO.
