### ISSUE TITLE
Task 39 .. java null

### ISSUE THREAD

**Issue by powerax** [FunnyGuilds/FunnyGuilds#915]
4:04:06 WARN]: Exception in thread "Craft Scheduler Thread - 1087"
[14:04:06 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-f23364a generated an exception while executing task 39
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
[14:04:07 WARN]: Exception in thread "Craft Scheduler Thread - 1090"
[14:04:07 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-f23364a generated an exception while executing task 39
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
[14:04:07 INFO]: KamshiYT probowal wykonac komende: /kit
[14:04:07 INFO]: KamshiYT: /kit
[14:04:08 WARN]: Exception in thread "Craft Scheduler Thread - 1094"
[14:04:08 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-f23364a generated an exception while executing task 39
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
[14:04:09 INFO]: Stivka1337 probowal wykonac komende: /r w sensie z ?
[14:04:09 WARN]: Exception in thread "Craft Scheduler Thread - 1072"
[14:04:09 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-f23364a generated an exception while executing task 39
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
[14:04:10 WARN]: Exception in thread "Craft Scheduler Thread - 1085"
[14:04:10 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-f23364a generated an exception while executing task 39
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException

/
Operatorzy

Wpisz nick gracza
Powerax

What shoud I do?

**Comment by Kamilkime** [comment]
Ściągnij najnowszy build z linku od nightly builds, link znajdziesz w opisie repozytorium FG

**Comment by powerax** [comment]
https://ci.kacperduras.pl/job/FunnyGuilds/

To ten link?

**Comment by Kamilkime** [comment]
Tak, najnowszy build powinien być kompatybilny bezproblemowo z 1.8-1.13, gdyby były jakieś problemy - użyj najwyżej jakiegoś starszego buildu, chyba 3 temu nie było 1.13

**Comment by Kamilkime** [comment]
Tak, najnowszy build powinien być kompatybilny bezproblemowo z 1.8-1.13, gdyby były jakieś problemy - użyj najwyżej jakiegoś starszego buildu, chyba 3 temu nie było 1.13
