### ISSUE TITLE
FunnyGuilds reload NPE

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyGuilds#927]
```
[23:17:40 INFO]: _an0 issued server command: /funnyguilds reload
[23:17:40 WARN]: Exception in thread "Thread-11" 
[23:17:40 WARN]: java.lang.NullPointerException
[23:17:40 WARN]: at org.diorite.cfg.system.elements.IterableTemplateElement.writeNewLines(IterableTemplateElement.java:168)
[23:17:40 WARN]: at org.diorite.cfg.system.elements.IterableTemplateElement.appendValue(IterableTemplateElement.java:110)
[23:17:40 WARN]: at org.diorite.cfg.system.elements.TemplateElement.write(TemplateElement.java:205)
[23:17:40 WARN]: at org.diorite.cfg.system.BaseTemplate.dump(BaseTemplate.java:257)
[23:17:40 WARN]: at org.diorite.cfg.system.Template.dump(Template.java:245)
[23:17:40 WARN]: at org.diorite.cfg.system.BaseTemplate.dump(BaseTemplate.java:270)
[23:17:40 WARN]: at org.diorite.cfg.system.Template.dump(Template.java:293)
[23:17:40 WARN]: at net.dzikoysk.funnyguilds.util.commons.ConfigUtils.loadConfig(ConfigUtils.java:46)
[23:17:40 WARN]: at net.dzikoysk.funnyguilds.data.Settings.<init>(Settings.java:15)
[23:17:40 WARN]: at net.dzikoysk.funnyguilds.command.ExcFunnyGuilds.lambda$reload$0(ExcFunnyGuilds.java:56)
[23:17:40 WARN]: at java.lang.Thread.run(Thread.java:748)
```

Najnowszy dev

**Comment by insertt** [comment]
Błąd najprawdopodobniej naprawiony wraz z aktualizacją diorite-configs.
