### ISSUE TITLE
Error w najnowszym nightly #101

### ISSUE THREAD

**Issue by powerax** [FunnyGuilds/FunnyGuilds#936]
Error zdarza się czasami przy wyjściu gracza z serwera. (Zapycha ram)

Config: https://pastebin.com/z3TbjdL4
Build: #101

ERROR:

```
[20:36:29] [Server thread/INFO]: BABIG_YT rozlaczyl sie z powodu: Disconnected Ping tego gracza wynosil: (48ms)
[20:36:29] [Craft Scheduler Thread - 53/WARN]: Exception in thread "Craft Scheduler Thread - 53" 
[20:36:29] [Craft Scheduler Thread - 53/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-2520e41 generated an exception while executing task 36
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at net.dzikoysk.funnyguilds.element.tablist.variable.DefaultTablistVariables.lambda$install$7(DefaultTablistVariables.java:63)
	at net.dzikoysk.funnyguilds.element.tablist.variable.impl.SimpleTablistVariable.get(SimpleTablistVariable.java:29)
	at net.dzikoysk.funnyguilds.element.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:23)
	at net.dzikoysk.funnyguilds.element.tablist.AbstractTablist.putVars(AbstractTablist.java:148)
	at net.dzikoysk.funnyguilds.element.tablist.impl.v1_8_R3.TablistImpl.send(TablistImpl.java:99)
	at net.dzikoysk.funnyguilds.system.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:57)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

**Comment by Kamilkime** [comment]
https://ci.kacperduras.pl/job/FunnyGuilds/102/
Powinno być ok =)
