### ISSUE TITLE
Czasami error

### ISSUE THREAD

**Issue by powerax** [FunnyGuilds/FunnyGuilds#941]
```bash
[14:42:19] [Server thread/INFO]: » Gracz Daj_Buszka_ zakupil efekt » Szybkie kopanie 3
[14:42:35] [Thread-361/INFO]: UUID of player C4lesin is 26ac1476-eae8-3e12-abac-a0180294d320
[14:42:36] [Server thread/INFO]: C4lesin[/85.22%%%%%%%%%0555] logged in with entity id 127255 at ([world]0.4945105786516466, 70.0, 0.5456627880628162)
[14:42:36] [Craft Scheduler Thread - 328/WARN]: Exception in thread "Craft Scheduler Thread - 328" 
[14:42:36] [pool-12-thread-1/INFO]: Stworzono pusty config: /home/e156251/pliki/plugins/Essentials/userdata/26ac1476-eae8-3e12-abac-a0180294d320.yml
[14:42:36] [Craft Scheduler Thread - 328/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-58ee73b generated an exception while executing task 35
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1471)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at java.util.HashSet.<init>(HashSet.java:120)
	at net.dzikoysk.funnyguilds.basic.user.UserUtils.getUsers(UserUtils.java:21)
	at net.dzikoysk.funnyguilds.element.tablist.variable.DefaultTablistVariables.lambda$createFunnyVariables$10(DefaultTablistVariables.java:78)
	at net.dzikoysk.funnyguilds.element.tablist.variable.impl.SimpleTablistVariable.get(SimpleTablistVariable.java:29)
	at net.dzikoysk.funnyguilds.element.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:23)
	at net.dzikoysk.funnyguilds.element.tablist.AbstractTablist.putVars(AbstractTablist.java:149)
	at net.dzikoysk.funnyguilds.element.tablist.impl.v1_8_R3.TablistImpl.send(TablistImpl.java:99)
	at net.dzikoysk.funnyguilds.system.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:57)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[14:42:38] [Server thread/INFO]: Daj_Buszka_ issued server command: /schowek
[14:42:47] [Server thread/INFO]: NozbikKM issued server command: /schowek
```

```bash
[16:23:43] [Async Chat Thread - #42/INFO]: [BEKA] [1180] SWAGER Nie_Umiem_Liczyc >> w sumie to nic nie za-aliscie
[16:23:47] [Thread-433/INFO]: UUID of player Zbysiek2k69 is 56895dff-92e7-3e5c-a378-a1e5cc1c88fa
[16:23:47] [Server thread/INFO]: Zbysiek2k69[/46.76.%%%%%%603] logged in with entity id 204366 at ([world]0.4945105786516466, 70.0, 0.5456627880628162)
[16:23:47] [pool-12-thread-1/INFO]: Stworzono pusty config: /home/e156251/pliki/plugins/Essentials/userdata/56895dff-92e7-3e5c-a378-a1e5cc1c88fa.yml
[16:23:47] [Craft Scheduler Thread - 510/WARN]: Exception in thread "Craft Scheduler Thread - 510" 
[16:23:47] [Craft Scheduler Thread - 510/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-58ee73b generated an exception while executing task 35
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1471)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at java.util.HashSet.<init>(HashSet.java:120)
	at net.dzikoysk.funnyguilds.basic.user.UserUtils.getUsers(UserUtils.java:21)
	at net.dzikoysk.funnyguilds.element.tablist.variable.DefaultTablistVariables.lambda$createFunnyVariables$10(DefaultTablistVariables.java:78)
	at net.dzikoysk.funnyguilds.element.tablist.variable.impl.SimpleTablistVariable.get(SimpleTablistVariable.java:29)
	at net.dzikoysk.funnyguilds.element.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:23)
	at net.dzikoysk.funnyguilds.element.tablist.AbstractTablist.putVars(AbstractTablist.java:149)
	at net.dzikoysk.funnyguilds.element.tablist.impl.v1_8_R3.TablistImpl.send(TablistImpl.java:99)
	at net.dzikoysk.funnyguilds.system.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:57)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[16:23:48] [Async Chat Thread - #42/INFO]: [BEKA] [1180] SWAGER Nie_Umiem_Liczyc >> takiego ze no
```

**Comment by dzikoysk** [comment]
#943
