### ISSUE TITLE
Nadal wyrzuca z gildii po restarcie.

### ISSUE THREAD

**Issue by powerax** [FunnyGuilds/FunnyGuilds#947]
Przed restartem gildia ma np. 10 członków + lider, a po restarcie 0 członków + lider.
Build: 108
Proszę o naprawienie tego błędu.

Raz zdarzył się też taki warn:

[09:29:18] [Server thread/INFO]: Lutikriss lost connection: Disconnected
[09:29:18] [Craft Scheduler Thread - 391/WARN]: Exception in thread "Craft Scheduler Thread - 391" 
[09:29:18] [Craft Scheduler Thread - 391/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-5821959 generated an exception while executing task 35
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.element.tablist.variable.DefaultTablistVariables.lambda$null$4(DefaultTablistVariables.java:53)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:438)
	at java.util.stream.LongPipeline.sum(LongPipeline.java:396)
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
	at net.dzikoysk.funnyguilds.element.tablist.variable.DefaultTablistVariables.lambda$install$5(DefaultTablistVariables.java:53)
	at net.dzikoysk.funnyguilds.element.tablist.variable.impl.SimpleTablistVariable.get(SimpleTablistVariable.java:29)
	at net.dzikoysk.funnyguilds.element.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:23)
	at net.dzikoysk.funnyguilds.element.tablist.AbstractTablist.putVars(AbstractTablist.java:149)
	at net.dzikoysk.funnyguilds.element.tablist.impl.v1_8_R3.TablistImpl.send(TablistImpl.java:99)
	at net.dzikoysk.funnyguilds.system.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:57)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

**Comment by insertt** [comment]
Czy błąd z znikaniem członków gildii występuje za każdym razem?

**Comment by powerax** [comment]
tak i mam zapis na flat
