### ISSUE TITLE
Build 110 nie działa.

### ISSUE THREAD

**Issue by powerax** [FunnyGuilds/FunnyGuilds#948]
```bash
[04:02:25] [Server thread/INFO]: [FunnyGuilds] Enabling FunnyGuilds v4.3.0 Tribute-7cad8e2
[04:02:27] [Server thread/INFO]: [FunnyGuilds] Loaded users: 6198
[04:02:27] [Server thread/INFO]: [FunnyGuilds] Loaded regions: 78
[04:02:27] [Server thread/ERROR]: Error occurred while enabling FunnyGuilds v4.3.0 Tribute-7cad8e2 (Is it up to date?)
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.HashSet
	at net.dzikoysk.funnyguilds.data.flat.FlatGuild.deserialize(FlatGuild.java:45) ~[?:?]
	at net.dzikoysk.funnyguilds.data.flat.Flat.loadGuilds(Flat.java:214) ~[?:?]
	at net.dzikoysk.funnyguilds.data.flat.Flat.load(Flat.java:87) ~[?:?]
	at net.dzikoysk.funnyguilds.data.Manager.<init>(Manager.java:29) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:81) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[04:02:27] [Server thread/INFO]: [FunnyGuilds] Disabling FunnyGuilds v4.3.0 Tribute-7cad8e2
```

**Comment by dzikoysk** [comment]
https://ci.kacperduras.pl/job/FunnyGuilds/111/
