### ISSUE TITLE
WorldGuard 

### ISSUE THREAD

**Issue by DarkTigger1** [FunnyGuilds/FunnyGuilds#961]
Siema mam problem ponieważ posiadam silnik 1.8.8 na serwerze i najnowszą wersję FG. Błędy wyskakują mi mianowicie takie 

[21:46:49] [pool-15-thread-2/WARN]: [WorldGuard] WorldGuard encountered an unexpected error
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.sk89q.worldguard.internal.guava.util.concurrent.Futures.getDone(Futures.java:1170) ~[worldguard-6.2.1.jar:?]
	at com.sk89q.worldguard.internal.guava.util.concurrent.Futures$4.run(Futures.java:1121) [worldguard-6.2.1.jar:?]
	at com.sk89q.worldguard.internal.guava.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) [worldguard-6.2.1.jar:?]
	at com.sk89q.worldguard.internal.guava.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) [worldguard-6.2.1.jar:?]
	at com.sk89q.worldguard.internal.guava.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) [worldguard-6.2.1.jar:?]
	at com.sk89q.worldguard.internal.guava.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) [worldguard-6.2.1.jar:?]
	at com.sk89q.worldguard.internal.guava.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) [worldguard-6.2.1.jar:?]
	at com.sk89q.worldguard.internal.guava.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) [worldguard-6.2.1.jar:?]
	at com.sk89q.worldguard.internal.guava.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) [worldguard-6.2.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

Wersja WordGuarda: 6.2.1 
Wersja FG: najnowasza 

Przy zakładaniu, usuwaniu itd regionów wywala mi błąd taki jak wyżej podałem.
Wersja starsza WorldGuarda 6.1 nie wchodzi w grę ponieważ wtedy wywala błąd FunnyGuilds że posiadam za starą wersję WG i czegoś tam brakuje (ten błąd był już zgłaszany w issuses)

**Comment by Kamilkime** [comment]
FG 4.3.0 + WG starsze niż 6.2
https://hastebin.com/aqacufomex.sql

**Comment by DarkTigger1** [comment]
Wiadomo coś czy będzie poprawiony ten błąd czy nie?
