### ISSUE TITLE
Zakładanie gildii + schemat

### ISSUE THREAD

**Issue by Verdunek** [FunnyGuilds/FunnyGuilds#965]
Verdun1337 issued server command: /zaloz VERD 123132123
[18:25:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'zaloz VERD 123132123' in net.dzikoysk.funnyguilds.command.util.Performer(zaloz)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/world/World
        at net.dzikoysk.funnyguilds.command.ExcCreate.execute(ExcCreate.java:264) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:127) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:166) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:22) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-21fe707-e1ebe52]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.world.World
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at net.dzikoysk.funnyguilds.command.ExcCreate.execute(ExcCreate.java:264) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:127) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:166) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:22) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-21fe707-e1ebe52]
        ... 14 more

**Comment by Kamilkime** [comment]
Jakiej wersji WorldEdit'a używasz?

**Comment by Verdunek** [comment]
5.6

**Comment by Kamilkime** [comment]
Użyj WorldEdit'a dla swojej wersji MC - 6.1

**Comment by Verdunek** [comment]
już pobrałem i sprawdzam :0

**Comment by Verdunek** [comment]
oky Działa sorki za sprawianie problemu.
i Dzięki za poświęcony czas, miłego wieczoru :)
