### ISSUE TITLE
Błąd #156

### ISSUE THREAD

**Issue by Verdunek** [FunnyGuilds/FunnyGuilds#966]
[FunnyGuilds] Task #156 for FunnyGuilds v4.3.0 Tribute-f23364a generated an exception
java.lang.NullPointerException
        at net.dzikoysk.funnyguilds.basic.util.GuildUtils.lambda$deleteGuild$0(GuildUtils.java:48) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by Kamilkime** [comment]
Pewnie już dawno poprawiony - sprawdź tę wersję FG
https://drive.google.com/open?id=1BdUVjYqkx4R3wQvbqDX4bENRcSXwWR7d

**Comment by Verdunek** [comment]
Thx
