### ISSUE TITLE
Ping na minusie? - Error

### ISSUE THREAD

**Issue by powerax** [FunnyGuilds/FunnyGuilds#971]
Build: 112 ERROR:

[18:51:36] [Thread-640/INFO]: UUID of player Kazuma is 51818e90-ebcd-36f8-a482-4b56024fa934
[18:51:36] [Server thread/INFO]: Kazuma[/3xxxxx.137:30xxx24] logged in with entity id 240201 at ([world]0.46261603422615627, 86.0, 0.4715045063870323)
[18:51:38] [Craft Scheduler Thread - 1365/WARN]: Exception in thread "Craft Scheduler Thread - 1365" 
[18:51:38] [Craft Scheduler Thread - 1365/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-a6a6e85 generated an exception while executing task 35
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.dzikoysk.funnyguilds.util.IntegerRange$MissingFormatException: No format for value -236892253 and range PING found!
	at net.dzikoysk.funnyguilds.util.IntegerRange.inRange(IntegerRange.java:38)
	at net.dzikoysk.funnyguilds.element.tablist.variable.DefaultTablistVariables.lambda$createFunnyVariables$11(DefaultTablistVariables.java:80)
	at net.dzikoysk.funnyguilds.element.tablist.variable.impl.SimpleTablistVariable.get(SimpleTablistVariable.java:29)
	at net.dzikoysk.funnyguilds.element.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:23)
	at net.dzikoysk.funnyguilds.element.tablist.AbstractTablist.putVars(AbstractTablist.java:151)
	at net.dzikoysk.funnyguilds.element.tablist.impl.v1_8_R3.TablistImpl.send(TablistImpl.java:99)
	at net.dzikoysk.funnyguilds.system.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:57)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

**Comment by Kamilkime** [comment]
Ping jest pobierany z serwera, więc to już coś serwer odwala
