### ISSUE TITLE
Tak trochę najnowsze buildy nie działają.

### ISSUE THREAD

**Issue by powerax** [FunnyGuilds/FunnyGuilds#972]
[13:04:58 ERROR]: Error occurred while enabling FunnyGuilds v4.3.0 Tribute-75cea6e (Is it up to date?)
java.lang.NoClassDefFoundError: org/diorite/cfg/system/TemplateCreator
        at net.dzikoysk.funnyguilds.util.commons.ConfigUtils.loadConfig(ConfigUtils.java:18) ~[?:?]
        at net.dzikoysk.funnyguilds.data.Messages.<init>(Messages.java:20) ~[?:?]
        at net.dzikoysk.funnyguilds.data.Messages.getInstance(Messages.java:43) ~[?:?]
        at net.dzikoysk.funnyguilds.data.Manager.<init>(Manager.java:23) ~[?:?]
        at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:85) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[mc.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [mc.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [mc.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [mc.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [mc.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [mc.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [mc.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [mc.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [mc.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [mc.jar:git-Spigot-21fe707-e1ebe52]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]

**Comment by Kamilkime** [comment]
Powinno pomóc
https://drive.google.com/open?id=16nuU3nFQusiEJn4jYKCo0MG5bLUNOcSg
