### ISSUE TITLE
Tablista

### ISSUE THREAD

**Issue by Natusiek** [FunnyGuilds/FunnyGuilds#988]
Jak sa wylaczone regiony to osoby ktora jest w gildi i wejdzie na serwer  wywala taki blad i tab nie dziala:
```
`
[15:12:10 WARN]: Exception in thread "Craft Scheduler Thread - 33"
[15:12:10 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-f23364a generated an exception while executing task 19
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at net.dzikoysk.funnyguilds.element.tablist.variable.DefaultTablistVariables.lambda$install$48(DefaultTablistVariables.java:72)
        at net.dzikoysk.funnyguilds.element.tablist.variable.impl.GuildDependentTablistVariable.get(GuildDependentTablistVariable.java:33)
        at net.dzikoysk.funnyguilds.element.tablist.variable.TablistVariablesParser.createResultFor(TablistVariablesParser.java:23)
        at net.dzikoysk.funnyguilds.element.tablist.AbstractTablist.putVars(AbstractTablist.java:136)
        at net.dzikoysk.funnyguilds.element.tablist.impl.v1_8_R3.TablistImpl.send(TablistImpl.java:93)
        at net.dzikoysk.funnyguilds.system.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:57)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

`
```

**Comment by Kamilkime** [comment]
Błąd ten został naprawiony w późniejszych commitach, pobierz najnowszy Nightly Build i błąd zniknie - https://ci.insertt.pl/job/FunnyGuilds/
