### ISSUE TITLE
MC 1.8 - błąd inicjalizacji NotificationUtil

### ISSUE THREAD

**Issue by Kamilkime** [FunnyGuilds/FunnyGuilds#994]
```java
[13:33:20 WARN]: Exception in thread "Craft Scheduler Thread - 991" 
[13:33:20 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v4.3.0 Tribute-a62a93d generated an exception while executing task 31
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.dzikoysk.funnyguilds.element.notification.NotificationUtil
    at net.dzikoysk.funnyguilds.element.tablist.AbstractTablist.createBaseComponent(AbstractTablist.java:143)
    at net.dzikoysk.funnyguilds.element.tablist.impl.v1_8_R1.TablistImpl.send(TablistImpl.java:103)
    at net.dzikoysk.funnyguilds.system.AsynchronouslyRepeater.run(AsynchronouslyRepeater.java:57)
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
```

**Comment by insertt** [comment]
Błąd występuje regularnie, czy to jednorazowy przypadek?

**Comment by Kamilkime** [comment]
Jednorazowy
